<script type="text/javascript">
var ns_bookmark_popup = {
  target: null,
  over_timer : null,
  out_timer : null,
  to_touch_id : null,
  touching_id : null,
  clicked_id : null,
  auto_save_timer: null,
  reminder_textfields : ['reminder_title', 'reminder_description', 'reminder_tags','reminder_attend_datetime'],
  reminder_checkboxes : ['reminder_has_email_alarm','reminder_has_popup_alarm','reminder_has_mobile_alarm'],
  tmpl_functions : {
    getID: function() {
      // remove out bookmark popup before adding the new one
      $('.bookmark_popup[data-id="'+this.data.id+'"]').remove();
      return this.data.id;
    },
    hasReminderContent: function(){
      for ( var n in ns_bookmark_popup.reminder_textfields ){
        if (typeof this.data[ns_bookmark_popup.reminder_textfields[n]] != 'undefined'){
          if (this.data[ns_bookmark_popup.reminder_textfields[n]] != null && this.data[ns_bookmark_popup.reminder_textfields[n]] != '') 
            return true;
        }
      }
      for ( var n in ns_bookmark_popup.reminder_checkboxes ){
        if (typeof this.data[ns_bookmark_popup.reminder_checkboxes[n]] != 'undefined'){
          if (this.data[ns_bookmark_popup.reminder_checkboxes[n]] == 1) return true;
        }
      }
      return false;
    },
    getAlertTime: function(type){
      if (this.data['reminder_'+type+'_alarm_time'] == '' || this.data['reminder_'+type+'_alarm_time'] == null)
         return '<?php echo $this->translate('upon attend time') ?>';
      return this.data['reminder_'+type+'_alarm_time'] + ' ' + this.data['reminder_'+type+'_alarm_time_unit'];
    }
  },
  toggleBookmark: function(id){
      var parents = $('#sidebar li.list_item[data-id="'+id+'"], article[data-id="'+id+'"]');
      var this_popup = $('.bookmark_popup[data-id="'+id+'"]');
      var set_status = parents.hasClass("bookmarked") ? 0 : 1;
    <?php if (Zend_Auth::getInstance()->hasIdentity() && Common::getSession()->user != null) { ?>
      jQuery.ajax({
          type: "POST",
          url: "<?php echo $this->baseUrl('ajax/bookmark/trigger') ?>",
          data: "id="+id+"&set_status="+set_status,
          success: function(msg){
            if (parents.hasClass("bookmarked")){
              parents.find('.star_inner').removeClass('gold');
              parents.removeClass("bookmarked");
              parents.find('.reminder_title .text').hide();
              parents.find('.reminder_title .not_set').show();
              this_popup.find('.white, .bookmark_popup_set_reminder').hide();
              this_popup.data('has_white', 0);
            } else {
              parents.find('.star_inner').addClass('gold');
              parents.addClass("bookmarked");
              parents.find('.reminder_title .text').show();
              parents.find('.reminder_title .not_set').hide();
              //this_popup.find('.bookmark_popup_set_reminder').show();
              if (this_popup.data('has_white') == 1)
                this_popup.find('.bookmark_popup_set_reminder').hide();
              else 
                this_popup.find('.bookmark_popup_set_reminder').show();
              
              /*if (! this_popup.is(':visible')){ 
                ns_bookmark_popup.togglePopup(id); 
              }*/
            }
            if (ns_bookmark_popup.target == 'feeds'){
              ns_bookmark_popup.togglePopup(id);
            }
          },
          error: function(){
            alert ("<?php echo $this->translate('Connection failed. Please try again later.') ?>");
          },
          dataType:"json"
      });
    <? } else { ?>
          alert('Please login to add bookmark.');
    <?php } ?>
  },
  togglePopup: function(id){
    if (ns_bookmark_popup.target==null ) ns_bookmark_popup.target = 'sidebar';
    
    var this_popup = $('.bookmark_popup[data-id="'+id+'"]');
    if (this_popup.length){
      if ($('.bookmark_popup').not(this_popup).is(':visible')){
        $('.bookmark_popup, .more').not(this_popup).hide();
      }
         console.log(ns_bookmark_popup.target);
      if (ns_bookmark_popup.target == 'sidebar'){
        var trigger_popup_icon = $('.trigger_popup_icon');
        var parent = $('#sidebar ul:visible li[data-id="'+id+'"]');
          if (this_popup.is(':visible')){
           this_popup.hide();
           trigger_popup_icon.hide();
          }else{
           this_popup.data('target', ns_bookmark_popup.target);
           
           ns_bookmark_popup.adjustSidebarPopupPosition(id);
           this_popup.show();
           this_popup.find('.yellow').show();
           trigger_popup_icon.show();
           
           if (!parent.hasClass('bookmarked')){
            this_popup.find('.white, .bookmark_popup_set_reminder').hide();
            this_popup.data('has_white', 0);
           }
           
           this_popup.find('.bookmark_popup_inner .teaser').dotdotdot({
                wrap : 'letter',
                height: 60
           });
          }
         <?php /*if (parent.hasClass('bookmarked')) {
          this_popup.find('.bookmark_popup_set_reminder').show();
          this_popup.find('.white').hide();
         } else {
          this_popup.find('.bookmark_popup_set_reminder').hide();
         }*/ ?>
      } else if (ns_bookmark_popup.target == 'feeds'){
        var trigger_popup_icon = $('.trigger_popup_icon');
        var parent = $('article[data-id="'+id+'"]');
        var star = $('article[data-id="'+id+'"] .star');
        if (parent.hasClass('bookmarked')){
          if (this_popup.is(':visible')){
            this_popup.hide(); // close popup when clicking outside
            trigger_popup_icon.hide();
          } else {
            //init
            this_popup.data('target', ns_bookmark_popup.target);
            trigger_popup_icon.css('top', star.offset().top + 18);
            trigger_popup_icon.css('left',star.offset().left+3);
            this_popup.css('top', star.offset().top + 37);
            this_popup.css('left',star.offset().left - 270);
            this_popup.show();
            this_popup.find('.yellow, .bookmark_popup_set_reminder').hide();
            this_popup.find('.white').show();
            this_popup.data('has_white', 1);
            ns_bookmark_popup.showReminderFields();
            trigger_popup_icon.show();
          }
        }else{
          this_popup.hide();
          trigger_popup_icon.hide();
        }
      }
    }
    ns_event_reminder_form.init();
  },
  adjustSidebarPopupPosition: function(id){
    var this_popup = $('.bookmark_popup[data-id="'+id+'"]');
    var trigger_popup_icon = $('.trigger_popup_icon');
    
    var parent = $('#sidebar ul:visible li[data-id="'+id+'"]');
    var grandparent = parent.parents('ul');
    
    console.log(parent.offset())
    //init
    trigger_popup_icon.css('top', parent.offset().top + 5);
    trigger_popup_icon.css('left',grandparent.offset().left+grandparent.outerWidth( true ));
    this_popup.css('top', parent.offset().top);
    this_popup.css('left',grandparent.offset().left+grandparent.outerWidth( true )+trigger_popup_icon.outerWidth( true ));
    
    if (parent.offset().top + this_popup.height() > $(window).height() + $(window).scrollTop()){
  
      console.log('exceeded below!');
  
      if ($(window).height() < this_popup.height()){
        console.log('not enough window size!');
        this_popup.css('top', $(window).scrollTop()+5);
      }else{
        console.log('enough window size!');
        var parent_to_bottom_height = $(window).height() + $(window).scrollTop() - parent.offset().top;
        var remaining_height = this_popup.height() - parent_to_bottom_height;
        var sum = parseInt(this_popup.css('top')) - remaining_height - 5;
        this_popup.css('top', sum +'px');
      }
  
    }else if (parent.offset().top <= $(window).scrollTop()+10){
      console.log('exceeded above!');
      
      var top_to_parent_height =  parent.offset().top - $(window).scrollTop();
      
      this_popup.css('top', parent.offset().top + (10 - top_to_parent_height) +'px');
      
    }else{
      console.log('inside');
    }
    console.log(this_popup.offset());
  },
  showReminderFields : function(){
    $('.bookmark_popup_reminder_title').watermark("<?php echo $this->translate('Reminder Title') ?>");
    $('.bookmark_popup_reminder_detail').watermark("<?php echo $this->translate('Reminder Detail') ?>");
  }
};

jQuery(function($){
  $('body')
  .on('click',".bookmark_popup",function(e){
    e.stopPropagation();
  })
  .on('click',".star",function(e){
    e.stopPropagation();
    if ($(e.target).closest('article.post_content, article.detail_div').length){
      ns_bookmark_popup.target = 'feeds';
    } else if ($(e.target).closest('#sidebar li').length){
      ns_bookmark_popup.target = 'sidebar';
    }
    ns_bookmark_popup.toggleBookmark($(this).data('id'));
    ns_sidebar_bookmark_tab.is_reload = true;
    <?php /*if (ns_sidebar.activeTab=='#bookmark_tab' && ! $(e.target).closest('#bookmark_tab li').length) ns_sidebar.loadTab(true);*/?>
  })
  .on('click', '.bookmark_popup_set_reminder',function(e){
    e.stopPropagation();
    $(this).parents('.bookmark_popup').find('.white').show();
    $(this).parents('.bookmark_popup').data('has_white', 1);
    $(this).hide();
    ns_bookmark_popup.showReminderFields();
    return false;
  })
  
<?php //pending hover keyup... ?>
  $('body').on('keyup', '.bookmark_popup_form input, .bookmark_popup_form textarea',function(e){
    var _this = $(this); // copy of this object for further usage
    if (ns_bookmark_popup.auto_save_timer) clearTimeout(
      ns_bookmark_popup.auto_save_timer
    );
    ns_bookmark_popup.auto_save_timer = setTimeout(function() {
      ns_event_reminder_form.submitForm(_this.parents('.bookmark_popup_form'));
    }, 500);
  })
<?php //pending hover effect... ?>
  $('body')
    .on('click', '#highlight_tab li.list_item , #bookmark_tab li.list_item' , function(e) {
      e.stopPropagation();
      ns_bookmark_popup.target = 'sidebar';
     if (ns_bookmark_popup.clicked_id == null){
        $('#highlight_tab li, #bookmark_tab li').removeClass('clicked');
        if (! $('.bookmark_popup[data-id="'+$(this).data('id')+'"]').is(':visible'))
          ns_bookmark_popup.togglePopup($(this).data('id'));
        ns_bookmark_popup.clicked_id = $(this).data('id');
        $(this).addClass('clicked');
      } else {
        ns_bookmark_popup.togglePopup($(this).data('id'));
        $('#highlight_tab li, #bookmark_tab li').removeClass('clicked');
        if ($('.bookmark_popup[data-id="'+$(this).data('id')+'"]').is(':visible')){
          ns_bookmark_popup.clicked_id = $(this).data('id');
          $(this).addClass('clicked');
        }else{
          ns_bookmark_popup.clicked_id = null;
          $(this).removeClass('clicked');
        }
      }
      console.log(ns_bookmark_popup.clicked_id);
    })
    .on({
      mouseenter : function(e){
        $(this).data('hover',1);
      },
      mouseleave : function(e){
        $(this).data('hover',0);
      }
    }, '.bookmark_popup, #highlight_tab li.list_item , #bookmark_tab li.list_item')
    .on({
      mouseenter : function(e){
        console.log('hover');
        if (ns_bookmark_popup.over_timer != null){
          clearTimeout(ns_bookmark_popup.over_timer);
          ns_bookmark_popup.over_timer = null;
        }
        if(ns_bookmark_popup.out_timer!=null) {
          clearTimeout(ns_bookmark_popup.out_timer);
          ns_bookmark_popup.out_timer = null;
        }
        if (ns_bookmark_popup.clicked_id != null) return false;
        
        if (ns_bookmark_popup.touching_id == null){
        // if it is the first list item to touch
          ns_bookmark_popup.to_touch_id = $(this).data('id');
          ns_bookmark_popup.over_timer = setTimeout(function() {
            console.log('over timeout');
            if (ns_bookmark_popup.clicked_id != null || ns_bookmark_popup.out_timer!=null) return false;
            ns_bookmark_popup.target = 'sidebar';
            ns_bookmark_popup.togglePopup(ns_bookmark_popup.to_touch_id);
            ns_bookmark_popup.touching_id = ns_bookmark_popup.to_touch_id;
          }, 1500)
        }else if (ns_bookmark_popup.touching_id !=null && $(e.target).closest('[data-id="'+ns_bookmark_popup.touching_id+'"]').length){
          // if it is the same list item
          return false;
        } else {
          // if it is different list item
          ns_bookmark_popup.to_touch_id = $(this).data('id');
          ns_bookmark_popup.target = 'sidebar';
          ns_bookmark_popup.togglePopup(ns_bookmark_popup.to_touch_id);
          ns_bookmark_popup.touching_id = ns_bookmark_popup.to_touch_id;
        }
      },
      mouseleave: function(e){
        if (ns_bookmark_popup.clicked_id != null) return false;
        ns_bookmark_popup.out_timer = setTimeout(function() {
            console.log('out timeout');
            if (ns_bookmark_popup.touching_id != null && $('.bookmark_popup').is(':visible')
            ){
              console.log('this is outside popup too');
              if (ns_bookmark_popup.clicked_id != null) return false;
              ns_bookmark_popup.target = 'sidebar';
              ns_bookmark_popup.togglePopup(ns_bookmark_popup.touching_id);
              ns_bookmark_popup.touching_id = null;
            }
        }, 500);
      }
    }, '#highlight_tab li.list_item, #bookmark_tab li.list_item, .bookmark_popup[data-target!="feeds"]')
    .on({
      mouseenter : function(e){
        console.log('hover');
        if (ns_bookmark_popup.over_timer != null){
          clearTimeout(ns_bookmark_popup.over_timer);
          ns_bookmark_popup.over_timer = null;
        }
        if(ns_bookmark_popup.out_timer!=null) {
          clearTimeout(ns_bookmark_popup.out_timer);
          ns_bookmark_popup.out_timer = null;
        }
        if (ns_bookmark_popup.clicked_id != null) return false;
        
        if (ns_bookmark_popup.touching_id == null){
        // if it is the first list item to touch
          ns_bookmark_popup.to_touch_id = $(this).data('id');
          ns_bookmark_popup.over_timer = setTimeout(function() {
            console.log('over timeout');
            if (ns_bookmark_popup.clicked_id != null || ns_bookmark_popup.out_timer!=null) return false;
            ns_bookmark_popup.target = 'feeds';
            ns_bookmark_popup.togglePopup(ns_bookmark_popup.to_touch_id);
            ns_bookmark_popup.touching_id = ns_bookmark_popup.to_touch_id;
          }, 500)
        }else if (ns_bookmark_popup.touching_id !=null && $(e.target).closest('[data-id="'+ns_bookmark_popup.touching_id+'"]').length){
          // if it is the same list item
          return false;
        } else {
          // if it is different list item
          ns_bookmark_popup.to_touch_id = $(this).data('id');
          ns_bookmark_popup.target = 'feeds';
          ns_bookmark_popup.togglePopup(ns_bookmark_popup.to_touch_id);
          ns_bookmark_popup.touching_id = ns_bookmark_popup.to_touch_id;
        }
      },
      mouseleave: function(e){
        if (ns_bookmark_popup.clicked_id != null) return false;
        ns_bookmark_popup.out_timer = setTimeout(function() {
            console.log('out timeout');
            if (ns_bookmark_popup.touching_id != null && $('.bookmark_popup').is(':visible')
            ){
              console.log('this is outside popup too');
              if (ns_bookmark_popup.clicked_id != null) return false;
              ns_bookmark_popup.target = 'feeds';
              ns_bookmark_popup.togglePopup(ns_bookmark_popup.touching_id);
              ns_bookmark_popup.touching_id = null;
            }
        }, 500);
      }
    }, 'article .star, .bookmark_popup[data-target="feeds"]')
})  
</script>