<script type="text/javascript">
var ns_new_event_advanced={}
jQuery(function($){
  tinymce_ns.init('#new_event_datetime_note');
  tinymce_ns.init('#new_event_application_datetime_note');
  tinymce_ns.init('#new_event_price_note');
  tinymce_ns.init('#new_event_traffic_note');
  tinymce_ns.init('#new_event_organiser_detail');
  
  var current = 0;
  $.validator.addMethod("pageRequired", function(value, element) {
    var $element = $(element)
    //console.log($element)
    function match(index) {
    //console.log(index)
    //console.log(current)
      return current == index && $element.parents("#step" + (index + 1)).length;
    }
    console.log("result = " +match(0) || match(1) || match(2) || match(3));
    if (match(0) || match(1) || match(2) || match(3)) {
    //console.log("this.optional(element) " +this.optional(element));
      return !this.optional(element);
    }
    return "dependency-mismatch";
  }, $.validator.messages.required)
  
  var new_event_advanced_validate_options = $.extend(true, {}, new_event_basic_validate_options, {
    ignore:".new_event_save, .prev, .next",
    rules:{
      organiser_tel:{
        number: true
      },
      organiser_email: {
        email: true
      },
      organiser_website: {
        url: true
      }
    },
    onkeyup: false,
    onblur: false,
    submitHandler: function(form) {
      ns_common_foot.saveFormToCookie('new_event_advanced');
      ns_common_foot.saveFormToCookie('new_event_basic', $.cookie('new_event_advanced'));
      form.submit();
    }
  });
  
  ns_new_event_advanced = {
    init:function(){
      ns_new_event_map.initMap('new_event_place_map', 'new_event_place', 'new_event_place_lat', 'new_event_place_lng');
      ns_new_event_map.initMap('new_event_application_place_map', 'new_event_application_place', 'new_event_application_place_lat', 'new_event_application_place_lng');
    }
  };
  
  var v = $("#new_event_advanced").validate(new_event_advanced_validate_options);
  
  var accordion = $('.accordion-new').accordion({ 
    heightStyle: "content"
  });
  
  $('body').on('click','.next',function(){
    if (v.form()) {
      accordion.accordion("option", "active", $(this).data('value'));
      current = $(this).data('value');
      ns_new_event_advanced.init();
    }
  }).on('click','.prev',function(){
      accordion.accordion("option", "active", $(this).data('value'));
      current = $(this).data('value');
      ns_new_event_advanced.init();
  }).on('click','input.new_event_save',function(){
      ns_common_foot.saveFormToCookie('new_event_advanced');
      ns_common_foot.saveFormToCookie('new_event_basic', $.cookie('new_event_advanced'));
      ns_common_foot.showFlashMessages([{'success' : '<?php echo $this->translate('form saved!'); ?>'}]);
      return false;
  });
});
</script>
<?php if (Zend_Registry::get('config_ini')->server->online==1){
    echo $this->partial('js/new_event/init_map.phtml', array('mapDiv_ID'=>'new_event_place_map', 'ac_input_ID'=>'new_event_place', 'lat_input_ID'=>'new_event_place_lat', 'lng_input_ID'=>'new_event_place_lng', 'geo_locate_ID'=>'new_event_geo_locate'));
} ?>
