<script type="text/javascript">
jQuery(function($){
  tinymce_ns.init('#new_event_description');
  tinymce_ns.init('#new_event_datetime_note');
  tinymce_ns.init('#new_event_price_note');
  tinymce_ns.init('#new_event_traffic_note');
  tinymce_ns.init('#new_event_application_note');
  tinymce_ns.init('#new_event_organiser_note');
  $.validator.addMethod("pageRequired", function(value, element) {
    return jQuery.validator.methods.required.call(this, value, element);
  }, $.validator.messages.required);
  
  $('body').on('click','input.new_event_save',function(){
      ns_common_foot.saveFormToCookie('new_event_basic');
      //ns_common_foot.saveFormToCookie('new_event_advanced', $.cookie('new_event_basic'));
      ns_common_foot.showFlashMessages([{'success' : '<?php echo $this->translate('form saved!'); ?>'}]);
      return false;
  })/*.on('click','input.new_event_more_detail',function(){
      ns_common_foot.saveFormToCookie('new_event_basic');
      ns_common_foot.saveFormToCookie('new_event_advanced', $.cookie('new_event_basic'));
      window.location.replace('http://'+window.location.hostname+':'+window.location.port+'<?php echo $this->baseUrl('new-event/advanced')?>');
      return false;
  })*/
  
  $('#new_event_basic').validate(new_event_basic_validate_options);
});
</script>