<script type="text/javascript">
var ns_new_event_map ={
  initMap: function(mapDiv_ID, ac_input_ID, lat_input_ID, lng_input_ID) {
    var mapDiv = document.getElementById(mapDiv_ID);
        maps[mapDiv_ID] = new google.maps.Map(mapDiv, {
          mapTypeId: google.maps.MapTypeId.ROADMAP,
          zoomControl:true,
          scrollwheel: false
        });
        
    // autocomplete init + customization when hitting enter, the first result should be queried
    var ac_input = document.getElementById(ac_input_ID);
    autocompletes[mapDiv_ID] = new google.maps.places.Autocomplete(ac_input);
    autocompletes[mapDiv_ID].bindTo('bounds', maps[mapDiv_ID]);
    google.maps.event.addListener(autocompletes[mapDiv_ID], 'place_changed', function() {
        updateMapByPlace(autocompletes[mapDiv_ID].getPlace(), mapDiv_ID, lat_input_ID, lng_input_ID);
    });
    
    var position;
    
    // check if there is user defined latlng in input
    if (ns_common_foot.isNumber(jQuery('#'+lat_input_ID).val()) && ns_common_foot.isNumber(jQuery('#'+lng_input_ID).val())){
      position = new google.maps.LatLng(jQuery('#'+lat_input_ID).val(), jQuery('#'+lng_input_ID).val());  
      
      maps[mapDiv_ID].setCenter(position);
      maps[mapDiv_ID].setZoom(17);  
      
      markers[mapDiv_ID] = new google.maps.Marker({
        position: position,
        map: maps[mapDiv_ID]
      });
    } else {
      position = new google.maps.LatLng('22.3964280', '114.1094970');
      maps[mapDiv_ID].setZoom(9);  
      maps[mapDiv_ID].setCenter(position);
    }
  }
}


var markers = {};
var maps = {};
var home_icon='<?php echo $this->baseUrl('images/map/home.png')?>';
var autocompletes = {};

function updateMapByPlace(place, mapDiv_ID, lat_input_ID, lng_input_ID){
    if(typeof markers[mapDiv_ID] == 'undefined'){
      markers[mapDiv_ID] = new google.maps.Marker({
        map: maps[mapDiv_ID]
      });
    }
  
    markers[mapDiv_ID].setVisible(false);
    
    if (!place.geometry) {
        //var content = [{'error' : 'Your input place was not found. please correct the input.'}] ;
        //ns_common_foot.showFlashMessages(content);
        // Inform the user that a place was not found and return.
        alert ("please ensure you have input the right location.")
        return false;
    }
        // If the place has a geometry, then present it on a map.
    if (place.geometry.viewport) {
      maps[mapDiv_ID].fitBounds(place.geometry.viewport);
    } else {
      maps[mapDiv_ID].setCenter(place.geometry.location);
      maps[mapDiv_ID].setZoom(17);  
    }

    markers[mapDiv_ID].setPosition(place.geometry.location);
    markers[mapDiv_ID].setVisible(true);
     
    jQuery('#'+lat_input_ID).val(place.geometry.location.place_lat());
    jQuery('#'+lng_input_ID).val(place.geometry.location.place_lng());

}

// trigger from the geolocate image button
function handleGeolocation(mapDiv_ID, ac_input_ID, lat_input_ID, lng_input_ID){
    // Try HTML5 geolocation
    if(navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var pos = new google.maps.LatLng(position.coords.latitude,
                                         position.coords.longitude);
        
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({'location': pos,'language':'<?php echo Common::getSiteDisplayLang(); ?>'}, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            //if (results[1]) {
              
              updateMapByPlace(results[0], mapDiv_ID, lat_input_ID, lng_input_ID);
              
              //$('#'+ac_input_ID).val(results[1].formatted_address);
              // use this for most accurate geo location
              $('#'+ac_input_ID).val(results[0].formatted_address);
              
            //}
          }
        });
      }, handleGeolocationErrors);
    } else {
      // Browser doesn't support Geolocation
      alert('Your browser doesn\'t support Geolocation!');
    }
  
}
function handleGeolocationErrors(error)
{
    $('#feed-settings-page .location_settings').toggle();
    switch(error.code)
    {
        case error.PERMISSION_DENIED: alert("Please enable geo location function in your device and try again.");
        break;

        case error.POSITION_UNAVAILABLE: alert("Current position could not be detected.");
        break;

        case error.TIMEOUT: alert("Retrieving position timed out.");
        break;

        default: alert("Unknown error.");
        break;
    }
}


function selectFirstResult(mapDiv_ID, lat_input_ID, lng_input_ID, ac_input_ID) {
    $(".pac-container").hide();
    var firstResult = $(".pac-container .pac-item:first").text();
    
    var geocoder = new google.maps.Geocoder();
    geocoder.geocode({"address":firstResult }, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
            //if (results[1]) {
              
              updateMapByPlace(results[0], mapDiv_ID, lat_input_ID, lng_input_ID);
              
              //$('#'+ac_input_ID).val(results[1].formatted_address);
              // use this for most accurate geo location
              $('#'+ac_input_ID).val(results[0].formatted_address);
              
            //}
        }
    });
}

</script>