<script id="upload_user_thumbnail" type="text/x-jquery-tmpl">
        <div class="watcher_form save_form upload_thumbnail">
            <ul>
                <li>
                    <label>Upload a new avatar</label>
                    <input type="file" class="fileimg" />
                </li>
                <li>
                    <div class="upload_img avatar_div">
                        <ul>
                            <li class="active"><img src="<?php echo $this->baseUrl('images/upload_img1.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img2.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img3.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img4.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img5.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img1.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img2.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img3.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img4.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img5.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img1.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img2.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img3.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img4.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img5.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img3.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img4.gif')?>" alt="" width="48" />
                            </li>
                            <li><img src="<?php echo $this->baseUrl('images/upload_img5.gif')?>" alt="" width="48" />
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="none" style="text-align:center" >
                    <input type="submit" value="Save" class="submit1" />
                    <input type="submit" value="Cancel" class="submit1" />
                </li>
            </ul>
        </div>
</script>