<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<?php echo $this -> partial('js/new_event.phtml'); ?>
<?php echo $this -> partial('js/new_event/advanced.phtml'); ?>

<article class="main shadow">
  <section class="main_inner advanced_event_form">
    <a href="scrolltop"></a>
    <?php if(isset($this->errors)){ ?>
    <p class="has_error"><?php echo $this->translate('Please correct the errors and submit the form again');?>:</p>
    <ul class="errors"> 
     <?php  foreach($this->errors as $key1 => $value1){
        foreach ($value1 as $key2 => $value2){
          echo  '<li>'. $this->translate($key1).' '. $value2. '</li>';
        }
      }
      ?> 
    </ul>
    <?php } ?>
    <form id="new_event_advanced" name="new_event_advanced" action="" method="post">
      <div class="accordion">
        <div class="accordion_button1 first">
          <?php echo $this->translate('new_event_event_type');?>
        </div>
        <section class="accordion_content1 grey_area event_form" id="openDiv1">
          <div class="horizontal-padding">
            <?php echo $this->partial('partials/new-event/input/event_types.phtml'); ?> 
            <div class="f_div">
              <input type="submit" value="Next" id="next1" class="submit4" />
            </div>
          </div>
        </section>
        <div class="accordion_button1 second">
          Event Details
        </div>
        <section class="accordion_content1 grey_area event_form" id="openDiv2">
          <div class="horizontal-padding">
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_name')); ?> 
            <?php echo $this->partial('partials/new-event/input/place.phtml', array('name'=>'new_event_place')); ?> 
            <div class="f_div">
              <label><?php echo $this->translate('Period');?></label>
              <div class="f_div1">
                <input type="checkbox" id="new_event_is_any_time" name="new_event_is_any_time"/>
                <label class="l-a" for="new_event_is_any_time"><?php echo $this->translate('new_event_is_any_time');?></label>
              </div>
              <div class="f_div1 f_div2">
                <input type="checkbox" id="new_event_is_all_day" name="new_event_is_all_day" />
                <label class="l-a" for="new_event_is_all_day"><?php echo $this->translate('new_event_is_all_day');?></label>
              </div>
            </div>
            
            <div class="f_div">
              <label>&nbsp;</label>
              <input type="text" class="date_input" id="new_event_begin_date" name="new_event_begin_date" required  readonly="true" />
              <label class="l-a1"><strong>-</strong></label>
              <input type="text" class="date_input" id="new_event_end_date" name="new_event_end_date" required readonly="true" />
              &nbsp;
              <?php //<label class="l-a1"><strong>From</strong></label> ?>
              <input id="new_event_begin_time" name="new_event_begin_time" type="text" class="timepicker" required />
              <label class="l-a1"><strong>-</strong></label>
              <input id="new_event_end_time" name="new_event_end_time" type="text" class="timepicker" required />
              <a class="l-a2 timezone_trigger text_link" href="#"><?php echo $this->translate('Time Zone');?></a>
            </div>
            <div class="f_div">
              <label>&nbsp;</label>
              <input type="text" class="date_input" id="new_event_begin_date" name="new_event_begin_date" required  readonly="true" />
              <label class="l-a1"><strong>-</strong></label>
              <input type="text" class="date_input" id="new_event_end_date" name="new_event_end_date" required readonly="true" />
              &nbsp;
              <?php //<label class="l-a1"><strong>From</strong></label> ?>
              <input id="new_event_begin_time" name="new_event_begin_time" type="text" class="timepicker" required />
              <label class="l-a1"><strong>-</strong></label>
              <input id="new_event_end_time" name="new_event_end_time" type="text" class="timepicker" required />
              <a class="l-a2 timezone_trigger text_link" href="#"><?php echo $this->translate('Time Zone');?></a>
            </div>
            <div class="f_div timezone_input">
              <label><?php echo $this->translate('Time Zone');?></label>
                <?php echo $this->partial('partials/new-event/input/timezone.phtml'); ?>
            </div>
              
            <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_date_note')); ?>
              
            <div class="f_div">
              <label><?php echo $this->translate('new_event_tree_ids');?></label>
              <?php echo $this -> partial('partials/new-event/input/tree.phtml'); ?>
            </div>
            <div class="f_div">
              <label for="description"><?php echo $this->translate('new_event_description');?></label>
              <textarea class="full" rows="5" cols="25" id="new_event_description" name="new_event_description" ></textarea>
              <a href="#" class="toggle_editor text_link" id="new_event_description_toggle_editor">[<?php echo $this->translate('new_event_description_toggle_editor');?>]</a>
              <input type="hidden" value="" name="new_event_description_is_toggled" id="new_event_description_is_toggled">
            </div>
            
            <?php echo $this -> partial('partials/new-event/input/tags.phtml', array('title' => 'Tags')); ?>
            
            <div class="f_div div_center">
              <input type="submit" value="Prev" class="submit1" id="prev1" />
              <input type="submit" value="Next" class="submit2" id="next2" />
            </div>
          </div>
        </section>
        <div class="accordion_button1 third">
          Prices and Booking
        </div>
        <section class="accordion_content1 grey_area event_form" id="openDiv3">
          <div class="horizontal-padding">
            <div class="f_div">
              <label for="description"><?php echo $this->translate('new_event_application_time_note');?></label>
              <textarea class="full" rows="5" cols="25" id="new_event_date_note" name="new_event_description" ></textarea>
              <a href="#" class="toggle_editor text_link" id="new_event_application_time_note_toggle_editor">[<?php echo $this->translate('new_event_application_time_note_toggle_editor');?>]</a>
              <input type="hidden" value="" name="new_event_application_time_note_is_toggled" id="new_event_application_time_note_is_toggled">
            </div>
            <?php echo $this->partial('partials/new-event/input/place.phtml', array('name'=>'new_event_application_place')); ?> 
            <?php echo $this->partial('partials/new-event/input/price.phtml', array('name'=>'new_event_price')); ?>
            <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_price_note')); ?>
            <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_traffic_note')); ?>
            <div class="f_div div_center" >
              <input type="submit" value="Prev" class="submit1" id="prev2" />
              <input type="submit" value="Next" class="submit2" id="next3" />
            </div>
            <div>
              &nbsp;
            </div>
          </div>
        </section>
        <div class="accordion_button1 fourth">
          Organization Details
        </div>
        <section class="accordion_content1 grey_area event_form" id="openDiv4">
          
          <div class="horizontal-padding">
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_name')); ?> 
            
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_email')); ?> 
            
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_tel')); ?> 
            
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_website')); ?> 
            
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_detail')); ?> 
            <div class="f_div div_center">
              <input type="submit" value="Save" class="submit1" />
              <input type="submit" value="Prev" class="submit2" id="prev3" />
              <input type="submit" value="Submit" class="submit3" />
            </div>
          </div>
        </section>
      </div>
    </form>
  </section>
</article>
