<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<?php echo $this -> partial('js/new_event.phtml'); ?>
<?php echo $this -> partial('js/new_event/advanced.phtml'); ?>

<article class="main shadow">
  <section class="main_inner advanced_event_form">
    <a href="scrolltop"></a>
    <?php if(isset($this->errors)){ ?>
    <p class="has_error"><?php echo $this->translate('Please correct the errors and submit the form again');?>:</p>
    <ul class="errors"> 
     <?php  foreach($this->errors as $key1 => $value1){
        foreach ($value1 as $key2 => $value2){
          echo  '<li>'. $this->translate($key1).' '. $value2. '</li>';
        }
      }
      ?> 
    </ul>
    <?php } ?>
    <form id="new_event_advanced" name="new_event_advanced" action="" method="post" >
    	<ul id="stepForm" class="accordion-new">
      <li id="step1"><a href='#' class="ui-accordion-link"> </a>
        <div>
          <fieldset>
            <legend><?php echo $this->translate('new_event_event_type');?></legend>
            <div class="horizontal-padding">
              <?php echo $this->partial('partials/new-event/input/event_types.phtml'); ?> 
              <div class="f_div div_center">
               <input type="button" value="<?php echo $this->translate('new_event_save');?>" class="submit1 new_event_save"/>
                <input data-value="1" type="button" class="next submit4" value="Next" alt="Next" title="Next"/>
              </div>
            </div>
          </fieldset>
        </div>
      </li>
      <li id="step2"><a href='#' class="ui-accordion-link"> </a>
        <div>
          <fieldset>
            <legend>Event Details</legend>
            <div class="horizontal-padding">
              
              <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_name')); ?> 
              
              <?php echo $this->partial('partials/new-event/input/place.phtml', array('name'=>'new_event_place')); ?> 
              
              <?php echo $this->partial('partials/new-event/input/datetime.phtml'); ?>
              
              <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_date_note')); ?>
                
              <div class="f_div">
                <label><?php echo $this->translate('new_event_tree_ids');?></label>
                <?php echo $this -> partial('partials/new-event/input/tree.phtml'); ?>
              </div>
              <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_description')); ?>
              
              <?php echo $this -> partial('partials/new-event/input/tags.phtml', array('title' => 'Tags')); ?>
              
              <div class="f_div div_center">
               <input type="button" value="<?php echo $this->translate('new_event_save');?>" class="submit1 new_event_save"/>
                <input data-value="0" type="button" alt="Back" title="Back" value="Back" class="submit1 prev" />
                <input data-value="2" type="button" class="next submit4" value="Next" alt="Next" title="Next"/>
              </div>
            </div>
          </fieldset>
        </div>
      </li>
      <li id="step3"><a href='#' class="ui-accordion-link"> </a>
        <div>
          <fieldset>
            <legend><?php echo $this->translate('new_event_application_time_note');?></legend>
            <div class="horizontal-padding">
              <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_application_time_note')); ?>
              
              <?php echo $this->partial('partials/new-event/input/place.phtml', array('name'=>'new_event_application_place')); ?> 
              <?php echo $this->partial('partials/new-event/input/price.phtml', array('name'=>'new_event')); ?>
              <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_price_note')); ?>
              <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_traffic_note')); ?>
              <div class="f_div div_center" >
               <input type="button" value="<?php echo $this->translate('new_event_save');?>" class="submit1 new_event_save"/>
                <input data-value="1" type="button" alt="Back" title="Back" value="Back"  class="submit1 prev" />
                <input data-value="3" type="button" class="next submit4" value="Next" alt="Next" title="Next"/>
              </div>
            </div>
          </fieldset>
        </div>
      </li>
      <li id="step4"><a href='#' class="ui-accordion-link"> </a>
        <div>
          <fieldset>
            <legend><?php echo $this->translate('Organization Details');?></legend>
            <div class="horizontal-padding">
              <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_name')); ?> 
              
              <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_email')); ?> 
              
              <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_tel')); ?> 
              
              <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_website')); ?> 
              
              <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_detail')); ?> 
              <div class="f_div div_center">
               <input type="button" value="<?php echo $this->translate('new_event_save');?>" class="submit1 new_event_save"/>
                <input data-value="2" type="button" alt="Back" title="Back" value="Back" class="submit1 prev" />
              <input type="submit" value="<?php echo $this->translate('new_event_submit');?>" name="new_event_submit" class="submit1" id="new_event_submit" />
              </div>
            </div>
          </fieldset>
        </div>
      </li>
    </ul>
    </form>
  </section>
</article>
