<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<?php echo $this -> partial('js/new_event.phtml'); ?>
<article class="main shadow">
  <section class="main_inner event_form">
    <h1>Post An Event</h1>
    <section class="grey_area">
      <div class="horizontal-padding">
        <div class="e_type_div">
          <label>Event Type</label>
          <div class="allevent">
            <div class="all_div clearfix">
              <ul>
                <li>
                  <a href="JavaScript:void(1);" class="profile_pic allgap"> <img src="<?php echo $this->baseUrl('images/public_event.gif')?>" alt="Public Event"/> <h6>Public Event</h6> </a>
                </li>
                <li>
                  <a href="JavaScript:void(2);" class="profile_pic allgap"> <img src="<?php echo $this->baseUrl('images/private_event.gif')?>" alt="Private Event"/> <h6>Private Event</h6> </a>
                </li>
                <li>
                  <a href="JavaScript:void(3);" class="profile_pic"> <img src="<?php echo $this->baseUrl('images/attraction.gif')?>" alt="Attraction"/> <h6>Attraction</h6> </a>
                </li>
              </ul>
            </div>
            <div>
              <div id="div1">
                <p>
                  For events either you are the representative of the organizer or the information supplier of an event organized for the public.
                </p>
              </div>

              <div id="div2" style="display:none">
                <p>
                  For events either you are the representative of the organizer or the information supplier of an event organized for the Private.
                </p>
              </div>

              <div id="div3" style="display:none">
                <p>
                  For events either you are the representative of the organizer or the information supplier of an event organized for the Attraction.
                </p>
              </div>

            </div>

          </div>
        </div>
        <div class="f_div">
          <label>Event Name</label>
          <input type="text" class="full"  />
        </div>
        <div class="f_div">
          <label class="show_hide_map">Place</label>
          <input id="place" type="text" name="place" class="full" value="<?php echo $this->form_data['place'] ?>"/>
          <img id="geo_locate" src="<?php echo $this->baseUrl('images/location_icon.png')?>" class="l_icon" alt="geo locate..." />
        </div>
        <div class="f_div event_map">
          <input type="hidden" name="lat" value="<?php echo $this->form_data['lat'] ?>"/>
          <input type="hidden" name="lng" value="<?php echo $this->form_data['lng'] ?>"/>
          <div id="map"></div>
        </div>
        <div class="f_div">
          <label>Period</label>
          <div class="f_div1">
            <input type="hidden" name="is_time_specific" value="0" />
            <input type="checkbox" id="is_time_specific" name="is_time_specific" checked="checked"/>
            <label class="l-a" for="is_time_specific">Time specific</label>
          </div>
          <div class="f_div1 f_div2">
            <input type="hidden" name="is_all_day" value="0" />
            <input type="checkbox" id="is_all_day" name="is_all_day" />
            <label class="l-a" for="is_all_day">All days</label>
          </div>
        </div>
        <div class="f_div">
          <label>&nbsp;</label>
          <input type="text" class="date_input" id="event_begin_date" />
          <label class="l-a1"><strong>-</strong></label>
          <input type="text" class="date_input" id="event_end_date" />
          &nbsp;
          <?php //<label class="l-a1"><strong>From</strong></label> ?>
          <input id="event_begin_time" type="text" class="timepicker"  />
          <label class="l-a1"><strong>-</strong></label>
          <input id="event_end_time" type="text" class="timepicker" />
          <a class="l-a2 timezone_trigger" href="#">Time Zone</a>
        </div>
        <div class="f_div timezone_input">
          <label>Time Zone</label>
          <select class="country middleSel">
            <option>Hong Kong</option>
          </select>
          <select class="city middleSel">
            <option>Hong Kong</option>
          </select>
          <?php //<input type="text" value="Hong Kong (+08:00)" class="middle2" /> ?>
        </div>
      </div>
      <div class="deep_grey_area">
        <div class="horizontal-padding clearfix">
          <div class="f_div">
            <label>&nbsp;</label>
            <div class="f_c_r">
              The following fields are optional but we strongly recommend you to provide
            </div>
          </div>
          <div class="f_div">
            <label>Category</label>
          <?php echo $this->partial('partials/new-event/input/tree.phtml',array('title'=>'Category')); ?>
          </div>
          <div class="f_div">
            <label for="description">Description</label>
            <textarea class="full" rows="4" id="description" ></textarea>
          </div>
          <div class="f_div">
            <label>Price</label>
            <div class="f_div1">
              <input type="checkbox" id="price-free" onclick="$(this).is(':checked') && $('#priceFree').slideDown('slow') || $('#priceFree').slideUp('slow');" />
              <label class="l-a" for="price-free">Is it free?</label>
            </div>

          </div>
          <div id="priceFree" class="f_div" style="display:none;">
            <label>Range</label>
            <input type="text" class="smallInput" value="min" onclick="if(this.value == 'min'){this.value='';}" onblur="if(this.value==''){this.value='min'};">
            <label class="l-a1"><strong>To</strong></label>
            <input type="text" class="smallInput" value="max" onclick="if(this.value == 'max'){this.value='';}" onblur="if(this.value==''){this.value='max'};">
            &nbsp;
            <label class="l-a1"><strong>The highest and lowest prices</strong></label>
          </div>
          <div class="f_div">
            <label>Tags</label>
            <a href="javascript:void(0)" class="choose chooseTag">Add tags to personalize your event exposure</a>
          </div>
          <div class="tree_tag clearfix" id="addTag">
            <div class="mainhead">
              Add tags
            </div>
            <div class="eventSlide add_category_div">
              <div class="f_div">
                <select>
                  <option>Hot Group</option>
                </select><label>Filter by</label>
                <input type="text" value="Use a keyword to filter out unwanted tags" class="middle2" onclick="if(this.value == 'Use a keyword to filter out unwanted tags'){this.value='';}" onblur="if(this.value==''){this.value='Use a keyword to filter out unwanted tags'};" >
                <nav class="all_selected right">
                  <ul>
                    <li>
                      <a href="#">All</a>
                    </li>
                    <li>
                      <a href="#">Selected</a>
                    </li>
                  </ul>
                </nav>
              </div>
              <div class="div_category">
                <select multiple="multiple" size="8" class="category_select">
                  <option>pollution</option>
                  <option>ecology</option>
                  <option>green</option>
                  <option selected="selected">environmental</option>
                  <option>clean</option>
                  <option>acid</option>
                  <option>addition</option>
                  <option>agricultural</option>
                </select>
                <select multiple="multiple" size="8" class="category_select">
                  <option>atmosphere</option>
                  <option>chemical</option>
                  <option>coal</option>
                  <option>combustion</option>
                  <option selected="selected">control</option>
                  <option>detrimental</option>
                  <option>disposal</option>
                  <option>effects</option>
                </select>
                <select multiple="multiple" size="8" class="category_select">
                  <option>following</option>
                  <option>gases</option>
                  <option selected="selected">harmful</option>
                  <option>health</option>
                  <option>human</option>
                  <option>industrial</option>
                  <option>introduction</option>
                  <option>land</option>
                </select>
                <select multiple="multiple" size="8" class="category_select">
                  <option>smoke</option>
                  <option>smoker</option>
                  <option selected="selected">soil</option>
                  <option>solid</option>
                  <option>urban</option>
                  <option>used</option>
                  <option>waste</option>
                  <option>water</option>
                </select>
              </div>
              <div class="f_div">
                <label><strong>New Tags</strong></label>
                <input type="text" class="middle1" value="Enter new tags here and separate them with commas">
              </div>

              <div class="div_center">
                <input type="submit" value="Confirm" class="submit1" id="tagConfirm1" />
                <input type="submit" value="Cancel" class="submit2" id="tagCancel1" />
              </div>

            </div>
          </div>
        </div>

      </div>
      <div class="horizontal-padding">
        <div class="f_div"></div>
        <div class="f_div">
          <label>&nbsp;</label>
          <input type="submit" value="Save" class="submit1" id="eventSave" />
          <input type="submit" value="Post" class="submit2" id="eventPost" />
          <input type="submit" value="More Details" class="submit3" />

        </div>
      </div>
    </section>
  </section>
</article>
