<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<?php echo $this -> partial('js/new_event.phtml'); ?>
<?php echo $this -> partial('js/new_event/basic.phtml'); ?>
<style>
</style>
<article class="main shadow">
  <section class="main_inner event_form">
    <h1><?php echo $this->translate('New Event');?></h1>
    <div class="grey_area">
    
    <div class="error_container" <?php if(!isset($this->errors)){ ?>style="display:none;"<?php } ?>>
      <p class="has_error" ><?php echo $this->translate('Please correct the errors and submit the form again');?>:</p>
      <ul class="errors"> 
     <?php  if(isset($this->errors)){
        foreach($this->errors as $key1 => $value1){
          foreach ($value1 as $key2 => $value2){
            echo  '<li>'. $this->translate($key1).' '. $value2. '</li>';
          }
        }
      }
      ?> 
    </ul>
    </div>
      <form id="new_event_basic" name="new_event_basic" action="" method="post">
        <div class="horizontal-padding">
          <?php echo $this->partial('partials/new-event/input/event_types.phtml'); ?> 
          
          <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_name')); ?> 
            
            <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_description')); ?>
          
          <div class="new_event_place">
            
            <?php echo $this->partial('partials/new-event/input/place.phtml', array('name'=>'new_event_place')); ?> 
            <div class="new_event_traffic_note">
              <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_traffic_note')); ?>
            </div>
          
          </div>
          
          <div class="new_event_datetime">
            <?php echo $this->partial('partials/new-event/input/datetime.phtml'); ?>
            <div class="new_event_datetime_note">
              <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_datetime_note')); ?>
            </div>
            
          </div>
          
          <?php echo $this -> partial('partials/new-event/input/tree.phtml', array('name'=>'new_event_tree_ids')); ?>
              
            <?php echo $this -> partial('partials/new-event/input/tags.phtml', array('title' => 'Tags')); ?>
        </div>
        <div class="deep_grey_area">
          <div class="horizontal-padding clearfix">
            <div class="f_div">
              <label>&nbsp;</label>
              <div class="f_c_r">
                The following fields are optional but we strongly recommend you to provide
              </div>
            </div>
            
            <div class="new_event_price">
              <?php echo $this->partial('partials/new-event/input/price.phtml', array('name'=>'new_event_price')); ?>
              <div class="new_event_price_note">
                <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_price_note')); ?>
              </div>
            </div>

            
            <div class="new_event_application">
              <div class="new_event_application_datetime_note">
                <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_application_datetime_note')); ?>
              </div>
            </div>
            
            <div class="new_event_organiser">
              <div class="new_event_organiser_detail">
                <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_name')); ?> 
                <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_organiser_detail')); ?>
              </div>
            </div>
            <?php /*?>
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_name')); ?> 
            
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_email')); ?> 
            
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_tel')); ?> 
            
            <?php echo $this->partial('partials/new-event/input/text.phtml', array('name'=>'new_event_organiser_website'));?>
            
            <?php echo $this->partial('partials/new-event/input/textarea.phtml', array('name'=>'new_event_organiser_detail')); */?>
          </div>

        </div>
        <div class="horizontal-padding">
          <div class="f_div">
            <label>&nbsp;</label>
            <input type="button" value="<?php echo $this->translate('new_event_load');?>"  class="ignore submit1 new_event_load"/>
            <input type="button" value="<?php echo $this->translate('new_event_save');?>"  class="ignore submit1 new_event_save"/>
            <input type="submit" value="<?php echo $this->translate('new_event_submit');?>" name="new_event_submit" class="ignore submit2" id="new_event_submit" />
            <?php /*<input type="button" value="<?php echo $this->translate('new_event_more_detail');?>" class="submit3 new_event_more_detail"/>*/?>
          </div>
        </div>
      </form>
    </div>
  </section>
</article>
