<?php /* <div class="bookmark_box_trigger">
    <div class="popup_bor watcher_gap">
        <div class="asaid_popup_main">
            <a title="Close" class="right_watcher_close" href="#">X</a>
            <form>
                <div id="main_innerWatcher2">

                    <section class="watcher_details watch_bor watch_color">
                        <h6 class="nonselect headgap watcheDetail" data-data-target="2">Watcher Detail</h6>
                        <section id="watcherDetailForm2" class="eventWatcherDetails">
                            <div class="watcher_form gap_top">
                                <ul>
                                    <li>
                                        <input type="text" value="Enter a brief watcher title here" class="txt" />
                                    </li>
                                    <li>
                                        <textarea rows="5" class="txt">Enter your event watcher detail here</textarea>
                                    </li>
                                    <li>
                                        <label>Remind Time</label>
                                        <input type="text" value="2012-4-4" class="d_input" />
                                        <input type="text" value="9:20" class="t_input" />
                                        <a href="#"><img src="images/alarm_bg.png" alt="alarm" height="21" /></a>
                                    </li>
                                </ul>
                            </div>
                            <div class="watcher_form watch_bor watcher_form_gap">
                                <ul>
                                    <li>
                                        <label class="tag_label">Tag</label>
                                        <select>
                                            <option>Select a group</option>
                                        </select>
                                    </li>
                                    <li>
                                        <section class="tag_l" >
                                            <strong>Tags:</strong><a href="#">Tag1</a> | <a href="#">Taaag1</a> | <a href="#">Taaaaag1</a> | <a href="#">Taaaag1</a> | <a href="#">Taaaaag1</a> | <a href="#">Taaag1</a> | <a href="#">Tagaa1</a> | <a href="#">Taaaaag1</a> | <a href="#">Tag1</a> | <a href="#">Tagaggg1</a> | <a href="#">Tagsaggg1</a>
                                        </section>
                                    </li>
                                    <li>
                                        <textarea rows="5" class="txt">Enter new tags here and separate them with commas</textarea>
                                    </li>
                                    <li class="none">
                                        <input type="submit" value="Save" data-target="2"  class="submit1 eventSave" />
                                        <input type="submit" value="Cancel" data-target="2" class="submit2 eventCancel" />
                                    </li>
                                </ul>
                            </div>
                        </section>
                        <section id="watcherDetailEdit2">
                            <div class="watcher_form gap_top">
                                <ul>
                                    <li>
                                        <strong>veggie produce info</strong>
                                    </li>
                                    <li>
                                        email to contact local agent, get Johnson to help sourcing 3 suppliers min.
                                    </li>
                                    <li>
                                        <strong>Watcher Alert </strong>: 2012-4-4, 9:20<a><img src="images/alarm_bg.png" alt="alarm" class="right" height="21" /></a>
                                    </li>
                                </ul>
                            </div>

                        </section>
                    </section>
                    <div class="watcher_form watcher_tag watch_bor">
                        <ul>
                            <li>
                                <section class="tag_l">
                                    <strong>Tags:</strong><a href="#">biz</a> | <a href="#">agriculture</a> | <a href="#">first-contact</a> | <a href="#">england</a>
                                </section>
                            </li>
                            <li class="none">
                                <input type="submit" value="Edit" data-target="2" class="submit1 eventEdit" />
                            </li>
                        </ul>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
*/ ?>

<script id="bookmark_box_trigger" type="text/x-jquery-tmpl">
        <form>
            <div id="main_innerWatcher2">
    
                <section class="watcher_details watch_bor watch_color">
                    <h6 class="nonselect headgap watcheDetail" data-data-target="2">Watcher Detail</h6>
                    <section id="watcherDetailForm2" class="eventWatcherDetails">
                        <div class="watcher_form gap_top">
                            <ul>
                                <li>
                                    <input type="text" value="Enter a brief watcher title here" class="txt" />
                                </li>
                                <li>
                                    <textarea rows="5" class="txt">Enter your event watcher detail here</textarea>
                                </li>
                                <li>
                                    <label>Remind Time</label>
                                    <input type="text" value="2012-4-4" class="d_input" />
                                    <input type="text" value="9:20" class="t_input" />
                                    <a href="#"><img src="images/alarm_bg.png" alt="alarm" height="21" /></a>
                                </li>
                            </ul>
                        </div>
                        <div class="watcher_form watch_bor watcher_form_gap">
                            <ul>
                                <li>
                                    <label class="tag_label">Tag</label>
                                    <select>
                                        <option>Select a group</option>
                                    </select>
                                </li>
                                <li>
                                    <section class="tag_l" >
                                        <strong>Tags:</strong><a href="#">Tag1</a> | <a href="#">Taaag1</a> | <a href="#">Taaaaag1</a> | <a href="#">Taaaag1</a> | <a href="#">Taaaaag1</a> | <a href="#">Taaag1</a> | <a href="#">Tagaa1</a> | <a href="#">Taaaaag1</a> | <a href="#">Tag1</a> | <a href="#">Tagaggg1</a> | <a href="#">Tagsaggg1</a>
                                    </section>
                                </li>
                                <li>
                                    <textarea rows="5" class="txt">Enter new tags here and separate them with commas</textarea>
                                </li>
                                <li class="none">
                                    <input type="submit" value="Save" data-target="2"  class="submit1 eventSave" />
                                    <input type="submit" value="Cancel" data-target="2" class="submit2 eventCancel" />
                                </li>
                            </ul>
                        </div>
                    </section>
                    <section id="watcherDetailEdit2">
                        <div class="watcher_form gap_top">
                            <ul>
                                <li>
                                    <strong>veggie produce info</strong>
                                </li>
                                <li>
                                    email to contact local agent, get Johnson to help sourcing 3 suppliers min.
                                </li>
                                <li>
                                    <strong>Watcher Alert </strong>: 2012-4-4, 9:20<a><img src="images/alarm_bg.png" alt="alarm" class="right" height="21" /></a>
                                </li>
                            </ul>
                        </div>
    
                    </section>
                </section>
                <div class="watcher_form watcher_tag watch_bor">
                    <ul>
                        <li>
                            <section class="tag_l">
                                <strong>Tags:</strong><a href="#">biz</a> | <a href="#">agriculture</a> | <a href="#">first-contact</a> | <a href="#">england</a>
                            </section>
                        </li>
                        <li class="none">
                            <input type="submit" value="Edit" data-target="2" class="submit1 eventEdit" />
                        </li>
                    </ul>
                </div>
            </div>
        </form>
</script>