    <nav class="breadcrumb clearfix">
        <ul>
            <li>You are here:</li>
            <li><a href="#"><strong>Home</strong></a> &gt;</li>
        </ul>
    </nav>
      <article class="main div_shadow">
      <div class="sort_map clearfix">
        <div class="sortby"><span><strong>Sort by :</strong></span>
          <nav>
            <ul>
              <li><a href="#">New</a></li>
              <li>|</li>
              <li class="current"><a href="#">Hot</a></li>
              <li>|</li>
              <li><a href="#">Ending Soon</a></li>
            </ul>
          </nav>
        </div>
        <nav class="location_div">
          <ul>
            <li>
              <input type="checkbox" id="match-interest" />
              <label for="match-interest">Match Interest</label></li>
            <li>
              
              <label for="match_location_check" id="match-location">
              <input type="checkbox" id="match_location_check"  name="match_location_check"  />Match Location</label></li>
            <li><a href="#" class="showMap"><strong>Show Map</strong></a></li>
            <li><a href="#"><strong>Refresh</strong></a></li>
          </ul>
        </nav>
      
      </div>
      <article class="map_location clearfix">
         
              <h3>within 19 km of Tai Lam, Hong Kong</h3>
              <div class="map_distance">
                <div class="mapgap"></div>
                <img src="images/map_icon.png" alt=" " class="loc_change" /> </div>
              <div class="loc_right">
                <input type="text" value="Enter a location" />
                <img src="images/location_icon.png" alt=" " class="l_icon" />
                <select>
                  <option>Saved location</option>
                </select>
                <a href="#savelocation" class="leanModal save"><img src="images/save.gif" alt=" " /></a> 
                <a href="#locations-management" class="leanModal setting"><img src="images/setting.gif" alt=" " /></a> </div>
            </article>
      <section class="Location" id="mapWrapper">
        
        <article> <img src="images/map2.gif" alt=" "> </article>
      </section>
      <section class="post" id="more_updates">
        <article class="post_content clearfix">
            <header>
              <div class="watched">
                <div class="w1"><a class="watcher_icon"><img src="images/watched_icon.png" alt=" " /></a><span class="w_con">Watched: 1</span></div>
                <div class="w2">256</div>
                <div class="positionable asaid_popup" id="watcher_able1" style="display:none;"> 
                <div class="popup_bor watcher_gap">
                <div class="asaid_popup_main">                
                    <a title="Close" class="right_watcher_close" href="#">X</a>
                    <?php include("watcher_detail.php");?>
                   </div>
                </div>
              </div>
              </div>
              <a href="#" class="remain_time r_day"><span>17 days</span></a>
              <h3 class="head3">What we love about Andy Griffith...</h3>
            </header>
            
            <div class="post_left"><img src="images/p1.jpg" alt=" " /></div>
            <div class="post_right">
              <header class="tag_top taggap clearfix">
                <ul>
                  <li><a href="#"><strong>Music &amp; Dance</strong></a></li>
                  <li>|</li>
                  <li>start: Dec 23, 2012</li>
                  <li>|</li>
                  <li>place:<a href="#">Grand City Hall</a></li>
                </ul>
              </header>
              <p>Music is the soul of the cosmos. It is found everywhere from the rustling of the trees, to the playful streams to the pitter-patter of the raindrops. Indian music in particular, is one of the oldest and finest forms of human passions like agony, ecstasy, sorrow, hope, desire etc. Indian music has strong connections.</p>
              <footer class="tag_bottom">
                <div class="tag_l left"><strong>Tags:</strong><a href="#">Music</a>|<a href="#">Dance</a></div>
                <div class="tag_r right"><a href="#">by Mac Slocum</a>|<a href="#">16 days ago</a></div>
              </footer>
            </div>
          </article>
          <article class="post_content clearfix">
            <header>
              <div class="watched">
                <div class="w1"><a href="#"><img src="images/watched_icon.png" alt=" " /></a><span class="w_con">Watched: 5</span></div>
                <div class="w2">318</div>
              </div>
              <a href="#" class="remain_time soon"><span>Soon</span></a>
              <h3 class="head3">Cycling: Greipel wins fourth stage</h3>
            </header>
            <div class="post_left"><img src="images/p2.jpg" alt=" " /></div>
            <div class="post_right">
              <header class="tag_top taggap clearfix">
                <ul>
                  <li><a href="#"><strong>Sports &amp; Outdoors</strong></a></li>
                  <li>|</li>
                  <li>start: Dec 23, 2012</li>
                  <li>|</li>
                  <li>place:<a href="#">Grand City Hall</a></li>
                </ul>
              </header>
              <p>Music is the soul of the cosmos. It is found everywhere from the rustling of the trees, to the playful streams to the pitter-patter of the raindrops. Indian music in particular, is one of the oldest and finest forms of human passions like agony, ecstasy, sorrow, hope, desire etc. Indian music has strong connections.</p>
              <footer class="tag_bottom">
                <div class="tag_l left"><strong>Tags:</strong><a href="#">Music</a>|<a href="#">Dance</a></div>
                <div class="tag_r right"><a href="#">by Mac Slocum</a>|<a href="#">13 days ago</a></div>
              </footer>
            </div>
          </article>
          <article class="post_content clearfix">
            <header>
              <div class="watched">
                <div class="w1"><a href="#"><img src="images/watched_icon.png" alt=" " /></a><span class="w_con">Watched: 3</span></div>
                <div class="w2">234</div>
              </div>
              <a href="#" class="remain_time expired"><span>Expired</span></a>
              <h3 class="head3">ECB expected to cut rates to new....</h3>
            </header>
            <div class="post_left"><img src="images/p3.jpg" alt=" " /></div>
            <div class="post_right">
              <header class="tag_top taggap clearfix">
                <ul>
                  <li><a href="#"><strong>Shopping &amp; Business</strong></a></li>
                  <li>|</li>
                  <li>start: Dec 23, 2012</li>
                  <li>|</li>
                  <li>place:<a href="#">Grand City Hall</a></li>
                </ul>
              </header>
              <p>Music is the soul of the cosmos. It is found everywhere from the rustling of the trees, to the playful streams to the pitter-patter of the raindrops. Indian music in particular, is one of the oldest and finest forms of human passions like agony, ecstasy, sorrow, hope, desire etc. Indian music has strong connections.</p>
              <footer class="tag_bottom">
                <div class="tag_l left"><strong>Tags:</strong><a href="#">Music</a>|<a href="#">Dance</a></div>
                <div class="tag_r right"><a href="#">by Mac Slocum</a>|<a href="#">10 days ago</a></div>
              </footer>
            </div>
          </article>
                <div class="more" id="morebutton" >
                    <a class="more" title="more" href="javascript:void(0);" > More &gt;  </a> 
                </div>
      </section>
      
        </article>
      </section>
      
    <div id="savelocation" class="popup_window" style="width:450px;">
      <?php echo $this->partial('partials/popup/savelocation.phtml'); ?>
    </div>
    <div id="locations-management" class="popup_window" style="width:500px;">
      <?php echo $this->partial('partials/popup/locations_management.phtml'); ?>
    </div>
    <div id="simple_personal_event" class="popup_window" style="width:480px;">
      <?php echo $this->partial('partials/popup/simple_personal_event.phtml'); ?>
    </div>
    <div id="remove" class="popup_window" style="width:450px;">
      <?php echo $this->partial('partials/popup/confirmation_box.phtml'); ?>
    </div>
    <div id="morebox" class="popup_window" style="width:450px;">
      <?php echo $this->partial('partials/popup/more.phtml'); ?>
    </div>
</html>