<script type="text/javascript">
    jQuery(function($){
        $('body #tag_events').on("click",'.load_more_feeds',function() {
            var para = {
                tag_id: <?php echo $this->tag_id?>,
                last_id: $('.feeds article:last').data("id")
            };
            refreshFeed('tag_events', true, para);
            return false;
        });
    })
</script>
<?php echo $this -> partial('js/page/index_events.phtml'); ?>