<head>
<!-- Force latest IE rendering engine or ChromeFrame if installed -->
<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap styles -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
<!-- Generic page styles 
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/upload/style.css')?>">-->
<!-- blueimp Gallery styles 
<link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">-->
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/upload/jquery.fileupload.css')?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('css/upload/jquery.fileupload-ui.css')?>">
<style>
.save_status{
  float: right;
  height:18px;
  color: red;
}
.save_status .saving, .save_status .saved{
  display: none;
}
.img_position{
  width: 60px;
}
.img_position form input{
  width:40px;
  text-align: center
}
</style>
<!-- CSS adjustments for browsers with JavaScript disabled -->
<noscript><link rel="stylesheet" href="<?php echo $this->baseUrl('css/upload/jquery.fileupload-noscript.css')?>"></noscript>
<noscript><link rel="stylesheet" href="<?php echo $this->baseUrl('css/upload/jquery.fileupload-ui-noscript.css')?>"></noscript>
</head>
<body>
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" action="<?php /*//jquery-file-upload.appspot.com/*/?><?php echo $this->baseUrl('event/upload/img_handle'); ?>" method="POST" enctype="multipart/form-data">
        <!-- Redirect browsers with JavaScript disabled to the origin page -->
        <noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="fileupload-buttonbar">
            <div class="col">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="files[]" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
                <div class="save_status">
                  <span class="saving"><?php echo $this->translate('Saving...')?></span>
                  <span class="saved"><?php echo $this->translate('Saved')?></span>
                </div>
                <!-- The global file processing state -->
                <span class="fileupload-process"></span>
            </div>
            <!-- The global progress state -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
    </form>
<!-- The blueimp Gallery widget 
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>-->
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td style="width:190px">
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <?php /*<td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>*/?>
        <td>
            <?php /*<span class="size">{%=o.formatFileSize(file.size)%}</span>
      <input type="text" data-filename="{%=file.name%}" id="img_caption_{%=file.name%}" value="" class="img_caption" placeholder="Caption"/>*/?>
        <div data-attribute="{%=file.name%}" class="img_caption" style="" data-placeholder="Caption...">{%=file.caption%}</div>
        </td>
        <?php /*
        <td>
            <p class="name"><label><input class="is_main_pic" type="radio" name="is_main_pic" value="{%=file.name%}" /> Set as main picture</label></p>
        </td>*/ ?>
        <td>
          <div data-attribute="{%=file.name%}" class="img_position" style="" data-placeholder="Position...">{%=file.position%}</div>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<?php /* avoid too new because of editinplace plugin about $.browser function
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.js"></script>*/?>
<script src="<?php echo $this->baseUrl('js/jquery-1.8.3.min.js'); ?>"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="<?php echo $this->baseUrl('js/upload/vendor/jquery.ui.widget.js'); ?>"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="http://blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script> 
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="http://blueimp.github.io/JavaScript-Load-Image/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="http://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<!-- blueimp Gallery script 
<script src="<?php echo $this->baseUrl('js/upload/jquery.blueimp-gallery.min.js'); ?>"></script>-->
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="<?php echo $this->baseUrl('js/upload/jquery.iframe-transport.js'); ?>"></script>
<!-- The basic File Upload plugin -->
<script src="<?php echo $this->baseUrl('js/upload/jquery.fileupload.js'); ?>"></script>
<!-- The File Upload processing plugin -->
<script src="<?php echo $this->baseUrl('js/upload/jquery.fileupload-process.js'); ?>"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="<?php echo $this->baseUrl('js/upload/jquery.fileupload-image.js'); ?>"></script>
<!-- The File Upload audio preview plugin -->
<script src="<?php echo $this->baseUrl('js/upload/jquery.fileupload-audio.js'); ?>"></script>
<!-- The File Upload video preview plugin -->
<script src="<?php echo $this->baseUrl('js/upload/jquery.fileupload-video.js'); ?>"></script>
<!-- The File Upload validation plugin -->
<script src="<?php echo $this->baseUrl('js/upload/jquery.fileupload-validate.js'); ?>"></script>
<!-- The File Upload user interface plugin -->
<script src="<?php echo $this->baseUrl('js/upload/jquery.fileupload-ui.js'); ?>"></script>

<script src="<?php echo $this->baseUrl('js/jinplace-1.0.0.min.js'); ?>"></script>
<?php /*<!-- The main application script --> 
<script src="<?php echo $this->baseUrl('js/upload/main.js'); ?>"></script>*/?>
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE 8 and IE 9 -->
<!--[if (gte IE 8)&(lt IE 10)]>
<script src="js/cors/jquery.xdr-transport.js"></script>
<![endif]-->
<script type="text/javascript">
jQuery(function($) {
  'use strict';
  // Initialize the jQuery File Upload widget:
  $('#fileupload').fileupload({
      // Uncomment the following to send cross-domain cookies:
      //xhrFields: {withCredentials: true},
      url: 'img_handle',
      formData: {event_id: <?php echo $this->event_id?>},
      autoUpload: true,
      acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i
  });

  // Enable iframe cross-domain access via redirect option:
  $('#fileupload').fileupload(
      'option',
      'redirect',
      window.location.href.replace(
          /\/[^\/]*$/,
          '/cors/result.html?%s'
      )
  ).bind('fileuploadcompleted', function (e, data) {
    
        console.log('done!!');
    $('.img_position').jinplace({
      submitFunction: function(opts, value) {
        if (!ns_iframe_event_image_upload.isNumber(value)) return false;
        if (ns_iframe_event_image_upload.values[opts.attribute] == value)
        return value;
        
        var data = {};
        data['position'] = value;
        data['filename'] = opts.attribute;
        if (ns_iframe_event_image_upload.updateImageInfos(data)){
          ns_iframe_event_image_upload.values[opts.attribute] = value;
          return value;
        } 
          
      }
    });
    $('.img_caption').jinplace({
      submitFunction: function(opts, value) {
        if (ns_iframe_event_image_upload.values[opts.attribute] == value)
        return value;
        
        var data = {};
        data['caption'] = value;
        data['filename'] = opts.attribute;
        if (ns_iframe_event_image_upload.updateImageInfos(data)){
          ns_iframe_event_image_upload.values[opts.attribute] = value;
          return value;
        } 
      } 
    });
  });
  
  $('#fileupload').addClass('fileupload-processing');
  $.ajax({
      // Uncomment the following to send cross-domain cookies:
      //xhrFields: {withCredentials: true},
      url: $('#fileupload').fileupload('option', 'url'),
      data: {event_id: <?php echo $this->event_id?>},
      dataType: 'json',
      context: $('#fileupload')[0],
      success: function(){
        
      }
  }).always(function () {
      $(this).removeClass('fileupload-processing');
  }).done(function (result) {
    $(this).fileupload('option', 'done')
        .call(this, $.Event('done'), {result: result});
        console.log('done!');
    $('.img_position').jinplace({
      submitFunction: function(opts, value) {
        if (!ns_iframe_event_image_upload.isNumber(value)) return false;
        if (ns_iframe_event_image_upload.values[opts.attribute] == value)
        return value;
        
        var data = {};
        data['position'] = value;
        data['filename'] = opts.attribute;
        if (ns_iframe_event_image_upload.updateImageInfos(data)){
          ns_iframe_event_image_upload.values[opts.attribute] = value;
          return value;
        } 
          
      }
    });
    $('.img_caption').jinplace({
      submitFunction: function(opts, value) {
        if (ns_iframe_event_image_upload.values[opts.attribute] == value)
        return value;
        
        var data = {};
        data['caption'] = value;
        data['filename'] = opts.attribute;
        if (ns_iframe_event_image_upload.updateImageInfos(data)){
          ns_iframe_event_image_upload.values[opts.attribute] = value;
          return value;
        } 
      } 
    });
  });
});
var ns_iframe_event_image_upload = {
  values: {},
  updateImageInfos: function(data){
    $('.reminder_save_status .saving').show();
    var flag = false;
    $.ajax({
      type: "POST",
      url: "<?php echo $this->baseUrl('ajax/image/update_infos') ?>",
      async: false,
      data: data,
      success: function(msg){
        if(msg['result']==true){
          $('.save_status .saving').hide();
          $('.save_status .saved').show().fadeOut("slow");
          flag = true;
        }
      },
      error: function(){
        alert ("<?php echo $this->translate('Connection failed. Please try again later.') ?>");
        $('.save_status .saving').hide();
        flag = false;
      },
      dataType:"json"
    });
    return flag;
  },
  isNumber: function(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }
}
</script>