      <nav class="breadcrumb clearfix">
            <ul>
                <li>You are here:</li>
                <li><a href="#"><strong>Home</strong></a> &gt;</li>
                <li><strong>Forgot Password</strong></li>
            </ul>
        </nav>
        <article class="main shadow">
                <section class="main_inner">
                <h1>Forgot Password</h1>

<div class="pop_form signup_form">
<div class="p_field"><label>Email Id:</label><input type="text" /></div>
<div class="div_center"><input type="submit" value="Submit" /></div>

</div>


                </section>
        </article>
