<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<article class="main shadow">
  <section class="main_inner">
    <h1>Forgot Password</h1>

    <div class="pop_form forgot_password_form">
      <form method="post" action="<?php echo $this->baseUrl('auth/forgot_password')?>" id="forgot_password">
        <div class="p_field">
          <input class="forgot_password_email" name="forgot_password_email" type="text" placeholder="Email" />
        </div>
        <div class="div_center">
          <input type="submit" value="Request Password" />
        </div>
      </form>
    </div>
  </section>
</article>

<?php echo $this -> partial('js/auth.phtml'); ?>