<?php echo $this->partial('breadcrumbs.phtml'); ?>
<article class="main shadow">
    <section class="mainevent">
        <h1>Login</h1>
        <div class="login_form">
            <div class="col_left">
                <form method="post" action="<?php echo $this->baseUrl('auth/login')?>">
                <div class="p_field">
                    <input class="required username"  type="text" name="username" value="" />
                </div>
                <div class="p_field">
                    <input type="password" class="required password" type="text" name="password" value="" />
                </div>
                
                <div>
                    <input class="submit_btn" type="submit" value="Login"  />
                </div>
                </form>
                <div class="other_options">
                    <a href="<?php echo $this->baseUrl('auth/signup'); ?>">Don't have an account?</a> <br />
                    <a href="<?php echo $this->baseUrl('auth/forgot_password'); ?>">Forgot your password?</a>
                </div>
            </div>
            <div class="or">
                <p>Or</p>
            </div>
            <div class="col_right">
                    <a href="<?php echo $this->googleAuthUrl ?>" class="button google"></a><br />
                    <a href="<?php echo $this->facebookAuthUrl ?>" class="button facebook"></a><br />
                    <a href="<?php echo $this->twitterAuthUrl ?>" class="button twitter"></a>
            </div>
            <div class="clr"></div>
        </div>
    </section>
</article>
