<?php echo $this->partial('breadcrumbs.phtml'); ?>
<article class="main shadow">
    <section class="main_inner">
        <h1>Login</h1>
        <div class="login_form">
            <div class="col_left">
                <form method="post" action="<?php echo $this->baseUrl('auth/login')?>" id="user_login">
                <div class="p_field">
                    <input class="required username" type="text" id="username" name="username" placeholder="Username" value="" />
                </div>
                <div class="p_field">
                    <input type="password" id="password" class="required password" placeholder="Password" type="password" name="password" value="" />
                </div>
                
                <div>
                    <input class="submit_btn" type="submit" value="Login"  />
                </div>
                </form>
                <div class="other_options">
                    <a href="<?php echo $this->baseUrl('auth/signup'); ?>">Don't have an account?</a> <br />
                    <a href="<?php echo $this->baseUrl('auth/forgot_password'); ?>">Forgot your password?</a>
                </div>
            </div>
            <div class="or">
                <p>Or</p>
            </div>
            <div class="col_right">
                    <a href="<?php echo $this->auth_link->google ?>" class="button google"></a><br />
                    <a href="<?php echo $this->auth_link->facebook ?>" class="button facebook"></a>
            </div>
            <div class="clr"></div>
        </div>
    </section>
</article>
<?php echo $this -> partial('js/auth.phtml'); ?>
