<?php echo $this->partial('breadcrumbs.phtml'); ?>
<article class="main shadow">
  <section class="main_inner">
    <h1>Reset Password</h1>
    <div class="pop_form signup_form">
      <div class="section">
        <div class="content">
          <form method="post" action="<?php echo $this->baseUrl('auth/reset_password')?>" id="reset_password">
              <input name="email" placeholder="Email" value="<?php echo $this->email ?>" type="hidden" required="required"/>
            
            <div class="p_field">
              <input id="password" name="password" placeholder="New Password" type="password" required="required" />
            </div>
            
            <div class="p_field">
              <input id="confirm_password" name="confirm_password" placeholder="Confirm Password" type="password" required="required" />
            </div>
            <div class="btnSet" style="padding-bottom:10px;">
              <input type="submit" value="<?php echo $this->translate('Submit')?>" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</article>
<script></script>
<?php echo $this -> partial('js/auth.phtml'); ?>
