<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<article class="main shadow">
  <section class="main_inner">
    <h1>Signup to confirm...</h1>
    <div class="pop_form signup_form">

<?php echo $this->translate("Congratulations! You have finished the signup process. The confirmation email was sent to %1\$s. Please confirm your account by clicking the activation link in email within the next 24 hours. In the meantime you may walk around the site and experience a bit :)."
    ,'<strong>'.$this->to_confirm_email.'</strong>'); ?>
    </div>
  </section>
</article>