<?php echo $this -> partial('breadcrumbs.phtml'); 
?>

<article class="main shadow">
    <section class="main_inner">
        <h1>Signup</h1>
        <div class="signup_form">
          <form method="post" action="<?php echo $this->baseUrl('auth/signup')?>" id="user_signup">
          <?php if ($this->has_provider){ ?>
            <p class="red">You are currently signing up associated with <?php echo $this->provider_name ?> Account.</p>
            <input type="hidden" name="provider_name" value="<?php echo $this->provider_name; ?>" />
          <?php } ?>
            <div class="p_field">
                <label>Name</label>
                <input type="text" name="display_name" value="<?php echo $this->name ?>"/>
            </div>
            <div class="p_field">
                <label for="gender" >Gender</label><br />
                <select name="gender">
                    <option></option>
                    <option <?php if ($this->gender=='M'){ ?>selected="selected"<?php } ?> value="M">Male</option>
                    <option <?php if ($this->gender=='F'){ ?>selected="selected"<?php } ?> value="F">Female</option>
                </select>
            </div>
            <div class="p_field">
                <label>* login username</label>
                <input type="text" name="username" value="<?php echo $this->username ?>"/>
            </div>
            <div class="p_field">
                <label>* Email</label>
                <input type="text" name="email" value="<?php echo $this->email ?>" <?php /*if ($this->has_provider && $this->is_email_verified){ ?> readonly="readonly"<?php }*/ ?>/>
                <?php /*if ($this->has_provider && $this->is_email_verified){ ?>
                <p class="red">If you do not want to receive updates from this verfied email address associated with <?php echo ucfirst($this->provider_name); ?>. You could choose to <a href="<?php echo $this->baseUrl('auth/signup?no_provider=1'); ?>">sign up with another email address</a>. You may then be required to confirm your new email address.</p>
                <?php }*/ ?>
            </div>
            <div class="p_field">
                <label>* New Password</label>
                <input type="password" id="password" name="password" value=""/>
            </div>
            <div class="p_field">
                <label>* Confirm Password</label>
                <input type="password" name="confirm_password" value=""/>
            </div>
            <div>
            <p><?php echo $this->translate("By clicking 'Sign Up', you confirm that you agree to our privacy policy and terms and conditions.")?></p>
                <input class="submit_btn" type="submit" value="<?php echo $this->translate("Sign Up");?>" />
            </div>
            <div class="clr"></div>
          </form>
          <p class="auth_question"><?php echo $this->translate('Already registered? '); ?><a class="ajax_load" href="<?php echo $this->baseUrl('auth/login'); ?>"><?php echo $this->translate('click here'); ?></a>
        </div>

    </section>
</article>
<?php echo $this -> partial('js/auth.phtml'); ?>
