<?php echo $this -> partial('breadcrumbs.phtml'); ?>

<article class="main shadow">
    <section class="main_inner">
        <h1>Signup</h1>
        <div class="signup_form">
          <form method="post" action="<?php echo $this->baseUrl('auth/signup')?>" id="user_signup">
            <div class="p_field">
                <label>Name</label>
                <input type="text" name="display_name"/>
            </div>
            <div class="p_field">
                <label for="gender" >Gender</label><br />
                <select name="gender">
                    <option></option>
                    <option value="M">Male</option>
                    <option value="F">Female</option>
                </select>
            </div>
            <div class="p_field">
                <label>* login username</label>
                <input type="text" name="username"/>
            </div>
            <div class="p_field">
                <label>* Email</label>
                <input type="text" name="email"/>
            </div>
            <div class="p_field">
                <label>* New Password</label>
                <input type="password" id="password" name="password"/>
            </div>
            <div class="p_field">
                <label>* Confirm Password</label>
                <input type="password" name="confirm_password"/>
            </div>
            <div>
            <p><?php echo $this->translate("By clicking 'Sign Up', you confirm that you agree to our privacy policy and terms and conditions.")?></p>
                <input class="submit_btn" type="submit" value="<?php echo $this->translate("Sign Up");?>" />
            </div>
            <div class="clr"></div>
          </form>
          <p class="auth_question"><?php echo $this->translate('Already registered? '); ?><a class="ajax_load" href="<?php echo $this->baseUrl('auth/login'); ?>"><?php echo $this->translate('click here'); ?></a>
        </div>

    </section>
</article>
<?php echo $this -> partial('js/auth.phtml'); ?>
