<script id="feed_index_item" type="text/x-jquery-tmpl">
    <article data-id="${id}" class="post_content clearfix {{if is_like}}{{if is_like==1 }}bookmarked{{/if}}{{/if}}">
        <header>
            <div class="watched">
                <div class="w1">
                    <?php /*<img class="watcher_icon" src="<?php echo $this->baseUrl('images/watched_icon.png');?>" alt="" />*/ ?>
                    <div data-id="${id}" class="star">
                        <div class="star_inner"></div>
                    </div>
                    <span class="w_con">Watched: ${like_count}</span>
                </div>
                <?php // temporarily hide the score as we do not have to show it to users and to avoid confusion with like count
                /*<div class="w2">
                    ${score}
                </div>*/ ?>
            </div>
            <a class="head" href="<?php echo $this->baseUrl('event');?>/${slug_name}">${name}</a>
        </header>
        <div class="post_left">
            <a href="<?php echo $this->baseUrl('event');?>/${slug_name}">
                <img class="lazy" width="135" alt="${$item.getMainPicTitle()}" src="${$item.getMainPicURL()}" />
            </a>
        </div>
        <div class="post_right">
            <header class="tag_top taggap clearfix">
                <ul>
                    {{if $item.hasMainCat() }}
                    <li>
                        <a target="blank" href="${$item.getMainCatURL()}"><strong>${$item.getMainCatName()}</strong></a>
                    </li>
                    {{/if}}
                    {{if begin_datetime}}
                        {{if $item.hasMainCat() }}
                        <li>
                            |
                        </li>
                        {{/if}}
                    <li>
                        start: ${$item.formatMysqlDate($data.begin_datetime)}
                    </li>
                    {{/if}}
                    {{if place}}
                        {{if $item.hasMainCat() || begin_datetime}}
                    <li>
                        |
                    </li>
                        {{/if}}
                    <li>
                        place: 
                        {{if degree}}
                            <a href="#" title="${degree}&deg;"><img class="direction-arrow ${degree}" height="10" src="<?php echo $this->baseUrl('images/direction-arrow.jpg');?>" /></a>
                        {{/if}}
                        {{if place_lat && place_lng}}<a class="place" data-lat="${place_lat}" data-lng="${place_lng}" title="${place}" href="#">{{else}}<span class="place">{{/if}}${place}{{if place_lat && place_lng}}</a>{{else}}</span>{{/if}}
                    </li>
                    {{/if}}
                </ul>
            </header>
            {{if place_lat && place_lng}}<div class="gmap" data-lat="${place_lat}" data-lng="${place_lng}" ></div>{{/if}}
            <div class="content">
                <!--{{html $item.urldecode($data.teaser)}}-->
                ${teaser}
            </div>
            <footer class="tag_bottom">
                <div class="tag_l left">
                    <strong>Tags:</strong>{{html $item.tagHTML()}}
                </div>
                <div class="tag_r right">
                    by <a target="_blank" href="<?php echo $this->baseUrl('user');?>/${submitter_slug_name}">${submitter_name}</a>| <abbr class="timeago" title="${create_time}">
                </div>
            </footer>
        </div>
    </article>
</script>