<script type="text/javascript">
    function initIndexFeed(){ 
        updateVariablesFromUrlParams();
        updateFeedInputsFromVariables();
        
        <?php if (Zend_Registry::get('config_ini')->server->online==1){ ?>
            initMap();
        <?php } ?>
        
        $( "#radius_slider" ).slider({
            range: "min",
            value:feed_para['radius'],
            step: 0.01,
            min: minDistance,
            max: maxDistance,
            slide: function( event, ui ) {
                $( ".radius_amt span#filter_radius" ).text( ui.value );
                
            },
            change: function( event, ui ) {
                $( ".radius_amt span#filter_radius" ).text( ui.value );
                if ($("#map").is(":visible")){
                    distanceWidget.set('distance',ui.value);
                    radiusWidget.bindTo('center', distanceWidget, 'position');
                    map.fitBounds(radiusWidget.get('bounds'));
                }
              feed_para['radius'] = ui.value;
              ns_feed.updateUrlParam('radius', ui.value);
            }
        });
    }

    var map_markers_data = [];
    jQuery(function($){
        <?php if (Zend_Registry::get('config_ini')->server->online==1){ ?>
            if (typeof index_feed != 'undefined'){ 
              map_markers_data = index_feeds.data;
              refreshMarkers();
            }
        <?php } ?>
        //when user clicks load more
        $('body#index').on("click",'.load_more_feeds',function() {
            feed_para.last_id = $('.feeds > article:last').data("id");
            ns_feed.refresh('index', true, [], false);
            return false;
        });
    })
</script>
<?php echo $this->partial('js/template/feeds/index_events_item.phtml') ?>