<script type="text/javascript">
var ns_feeds_index_events = {
  autoLoadMoreIndex:0,
  autoLoadMoreLimit:2,
  initIndexFeed: function(){ 
    ns_feeds.updateFeedOptionsFromUrlParams();
    
    <?php if (Zend_Registry::get('config_ini')->server->online==1){ ?>
        ns_filter_map.initMap();
    <?php } ?>
  },
  loadMoreFeed: function(){
    ns_feeds.feed_para.page = this.autoLoadMoreIndex+2; // +1 is the current page
    ns_feeds.feed_para.last_id = $('.feeds > article:last').data("id");
    ns_feeds.refresh('index', true, []);
    return false;
  }
}
jQuery(function($){
  <?php if (Zend_Registry::get('config_ini')->server->online==1){ ?>
      if (typeof index_feed != 'undefined'){ 
        ns_feeds.map_markers_data = index_feeds.data;
        ns_filter_map.refreshMarkers();
      }
  <?php } ?>
  
  $('.load_more_feeds').appear();
  //when user clicks load more
  $('body#search')
    .on("click",'.load_more_feeds',function() {
      ns_feeds_index_events.loadMoreFeed();
    })
    .on('appear', '.load_more_feeds', function(e, $affected) {
      
      if(ns_feeds_index_events.autoLoadMoreIndex <= ns_feeds_index_events.autoLoadMoreLimit)
        ns_feeds_index_events.loadMoreFeed();
        
      ns_feeds_index_events.autoLoadMoreIndex++;
    })
  
})

</script>
<?php echo $this->partial('js/template/feeds/index_events_item.phtml') ?>