<script type="text/javascript">
var ns_feeds_index_events = {
  initIndexFeed: function(){ 
    ns_common_foot.updateVariablesFromUrlParams();
    ns_feeds.updateFeedInputsFromVariables();
    
    <?php if (Zend_Registry::get('config_ini')->server->online==1){ ?>
        ns_filter_map.initMap();
    <?php } ?>
    /*
    $( "#radius_slider" ).slider({
        range: "min",
        value:ns_feeds.feed_para['radius'],
        step: 0.01,
        min: minDistance,
        max: maxDistance,
        slide: function( event, ui ) {
            $( ".radius_amt span#filter_radius" ).text( ui.value );
            
        },
        change: function( event, ui ) {
            $( ".radius_amt span#filter_radius" ).text( ui.value );
            if ($("#map").is(":visible")){
                distanceWidget.set('distance',ui.value);
                radiusWidget.bindTo('center', distanceWidget, 'position');
                map.fitBounds(radiusWidget.get('bounds'));
            }
          ns_feeds.feed_para['radius'] = ui.value;
          ns_feeds.updateUrlParam('radius', ui.value);
        }
    });*/
  }
}
jQuery(function($){
  <?php if (Zend_Registry::get('config_ini')->server->online==1){ ?>
      if (typeof index_feed != 'undefined'){ 
        ns_feeds.map_markers_data = index_feeds.data;
        ns_filter_map.refreshMarkers();
      }
  <?php } ?>
  //when user clicks load more
  $('body#index').on("click",'.load_more_feeds',function() {
      ns_feeds.feed_para.last_id = $('.feeds > article:last').data("id");
      ns_feeds.refresh('index', true, []);
      return false;
  });
})
</script>
<?php echo $this->partial('js/template/feeds/index_events_item.phtml') ?>