<script type="text/javascript">
    jQuery(function($){
        //when tree clicks load more
        $('body #tree_feeds').on("click",'.load_more_feeds',function() {
            var para = {
                <?php if (isset(Common::getSession()->redirect_params['cat1'])){ ?>cat1: '<?php echo Common::getSession()->redirect_params['cat1'] ?>',<?php } 
                 if (isset(Common::getSession()->redirect_params['cat2'])){ ?>cat2: '<?php echo Common::getSession()->redirect_params['cat2'] ?>',<?php } 
                 if (isset(Common::getSession()->redirect_params['cat3'])){ ?>cat3: '<?php echo Common::getSession()->redirect_params['cat3'] ?>',<?php } ?>
                 level: '<?php echo Common::getSession()->redirect_params['level'] ?>',
                 last_id: $('.feeds article:last').data("id")
            };
            refreshFeed('tree_feeds', true, para);
            return false;
        });
    })
</script>
<?php //echo $this->partial('js/template/feeds/_tree_item.phtml') ?>
<?php echo $this -> partial('js/feeds/index_events.phtml'); ?>