<?php echo $this->partial('js/template/feed/index_item.phtml') // for sub feed item ?>
<script type="text/javascript">
</script>        
<script id="feed_user_item" type="text/x-jquery-tmpl">
    <div class="log clearfix" data-id="${id}" style="border-bottom:1px solid grey;padding:10px 0;">
        <div class="content">
            <a href="<?php echo $this->baseUrl('user/')?>${username}">${user_name}</a>
            ${$item.getPastTense()}
            <a href="<?php echo $this->baseUrl('/')?>${$item.getObjectType()}/${object_slug_name}">${object_name}</a>
            <abbr class="timeago" title="${create_time}" style="float:right;">
        </div>
        {{if is_detailed_feed}}
            {{html $item.getFeedItem()}}
        {{/if}}
    </div>
</script>