<script type="text/javascript">
var ns_sidebar_bookmark_poup = {
  toggleBookmark: function(bookmark_star_elem){
      var parent_li = bookmark_star_elem.parents('li');
      var this_popup = parent_li.find('.sidebar_bookmark_popup, .arrow');
      if (parent_li.hasClass("bookmarked")){
        bookmark_star_elem.removeClass('gold');
        parent_li.removeClass("bookmarked");
        this_popup.hide();
      } else {
        bookmark_star_elem.addClass('gold');
        parent_li.addClass("bookmarked");
        ns_sidebar_bookmark_poup.togglePopup(parent_li);
      }
  },
  togglePopup: function(list_item){
    var this_popup = list_item.find('.sidebar_bookmark_popup, .arrow');
    if ($('.sidebar_bookmark_popup, .arrow').not(this_popup).is(':visible')){
      $('.sidebar_bookmark_popup, .arrow').not(this_popup).hide();
    }
    if (this_popup.is(':visible')){
      this_popup.hide();
    }else{
      this_popup.show();
      $('.sidebar_bookmark_popup_inner .teaser').dotdotdot({
          wrap : 'letter',
          height: 50
     });
    ns_sidebar_bookmark_poup.adjustSidebarPopupPosition(list_item.find('.sidebar_bookmark_popup'));
    }
  },
  adjustSidebarPopupPosition: function(elem){
    //init
    elem.css('top', 0);
    
    var parent = elem.parents('li');
    
    var offset = elem.offset();
    var parent_offset = parent.offset();
  
    if (offset.top + elem.height() > $(window).height() + $(window).scrollTop()){
  
      console.log('exceeded below!');
  
      if ($(window).height() < elem.height()){
        console.log('not enough window size!');
        var top_to_parent_height =  parent_offset.top - $(window).scrollTop();
        elem.css('top', (10 - top_to_parent_height) +'px');
  
      }else{
        console.log('enough window size!');
        var parent_to_bottom_height = $(window).height() + $(window).scrollTop() - parent_offset.top - parent.height();
        var popuptop_to_parent_height =  Math.abs(parseInt(elem.css('top')));
        var remaining_height = elem.height() - parent.height() - parent_to_bottom_height - popuptop_to_parent_height + 10;
        var sum = parseInt(elem.css('top')) - remaining_height;
        elem.css('top', sum +'px');
      }
      
      if (parent_to_bottom_height <= 10){
        parent.find('.arrow').hide();
      }
  
    }else if (offset.top <= $(window).scrollTop()+10){
      console.log('exceeded above!');
      
      var top_to_parent_height =  parent_offset.top - $(window).scrollTop();
      
      elem.css('top', (10 - top_to_parent_height) +'px');
      
      if (top_to_parent_height <= 10){
        parent.find('.arrow').hide();
      }
    }else{
      console.log('inside');
    }
  }
};
jQuery(function($){
  $('body').on('click', '#highlight_tab li, #reminder_tab li' , function(event) {
    if ($(event.target).closest('a').length) {
      //console.log('is link!');
      //return false;
    }else{
      ns_sidebar_bookmark_poup.togglePopup($(this));
    }
  })
  .on('click',".sidebar_bookmark_popup",function(e){
    e.stopPropagation();
  })
  .on('click',".star_inner",function(e){
    e.stopPropagation();
    ns_sidebar_bookmark_poup.toggleBookmark($(this));
  })
  .on('click', '.sidebar_bookmark_popup_set_reminder',function(e){
    e.stopPropagation();
    $(this).parents('.sidebar_bookmark_popup').find('.white').show();
    $(this).hide();
    $('.sidebar_bookmark_popup_reminder_title').watermark("<?php echo $this->translate('Reminder Title') ?>");
    $('.sidebar_bookmark_popup_reminder_detail').watermark("<?php echo $this->translate('Reminder Detail') ?>");
    return false;
  })
 .on('click', function(event) {
      if (!$(event.target).closest('.sidebar_bookmark_popup, .arrow, #highlight_tab li, #reminder_tab li').length) {
      $(".sidebar_bookmark_popup, .arrow").hide();
      };
  });
<?php /* //pending hover effect...
  var over_timer;
  var out_timer;
  $('#highlight_tab li.bookmarked, #reminder_tab li.bookmarked, sidebar_bookmark_popup').hover(
    function(e){
      if ($(this).find('.sidebar_bookmark_popup, .arrow').is(':visible')) return false
      var this_elem =$(this);
      if(over_timer) {
        clearTimeout(over_timer);
        over_timer = null;
      }
      console.log('start over timer')
      over_timer = setTimeout(function() {
        if (!$(e.target).closest('.sidebar_bookmark_popup').length) {
          ns_sidebar_bookmark_poup.togglePopup(this_elem);
        }
      }, 500)
    },
    function(e){
      if (! $(this).find('.sidebar_bookmark_popup, .arrow').is(':visible')) return false
      var this_elem =$(this);
      clearTimeout(over_timer);
      if(out_timer) {
        clearTimeout(out_timer);
        out_timer = null;
      }
      console.log('start out timer')
      out_timer = setTimeout(function() {
          $('.sidebar_bookmark_popup, .arrow').hide();
      }, 500)
    }
  )*/ ?>
})  
</script>
<?php //echo $this->partial('js/template/sidebar/event_detail_popup_item.phtml') ?>