<script type="text/javascript">
var ns_sidebar_bookmark_popup = {
  target: null,
  toggleBookmark: function(id){
      var parents = $('#sidebar li.list_item[data-id="'+id+'"], article[data-id="'+id+'"]');
      var this_popup = $('.sidebar_bookmark_popup[data-id="'+id+'"]');
      var set_status = parents.hasClass("bookmarked") ? 0 : 1;
    <?php if (Zend_Auth::getInstance()->hasIdentity() && Common::getSession()->user != null) { ?>
      jQuery.ajax({
          type: "POST",
          url: "<?php echo $this->baseUrl('ajax/bookmark/trigger') ?>",
          data: "id="+id+"&set_status="+set_status,
          success: function(msg){
            if (parents.hasClass("bookmarked")){
              parents.find('.star_inner').removeClass('gold');
              parents.removeClass("bookmarked");
              this_popup.find('.white, .sidebar_bookmark_popup_set_reminder').hide();
            } else {
              parents.find('.star_inner').addClass('gold');
              parents.addClass("bookmarked");
              this_popup.find('.sidebar_bookmark_popup_set_reminder').show();
              /*if (! this_popup.is(':visible')){ 
                ns_sidebar_bookmark_popup.togglePopup(id); 
              }*/
            }
            if (ns_sidebar_bookmark_popup.target == 'feeds'){
              ns_sidebar_bookmark_popup.togglePopup(id);
            }
          },
          error: function(){
            alert ("<?php echo $this->translate('Connection failed. Please try again later.') ?>");
          },
          dataType:"json"
      });
    <? } else { ?>
          alert('Please login to add bookmark.');
    <?php } ?>
  },
  togglePopup: function(id){
    if (ns_sidebar_bookmark_popup.target==null ) ns_sidebar_bookmark_popup.target = 'sidebar';
    
    var this_popup = $('.sidebar_bookmark_popup[data-id="'+id+'"]');
    if (this_popup.length){
      if ($('.sidebar_bookmark_popup').not(this_popup).is(':visible')){
        $('.sidebar_bookmark_popup, .more').not(this_popup).hide();
      }
      if (ns_sidebar_bookmark_popup.target == 'sidebar'){
        var trigger_popup_icon = $('.trigger_popup_icon');
        var parent = $('#sidebar ul:visible li[data-id="'+id+'"]');
          if (this_popup.is(':visible')){
           this_popup.hide();
           trigger_popup_icon.hide();
          }else{
           ns_sidebar_bookmark_popup.adjustSidebarPopupPosition(id);
           this_popup.show();
           this_popup.find('.yellow').show();
           trigger_popup_icon.show();
           
           this_popup.find('.sidebar_bookmark_popup_inner .teaser').dotdotdot({
                wrap : 'letter',
                height: 60
           });
          }
         if (parent.hasClass('bookmarked')) {
          this_popup.find('.sidebar_bookmark_popup_set_reminder').show();
          this_popup.find('.white').hide();
         } else {
          this_popup.find('.sidebar_bookmark_popup_set_reminder').hide();
         }
      } else if (ns_sidebar_bookmark_popup.target == 'feeds'){
        var trigger_popup_icon = $('.trigger_popup_icon');
        var parent = $('article[data-id="'+id+'"]');
        var star = $('article[data-id="'+id+'"] .star');
        if (parent.hasClass('bookmarked')){
          if (this_popup.is(':visible')){
            this_popup.hide(); // close popup when clicking outside
            trigger_popup_icon.hide();
          } else {
            //init
            trigger_popup_icon.css('top', star.offset().top + 15);
            trigger_popup_icon.css('left',star.offset().left);
            this_popup.css('top', star.offset().top + 37);
            this_popup.css('left',star.offset().left - 270);
            this_popup.show();
            this_popup.find('.yellow, .sidebar_bookmark_popup_set_reminder').hide();
            this_popup.find('.white').show();
            ns_sidebar_bookmark_popup.showReminderFields();
            trigger_popup_icon.show();
          }
        }else{
          this_popup.hide();
        }
      }
    }
  },
  adjustSidebarPopupPosition: function(id){
    var this_popup = $('.sidebar_bookmark_popup[data-id="'+id+'"]');
    var trigger_popup_icon = $('.trigger_popup_icon');
    
    var parent = $('#sidebar ul:visible li[data-id="'+id+'"]');
    var grandparent = parent.parents('ul');
    
    console.log(parent.offset())
    //init
    trigger_popup_icon.css('top', parent.offset().top + 5);
    trigger_popup_icon.css('left',grandparent.offset().left+grandparent.outerWidth( true ));
    this_popup.css('top', parent.offset().top);
    this_popup.css('left',grandparent.offset().left+grandparent.outerWidth( true )+trigger_popup_icon.outerWidth( true ));
    
    if (parent.offset().top + this_popup.height() > $(window).height() + $(window).scrollTop()){
  
      console.log('exceeded below!');
  
      if ($(window).height() < this_popup.height()){
        console.log('not enough window size!');
        this_popup.css('top', $(window).scrollTop()+5);
      }else{
        console.log('enough window size!');
        var parent_to_bottom_height = $(window).height() + $(window).scrollTop() - parent.offset().top;
        var remaining_height = this_popup.height() - parent_to_bottom_height;
        var sum = parseInt(this_popup.css('top')) - remaining_height - 5;
        this_popup.css('top', sum +'px');
      }
  
    }else if (parent.offset().top <= $(window).scrollTop()+10){
      console.log('exceeded above!');
      
      var top_to_parent_height =  parent.offset().top - $(window).scrollTop();
      
      this_popup.css('top', parent.offset().top + (10 - top_to_parent_height) +'px');
      
    }else{
      console.log('inside');
    }
    console.log(this_popup.offset());
  },
  showReminderFields : function(){
    $('.sidebar_bookmark_popup_reminder_title').watermark("<?php echo $this->translate('Reminder Title') ?>");
    $('.sidebar_bookmark_popup_reminder_detail').watermark("<?php echo $this->translate('Reminder Detail') ?>");
  }
};
jQuery(function($){
  $('body')
  .on('click',".sidebar_bookmark_popup",function(e){
    e.stopPropagation();
  })
  .on('click',".star_inner",function(e){
    e.stopPropagation();
    if ($(e.target).closest('article.post_content').length){
      ns_sidebar_bookmark_popup.target = 'feeds';
    } else if ($(e.target).closest('#sidebar li').length){
      ns_sidebar_bookmark_popup.target = 'sidebar';
    }
    console.log(ns_sidebar_bookmark_popup.target);
    ns_sidebar_bookmark_popup.toggleBookmark($(this).data('id'));
    ns_sidebar_bookmark_tab.is_reload = true;
    <?php /*if (ns_sidebar.activeTab=='#bookmark_tab' && ! $(e.target).closest('#bookmark_tab li').length) ns_sidebar.loadTab(true);*/?>
  })
  .on('click', '.sidebar_bookmark_popup_set_reminder',function(e){
    e.stopPropagation();
    $(this).parents('.sidebar_bookmark_popup').find('.white').show();
    $(this).hide();
    ns_sidebar_bookmark_popup.showReminderFields();
    return false;
  })
<?php //pending hover effect... ?>
  var over_timer = null;
  var out_timer = null;
  var to_touch_id = null;
  var touching_id = null;
  var clicked_id = null;
  $('body')
    .on('click', '#highlight_tab li.list_item , #bookmark_tab li.list_item' , function(e) {
      e.stopPropagation();
      ns_sidebar_bookmark_popup.target = 'sidebar';
     if (clicked_id == null){
        $('#highlight_tab li, #bookmark_tab li').removeClass('clicked');
        if (! $('.sidebar_bookmark_popup[data-id="'+$(this).data('id')+'"]').is(':visible'))
          ns_sidebar_bookmark_popup.togglePopup($(this).data('id'));
        clicked_id = $(this).data('id');
        $(this).addClass('clicked');
      } else {
        ns_sidebar_bookmark_popup.togglePopup($(this).data('id'));
        $('#highlight_tab li, #bookmark_tab li').removeClass('clicked');
        if ($('.sidebar_bookmark_popup[data-id="'+$(this).data('id')+'"]').is(':visible')){
          clicked_id = $(this).data('id');
          $(this).addClass('clicked');
        }else{
          clicked_id = null;
          $(this).removeClass('clicked');
        }
      }
      console.log(clicked_id);
    })
    .on({
      mouseenter : function(e){
        $(this).data('hover',1);
      },
      mouseleave : function(e){
        $(this).data('hover',0);
      }
    }, '.sidebar_bookmark_popup, #highlight_tab li.list_item , #bookmark_tab li.list_item')
    .on({
      mouseenter : function(e){
        console.log('hover');
        if (over_timer != null){
          clearTimeout(over_timer);
          over_timer = null;
        }
        if(out_timer!=null) {
          clearTimeout(out_timer);
          out_timer = null;
        }
        if (clicked_id != null) return false;
        
        if (touching_id == null){
        // if it is the first list item to touch
          to_touch_id = $(this).data('id');
          over_timer = setTimeout(function() {
            console.log('over timeout');
            if (clicked_id != null || out_timer!=null || ns_sidebar_bookmark_popup.target == 'feeds') return false;
            ns_sidebar_bookmark_popup.target = 'sidebar';
            ns_sidebar_bookmark_popup.togglePopup(to_touch_id);
            touching_id = to_touch_id;
          }, 1500)
        }else if (touching_id !=null && $(e.target).closest('[data-id="'+touching_id+'"]').length){
          // if it is the same list item
          return false;
        } else {
          // if it is different list item
          to_touch_id = $(this).data('id');
          ns_sidebar_bookmark_popup.target = 'sidebar';
          ns_sidebar_bookmark_popup.togglePopup(to_touch_id);
          touching_id = to_touch_id;
        }
      },
      mouseleave: function(e){
        if (clicked_id != null) return false;
        out_timer = setTimeout(function() {
            console.log('out timeout');
            if (touching_id != null && $('.sidebar_bookmark_popup:visible').data('hover')!=1 && $('.sidebar_bookmark_popup').is(':visible')
              && ns_sidebar_bookmark_popup.target != 'feeds'
            ){
              console.log('this is outside popup too');
              if (clicked_id != null) return false;
              ns_sidebar_bookmark_popup.target = 'sidebar';
              ns_sidebar_bookmark_popup.togglePopup(touching_id);
              touching_id = null;
            }
        }, 500);
      }
    }, '#highlight_tab li.list_item, #bookmark_tab li.list_item, .sidebar_bookmark_popup');
})  
</script>