<script type="text/javascript">
var ns_sidebar_event_detail_popup = {
  init: function(){
    
  },
  
  render : function(data){
    if (typeof data == 'undefined') var data={};
    console.log($( "#sidebar_event_detail_popup_item" ).tmpl());
    return $( "#sidebar_event_detail_popup_item" ).tmpl();
    //return ns_sidebar_event_detail_popup.generate(data);
  },
  
  /*generate: function(data){
    if (typeof data == 'undefined') var data={};
    return $( "#sidebar_event_detail_popup_item" ).tmpl(data,
      {
      } 
    );
  },*/
  
  attachEvents: function(){
    
  }
  
};
jQuery(function($){
    $('body').on('click', '#watchlist_tab .event_icon' , function() {
        $(this).qtip(
        {
            //overwrite: false, 
            content: {
                text: '<img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." />',
                ajax: {
                    url: '<?php echo $this->baseUrl('ajax/bookmark/open_box_trigger')?>', 
                    success: function(data, status) {
                        this.set('content.text', ns_sidebar_event_detail_popup.render(data));
    ns_sidebar_event_detail_popup.attachEvents();
                    }
                },
                title: {
                    text: 'Bookmark details'
                }
            },
            position: {
                at: 'top right', 
                my: 'top left',
                target: $(this)
            },
            show: {
                 ready: true
            },
            style: {
                def:false,
                classes: 'qtip-light bookmark_box_trigger qtip-shadow'
            }
        })
    })
})  
</script>
<?php echo $this->partial('js/template/sidebar/event_detail_popup_item.phtml') ?>