<script type="text/javascript">
var ns_sidebar_highlight_tab = {
  is_fetching: false,
  has_nth_fetched: false,
  used_ids: [],
  rpp: 5,
  fetch: function(){
    if (ns_sidebar_highlight_tab.is_fetching == false){
      ns_sidebar_highlight_tab.is_fetching=true;
      $.ajax({
        type: "POST",
        url: "<?php echo $this->baseUrl('ajax/bookmark/get_highlights') ?>",
        data: {used_ids: ns_sidebar_highlight_tab.used_ids},
        success: function(msg){
          if (msg.data.length == 0) 
            ns_sidebar_highlight_tab.has_nth_fetched = true;
          else ns_sidebar_highlight_tab.has_nth_fetched = false;
          var content = ns_feed.getHTML(msg, 'sidebar_highlight_list_item', {
            getID: function() {
              if ($.inArray( this.data.id, ns_sidebar_highlight_tab.used_ids ) ==-1)
                ns_sidebar_highlight_tab.used_ids.push(this.data.id);
              $('.sidebar_bookmark_popup[data-id="'+this.data.id+'"]').remove();
              return this.data.id;
            },
            formatMysqlDate2: function() { 
              if (typeof arguments[0] == 'string') 
                return $.datepicker.formatDate('dd M', mysqlTimeStampToDate(arguments[0]));
            }
          });
          $("#highlight_tab .highlight_list .load_more").before(content);
          $("#highlight_tab .highlight_list .loading").hide();
          $(ns_sidebar.activeTab).find("li .title").dotdotdot({
              wrap : 'letter',
              height: 25
          });
          if (ns_sidebar_highlight_tab.used_ids.length >= ns_sidebar_highlight_tab.rpp){
            $('#highlight_tab .highlight_list').scrollpanel();
          }
          $("#highlight_tab .highlight_list .load_more .more").show();
          var popup_content = ns_feed.getHTML(msg, 'sidebar_popup');
          $('body').append(popup_content);
          ns_sidebar_highlight_tab.is_fetching=false;
        },
        error: function(){
          $("#highlight_tab .highlight_list").html('<li><?php echo $this->translate('Connection failed. Please try again later.') ?></li>');
        },
        dataType:"json"
      });
    }
  }
};
jQuery(function($){
  $('#highlight_tab ul').mousewheel(function(){
    $('.sidebar_bookmark_popup, .trigger_popup_icon').hide();
    var parent_div = $('.sp-viewport'); 
    var scroll_pos = parent_div.scrollTop()+parent_div.innerHeight();
    var scroll_height = parent_div[0].scrollHeight;
    if (scroll_pos +35 >= scroll_height && !ns_sidebar_highlight_tab.has_nth_fetched){
      ns_sidebar_highlight_tab.fetch();
    }
  })
  $('#highlight_tab .highlight_list .load_more').click(function(e){
    e.preventDefault();
    ns_sidebar_highlight_tab.fetch();
  })
})  
</script>