<div class="sidebar_bookmark_popup">
  <div class="sidebar_bookmark_popup_inner">
    <?php /*<h2>Event Brief</h2> */ ?>
    <div class="yellow">
      <h3>Event title 1</h3>
      <p class="info_line">
        Music | Dec 23, 2013, 9:00 | City Hall
      </p>
      <p class="teaser">
        We now have an entirely new website!
        Stay on this page if you want to purchase
        subscriptions
      </p>
    </div>
    <a class="sidebar_bookmark_popup_set_reminder" href="#" data-value="0">Set Reminder...</a>
    <div class="white">
      <form class="sidebar_bookmark_popup_form" name="sidebar_bookmark_popup_form" action="" method="post" >
        <input type="text" name="reminder_title" class="sidebar_bookmark_popup_reminder_title" value=""/>
        <textarea name="reminder_detail" class="sidebar_bookmark_popup_reminder_detail" ></textarea>
        <input type="submit" name="save" value="Save" class="sidebar_bookmark_popup_reminder_save">
      </form>
      <a class="sidebar_bookmark_popup_more_reminder_fields" href="#">More reminder fields....</a>
    </div>
    <div class="clr"></div>
  </div>
</div>
<div class="arrow">
  <
</div>