<div class="sidebar_bookmark_popup">
  <div class="sidebar_bookmark_popup_inner">
    <?php /*<h2>Event Brief</h2> */ ?>
    <div class="yellow">
      <a href="http://www.google.com" target="_blank" class="title">地深52層樓污水隧道慶貫通</a>
      <p class="info_line">
        Music | Dec 23, 2013, 9:00 | City Hall
      </p>
      <p class="teaser">
         記者葉佩瑜報道：為改善維多利亞港水質，特區政府投放171億元於「净化海港計劃」，其中第二期甲階段工程，包括興建一條全港最深的污水隧道，堪稱現代版的「地深探險」。渠務署昨天為北角至昂船洲污水輸送系統中，北角至灣仔段隧道進行貫通慶祝典禮，該段隧道全長約3.2公里，深度介乎海平面以下140米至160米，相等於樓高52層的中環怡和大廈，隧道工程現已完成六成，預計可於2015年陸續啟用。
      </p>
    </div>
    <a class="sidebar_bookmark_popup_set_reminder" href="#" data-value="0">Set Reminder...</a>
    <div class="white">
      <form class="sidebar_bookmark_popup_form" name="sidebar_bookmark_popup_form" action="" method="post" >
        <input type="text" name="reminder_title" class="sidebar_bookmark_popup_reminder_title" value=""/>
        <textarea name="reminder_detail" class="sidebar_bookmark_popup_reminder_detail" ></textarea>
        <input type="submit" name="save" value="Save" class="sidebar_bookmark_popup_reminder_save">
      </form>
      <a class="sidebar_bookmark_popup_more_reminder_fields" href="#">More reminder fields....</a>
    </div>
    <div class="clr"></div>
  </div>
</div>
<div class="arrow">
  <
</div>