<div id="add_tags_popup">
  <div>
    <select name="new_event_filter_tags_by_tag_group" id="new_event_filter_tags_by_tag_group">
      <option value="1" selected="selected">熱門</option>
      <option value="2">電視首映</option>
      <option value="3">衛生</option>
    </select>
    <?php /*<label>Filter by</label>*/ ?>
    <input type="text" name="new_event_filter_tags_by_keyword" id="new_event_filter_tags_by_keyword" value=""/>
    <nav id="new_event_switch_tags_selected_or_all" class="right">
      <ul>
        <li>
          <a href="#" class="all pressed"><?php echo $this->translate('All') ?></a>
        </li>
        <li>
          <a href="#" class="selected"><?php echo $this->translate('Selected')?></a>
        </li>
      </ul>
    </nav>
  </div>
  <div id="new_event_tag_items">
    <div class="inner"></div>
    <div class="backup"></div>
  </div>
  <div class="f_div">
    <?php /*<label><strong>New Tags</strong></label>*/ ?>
    <input name="new_event_add_custom_tags" id="new_event_add_custom_tags" type="text">
  </div>
</div>
<script type="text/javascript">
jQuery(function($){
  $('#new_event_filter_tags_by_keyword').watermark("<?php echo $this->translate('Filter tags by keyword') ?>");
  $('#new_event_add_custom_tags').watermark("<?php echo $this->translate('Enter new tags here and separate them with commas') ?>");
	getTagsByTerm('');
	$('#new_items').val(new_items.join(', '));
})
</script>
