<?php if (isset($this->authUrls['google'])) { ?>
    <a href="<?= $this->authUrls['google'] ?>"><img src="<?php echo $this->baseUrl('images/google_icon.jpg')?>"/> google</a><br />
<?php } ?>
<?php if (isset($this->authUrls['facebook'])) { ?>
<a href="<?= $this->authUrls['facebook'] ?>"><img src="<?php echo $this->baseUrl('images/facebook-icon.jpg')?>"/> facebook</a><br />
<?php } ?>
<?php if (isset($this->authUrls['twitter'])) { ?>
<a href="<?= $this->authUrls['twitter'] ?>"><img src="<?php echo $this->baseUrl('images/twitter_icon.png')?>"/> twitter</a><br />
<?php } ?>