<div id="add_tree_popup">
  <p>Choose a category for the event. If no category is selected, an Unclassified category will be assigned:</p>
  <form id="new_event_add_tree" minlength="1" name="new_event_add_tree">
    <select class="auto_select" minlength="1" size="15" class="entrySelect" id="cat1" name="cat1"></select>
    <select class="auto_select" minlength="1" size="15" class="entrySelect" id="cat2" name="cat2"></select>
    <select class="last auto_select" size="15" class="entrySelect" id="cat3" name="cat3"></select>
    <div id="new_event_add_tree_error"></div>
  </form>
</div>
<script type="text/javascript">var category =<?php echo Common::getSession()->tree_json ?>
  ;
  var cat_arr = [];
  jQuery(function($) {
    var i;
    for ( i = 0; i < category[1].length; i += 2) {
      $('#cat1').append('<option value="' + category[1][i] + '">' + category[1][i + 1] + '</option>');
    }
    $(document).on("change", "#cat1,#cat2,#cat3", function() {
      if ($(this).prop('id') == 'cat1' || $(this).prop('id') == 'cat2') {
        changeCategory($(this).prop('id'));
      }
    });
    var cat_ids = $('#new_event_tree_ids').val();
    if (cat_ids != '') {
      var cat = cat_ids.split('|');
      cat.pop();
      cat.shift();
      var j;
      for ( j = 1; j <= cat.length; j++) {
        $("#cat" + j).val(cat[j - 1]);
        changeCategory('cat' + j);
      }
      $("#cat" + (j - 1)).val(cat[j - 2]);
    }
    
    
    // this one requires the text "buga", we define a default message, too
    $.validator.addMethod("all_selected", function(value) {
      return ($('#cat1 option:selected').length && $('#cat2 option:selected').length && $('#cat3 option:selected').length);
    }, "<?php echo $this->translate("Please make sure to specify 3 levels of category.");?>");
    
    $("#new_event_add_tree").validate({
        ignore: [],
        rules: {
          cat1: "all_selected"
        },
       errorPlacement: function(error, element) {
         error.insertAfter("#cat3");
       }
     });
  })
  function changeCategory(id) {
    var key;
    if (id == 'cat1') {
      $('#cat2,#cat3').empty();
      key = jQuery.inArray('|1|' + $('#cat1 :selected').val() + '|', category);
      if (key != -1) {
        appendOptions(key, 'cat2');
        changeCategory('cat2');
      }
      $('#cat2').removeAttr('disabled');
    } else {
      $('#cat3').empty();
      key = jQuery.inArray('|1|' + $('#cat1 :selected').val() + '|' + $('#cat2 :selected').val() + '|', category);
      if (key != -1) {
        appendOptions(key, 'cat3');
      }
      $('#cat3').removeAttr('disabled')
    }
  }

  function appendOptions(key, cat) {
    var i = 0;
    //$('#'+cat).append('<option value="">Please specify...</option>');
    for ( i = 0; i < category[key + 1].length; i += 2) {
      $('#' + cat).append('<option value="' + category[key+1][i] + '">' + category[key+1][i + 1] + '</option>').show();
    }
  }
</script>