<section class="main_inner">
    <h1><?php echo $this->tree_item->name?></h1>
    <div class="myprofile profile_form clearfix">
      <div class="profileLeft">
        <div class="profile_pic"><img src="<?php echo $this->baseUrl('images/man.gif')?>" alt=""/></div>
        <a href="#" class="upload_user_thumbnail">Upload an image</a></div>
      <div class="profile_right">
        <div class="p-div">
          <label >Related Categories:</label>
          <span class="profile_field"><?php
                $cat_info=$this->related_categories['cat_info'];
                foreach($this->related_categories['related_cats'] as $related_tree_ids){ ?>
                    <?php
                    $i=1;
                    $cats_slugname=array();
                    $cats_name=array();
                    foreach ($related_tree_ids as $cat){
                        $cats_slugname[]=$cat_info[$cat]['slug_name'];
                        $cats_name[]=$cat_info[$cat]['name'];
                
                        $cats_slugname_url=implode('/',$cats_slugname);
                        ?>
                        <a class="ajax_load" href="<?php echo $this->baseUrl('tree/'.$cats_slugname_url); ?>"><?php echo $cat_info[$cat]['name']; ?></a><?php if (count($related_tree_ids)>$i){?> > <?php } 
                        $i++;
                        if (count($this->related_categories['related_cats']) < $i) echo ', ';
                    } ?>
                    <?php
                }
                 ?></span>
        </div>
        <div class="p-div">
          <label>Description:</label>
        </div>
        </div>
        <p><?php echo $this->tree_item->description?></p>
      </div>
</section>
<nav class="righttab">
    <ul class="tabs">
      <li <?php if ($this->active_tab=='index'){?>class="active"<?php } ?>><a href="<?php echo $this -> baseUrl('tree/' . $this -> tree -> username); ?>"><img src="<?php echo $this->baseUrl('images/icon12.png')?>" alt="Feeds" /></a></li>
    </ul>
</nav>