<?php echo $this->partial('js/common/functions.phtml')?>
<?php echo $this->partial('js/common/lightboxes.phtml')?>
<?php echo $this->partial('js/common/bookmark/popup.phtml')?>
<script type="text/javascript">
var ns_common_foot = {
  mysqlTimeStampToDate: function(timestamp) {
      //function parses mysql datetime string and returns javascript Date object
      //input has to be in this format: 2007-06-05 15:26:02
      var regex=/^([0-9]{2,4})-([0-1][0-9])-([0-3][0-9]) (?:([0-2][0-9]):([0-5][0-9]):([0-5][0-9]))?$/;
      var parts=timestamp.replace(regex,"$1 $2 $3 $4 $5 $6").split(' ');
      return new Date(parts[0],parts[1]-1,parts[2],parts[3],parts[4],parts[5]);
  },
  scrollToAnchor: function(aid){
     var aTag = $("a[name='"+ aid.replace('#','') +"']");
     $('html,body').animate({scrollTop: aTag.offset().top},'slow');
  },
  getURLParameterValue: function(name) {
      return decodeURI(
          (RegExp(name + '=' + '(.+?)(&|$)').exec(location.search)||[,''])[1]
      );
  },
  showFlashMessages: function(content){
    <?php //if (jQuery(".flash_message").is(':visible'))
    //  jQuery(".flash_message").hide(); ?>
    jQuery( "#flash_message_tmpl" ).tmpl( content ).appendTo( ".flash_messages" );
    
    jQuery(".flash_messages").fadeIn(300);

  },
  getFlashMessageType: function(data){
      if (typeof data == 'object'){
          for (x in data){
              return x;
          }
      }
      return 'default';
  },
  getFlashMessageHtml: function(data){
      if (typeof data == 'object'){
          for (x in data){
              return data[x];
          }
      }
      return data;
  },
  hideMoreButton: function(more_flag, type, obj_selector){
    //var content = [{'error' : '<?php echo $this->translate('There is no more to load.')?>'}] ;
    //ns_common_foot.showFlashMessages(content);
    if (typeof more_flag == 'undefined') var more_flag=false;
    if (typeof type == 'undefined') var type = 'index';
    if (typeof obj_selector == 'undefined') var obj_selector = '.feeds_and_more .feeds';

    $(".load_more_feeds .more").hide();
    $(".load_more_feeds .loading").hide();
    var text = '';
    if (type == 'index'){
        text = '<p>No results. Please loosen the filters</p>';
    } else if ($type =='user_bookmarks'){
        text = '<p>That\'s all your bookmarks</p>';
    }
    if (more_flag) $(obj_selector).append(text);
    else $(obj_selector).html(text);
  },
  isNumber: function(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  },
  getNow: function() {
    var currentDate = new Date()
    var day = currentDate.getDate()
    var month = currentDate.getMonth() + 1
    var year = currentDate.getFullYear()
    var hours = currentDate.getHours()
    var minutes = currentDate.getMinutes()
    var seconds = currentDate.getSeconds()
      if (minutes < 10)  minutes = "0" + minutes
      if (seconds < 10)  seconds = "0" + seconds
     return year+ "-" + month + "-" + day  + " "+ hours + ":" + minutes +":" + seconds + " ";
  },
  goToByScroll: function(element){
    $('html,body').animate({scrollTop: $(element).offset().top},'slow');
  },
  /*
   * clone object by jQuery.extend (deep copy)
   * @param: source / 來源物件
   * @param: append / 附加的值 (非必要)
   */
  clone: function (source, append) {
    if ('undefined' !== typeof append) {
      var obj = jQuery.extend({}, source);
      return jQuery.extend(true, obj, append);
    } else {
      return jQuery.extend(true, {}, source);
    }
  },
  <?php //update variables from url parameters ?>
  updateVariablesFromUrlParams: function(){
    for (key in ns_feeds.default_feed_para){
        var value = ns_common_foot.getURLParameterValue(key);
        if (ns_feeds.isFeedParameterValid(key, value) && value != ""){
            ns_feeds.feed_para[key] = value;
            ns_feeds.updateUrlParam(key, value);
        } else {
            ns_feeds.feed_para[key] = ns_feeds.default_feed_para[key];
        }
    }
  },
  getFormDataJson: function(form_css_selector){
    return JSON.stringify($(form_css_selector).serializeObject())
  }<?php /*
  saveFormToCookie: function(form_id, data){
    console.log('saveFormCookie')    
    if (typeof data == 'undefined'){
      data =  $.extend(data,$('#'+form_id).serializeObject());
    }
    console.log(JSON.stringify(data));
    $.cookie.json = true;
    $.cookie(form_id, data, {path: '/'});
  },
  loadCookieToForm: function(form_id){
    if ($.cookie(form_id) != '' && $.cookie(form_id) != null){
      //console.log($.cookie(form_id))
      //var form_data = JSON.parse($.cookie(form_id));
      $.cookie.json = true;
      var form_data = $.cookie(form_id);
      console.log(JSON.stringify(form_data));
  
      $('#'+form_id).find('input, textarea').each(function(){
          if ($(this).prop('name').length && $(this).prop('name') in form_data){
            if (form_data[$(this).prop('name')]!=''){
          //console.log($(this))
          //console.log($(this).prop('value'))
              //if checkbox 
              if ($(this).is(':checkbox')){
                $(this).prop('checked','checked');
              //if text input
              }else if ($(this).prop('value')==''){
          //console.log($(this))
                
                $(this).val(form_data[$(this).prop('name')]);
              }
            }
          }
      });
    }
  } */?>
}

jQuery(function($){
      // Dialog
  $('#dialog').dialog({
      autoOpen: false,
      width: 700,
      buttons: {
          "Ok": function() {
              $(this).dialog("close");
          },
          "Cancel": function() {
              $(this).dialog("close");
          }
      }
  });
  $('body').on('click','.language a',function(){
      $.ajax({
        type: "POST",
        url: "<?php echo $this->baseUrl('ajax/language/switch') ?>",
          data: {
              display_lang:$(this).find('input').val()
          },
        success: function(msg){
          if(msg['result']==true){
              window.location.hash = ''; //if you want to reload with an empty hash
              window.location.reload(true); //reload the page and bypass the cache
          }else{
              alert('Unkown error occured. Please try again later.')
          }
          },
          dataType:'json'
      });
      return false;
  })
  .on('click','.flash_message .close',function(){
      $(this).parents(".flash_messages").fadeOut(300, function(){
         $(this).empty();
      });
      return false;
  })
  .on('click','#login-trigger',function(e){
    e.preventDefault();
    $(this).next('#login-content').slideToggle();
    $(this).toggleClass('active');
    
    if ($(this).hasClass('active')) $(this).find('span').html('&#x25B2;')
      else $(this).find('span').html('&#x25BC;')
  })
  .on('click', function(e) {
    if (!$(e.target).closest('.bookmark_popup, #highlight_tab li, #bookmark_tab li').length) {
      ns_common_bookmark_popup.togglePopup($('.bookmark_popup:visible').data('id'));
      
      ns_common_bookmark_popup.touching_id = null;
      $('.bookmark_popup:visible').data('hover',0)
      ns_common_bookmark_popup.clicked_id = null;
      $('#highlight_tab li, #bookmark_tab li').removeClass('clicked');
    }
    if (!$(e.target).closest('#login-trigger, #login-content').length && $('#login-trigger').hasClass('active')) {
      $('#login-trigger').next('#login-content').slideToggle();
      $('#login-trigger').removeClass('active');
      $('#login-trigger').find('span').html('&#x25BC;')
    };
    if (!$(e.target).closest('a.place, #feeds_map_popup').length) {
      $('#feeds_map_popup').hide();
    };
  })
  
  $(window).resize(function(){
    if ($('.bookmark_popup').is(':visible'))
      ns_common_bookmark_popup.togglePopup();
      <?php //ns_common_bookmark_popup.adjustSidebarPopupPosition($('.bookmark_popup:visible').data('id')); ?>
    
  }); 
  
  <?php /* ?>$('.login_info .login').qtip({
      content: {
          text: '<p style="text-align:center;"><img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." /></p>',
          ajax: {
              url: '<?php echo $this->baseUrl('ajax/auth/open_login_box')?>',
              success: function(data, status) {
                  if (data.result == 'false'){
                      this.set('content.text', 'already loginned!');
                  } else {
                      this.set('content.text', $( "#login" ).tmpl(data.data));
                  }
                  $('input.username').watermark("<?php echo $this->translate('Username') ?>");
                  $('input.password').watermark("<?php echo $this->translate('Password') ?>");
              },
              once: true,
              loading: true
          },
          title: {
              text: 'Login'
          }
      },
      show: {
          event: 'click',
          modal: {
              on: true
          }
      },
      position: {
          my: 'center',
          at: 'center',
          target: $(window)
      },
      style: {
          def:false,
          classes: 'qtip-light qtip-rounded login_dialog'
      }
  });
  $('body').on('click', '.watcher_icon' , function() {
      $(this).qtip(
      {
          //overwrite: false, 
          content: {
              text: '<img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." />',
              ajax: {
                  url: '<?php echo $this->baseUrl('ajax/bookmark/open_box_trigger')?>', 
                  success: function(data, status) {
                      this.set('content.text', $( "#bookmark_box_trigger" ).tmpl());
                  }
              },
              title: {
                  text: 'Bookmark details'
              }
          },
          position: {
              at: 'bottom center', 
              my: 'top right',
              target: $(this)
          },
          show: {
               ready: true
          },
          style: {
              def:false,
              classes: 'qtip-light bookmark_box_trigger qtip-shadow'
          }
      })
  })
  <?php */ ?>
  
  var loginined_popup;
  $('body').on('click', '.login_info .grid_icon' , function() {
      var target = $(this) ;
      if (!target.hasClass('active')){
          if (typeof loginined_popup == 'undefined' ){
              loginined_popup = $(this).qtip(
                  {
                      content: {
                          text: '<img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." />',
                          ajax: {
                              url: '<?php echo $this->baseUrl('ajax/header/open_loginned_popup')?>', 
                              success: function(data, status) {
                                  this.set('content.text', $( "#loginned_popup" ).tmpl());
                              },
                              once: true
                          },
                          title: {
                              button: false
                          }
                      },
                      events: {
                          hidden: function(event, api) {
                              target.removeClass('active');
                          }
                      },
                      position: {
                          at: 'bottom center', 
                          my: 'top right',
                          target: $(this)
                      },
                      show: {
                           ready: true
                      },
                      style: {
                          def:false,
                          classes: 'qtip-light loginned_popup qtip-shadow'
                      }
                  })
             }else{
               loginined_popup.qtip('show');
             }
      } else {
          loginined_popup.qtip('hide');
      }
      target.toggleClass('active');
  }).on('click', 'a', function(e){
    if( $(this).attr('href') === '#' ) e.preventDefault(); 
  });;
  $('input.username').watermark("<?php echo $this->translate('username') ?>");
  $('input.password').watermark("<?php echo $this->translate('password') ?>");
  $('input.keyword_text').watermark("<?php echo $this->translate('enter keyword') ?>...");
  $('.loc_right input').watermark("<?php echo $this->translate('enter location') ?>...");
  
  //defining daterange below search bar...
  //$.datepicker.setDefaults($.datepicker.regional['zh-HK']);
  
 /*$("select.selectBoxIt").selectBoxIt({
    showEffect: "fadeIn",
    showEffectSpeed: 100,
    hideEffect: "fadeOut",
    hideEffectSpeed: 100
 });*/
  ns_common_foot.updateVariablesFromUrlParams();
});
</script>
<?php echo $this->partial('js/template/auth/login.phtml')?>
<?php echo $this->partial('js/template/common/bookmark/box_trigger.phtml')?>
<?php echo $this->partial('js/template/common/bookmark/popup.phtml')?>
<?php echo $this->partial('js/template/header/loginned_popup.phtml')?>