<?php echo $this->partial('js/template/event/reminder_form.phtml'); ?>
<script type="text/javascript">
jQuery(function($) {
  $('body').on('click','.bookmark_popup_more_reminder_fields',function(){
    var item_id = $(this).parents('.bookmark_popup').data('id');
    $.ajax({
      url: "<?php echo $this->baseUrl('ajax/event/reminder_form') ?>",
      data: {item_id: item_id},
      beforeSend:  function() {
      },
      success: function(msg){
        var colorbox_options = 
        $.colorbox({
          transition:"none",
          fadeOut: 0,
          closeButton: false,
          html:$( "#event_reminder_form_tmpl" ).tmpl(msg.data, ns_event_reminder_form.tmpl_functions),
          onComplete:function(){ ns_event_reminder_form.init(); }
        });
        return true;
      }
    });
    return false;
  })
  .on('click','#menu .new_event', function(e){
    e.preventDefault();
    ns_common_head.jQDialog(
      '<?php echo $this->baseUrl('ajax/dialog/new_event')?>',
      {
          title: '<?php echo $this->translate('New Event') ?>',
          open: function( event, ui ) {ns_news_event_popup.showform(0)}

      }
    );
    return false;
  });
});
</script>
<?php echo $this->partial('js/event/reminder_form.phtml'); ?>
<?php echo $this->partial('js/new_event/popup.phtml')?>