<script type="text/javascript">
var tinymce_ns = {};
jQuery(function($){
  tinymce_ns = {
    init : function(tinymce_toggle_css_selector, textarea_element){
      $('body').on('click',tinymce_toggle_css_selector, function(){
          if (textarea_element.data('is_tinymce_loaded') == true) {
              if (textarea_element.tinymce().isHidden()){
                  textarea_element.tinymce().show();
              } else {
                  textarea_element.tinymce().hide();
              };
          } else {
              tinymce_ns.loadTinymce(textarea_element);
          }
          return false;
      })
   },
   loadTinymce: function(elem){
    elem.tinymce({
        script_url : '<?php echo $this->baseUrl('js/tinymce/tiny_mce.js'); ?>',
        theme : "advanced",
        plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist,autoresize",

        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,cut,copy,paste,pastetext,pasteword,|,search,replace,|,justifyleft,justifycenter,justifyright,justifyfull",
        theme_advanced_buttons2 : "bullist,numlist,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons3 : "outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons4 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,fullscreen",
        theme_advanced_resizing : true,
        
        content_css : "<?php echo $this->baseUrl('css/tinymce/advanced/content.css'); ?>",
    });
    
    elem.data('is_tinymce_loaded', true);
   }
  };
})

</script>