<script type="text/javascript">
var tinymce_ns = {};
jQuery(function($){
  tinymce_ns = {
    init : function(tinymce_toggle_css_selector){
      //if ($(tinymce_toggle_css_selector+'_is_toggled').val() == 1){
        tinymce_ns.loadTinymce($(tinymce_toggle_css_selector));
        //$(tinymce_toggle_css_selector).tinymce().show();
      //}
      <?php /*console.log(tinymce_toggle_css_selector)
      console.log($(tinymce_toggle_css_selector+'_is_toggled').val())
      console.log($(tinymce_toggle_css_selector).data('is_tinymce_loaded'))
      console.log($(tinymce_toggle_css_selector).data('is_tinymce_loaded') == true)*/
      
    /*  $('body').on('click',tinymce_toggle_css_selector+'_toggle_editor', function(e){
        e.preventDefault();
        if ($(tinymce_toggle_css_selector).data('is_tinymce_loaded') == true) {
            if ($(tinymce_toggle_css_selector).tinymce().isHidden()){
                $(tinymce_toggle_css_selector).tinymce().show();
                $(tinymce_toggle_css_selector+'_is_toggled').val(1);
            } else {
                $(tinymce_toggle_css_selector).tinymce().hide();
                $(tinymce_toggle_css_selector+'_is_toggled').val(0);
            };
        } else {
            tinymce_ns.loadTinymce($(tinymce_toggle_css_selector));
            $(tinymce_toggle_css_selector+'_is_toggled').val(1);
        }
        return false;
      })*/?>
   },
   loadTinymce: function(elem){
    elem.tinymce({
        script_url : '<?php echo $this->baseUrl('js/tinymce/tiny_mce.js'); ?>',
        theme : "simple",
        <?php /*plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist,autoresize",

        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,strikethrough,|,cut,copy,paste,pastetext,pasteword,|,search,replace,|,justifyleft,justifycenter,justifyright,justifyfull",
        theme_advanced_buttons2 : "bullist,numlist,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons3 : "outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons4 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,fullscreen",
        theme_advanced_resizing : true,*/?>
        
        <?php /*content_css : "<?php echo $this->baseUrl('css/tinymce/advanced/content.css'); ?>",*/?>
    }).show();
    
    elem.data('is_tinymce_loaded', true);
   }
  };
})

</script>