<script type="text/javascript" src="<?php echo $this->baseUrl('js/tinymce_v4/tinymce.min.js')?>"></script>
<script type="text/javascript">

tinyMCE.init({
    selector: "#new_event_description",
    plugins : [
      "advlist autolink lists link image charmap print preview anchor",
      "searchreplace visualblocks code fullscreen",
      "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});
</script>