<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<?php if ($this->tag_item != NULL){ ?>
    <?php //echo $this -> partial('js/tree.phtml'); ?>
    <?php echo $this -> partial('partials/tag/profile.phtml', array('tag_item' => $this->tag_item)); ?>
    
    <section class="tab_container">
        <section id="tag_events" data-id="<?php echo $this->tree_item->id ?>" class="tab_content" >
            <h1 class="heading1">Hot Events</h1>
        
            <div class="post" id="more_updates">
                <div class="feeds tree_feeds"></div>
                <div class="more_div">
                    <a style="display:none;" class="more" href="#"> More &gt; </a>
                    <img style="display:none;" class="loading"  alt="loading..." src="<?php echo $this->baseUrl('images/ajax-loader.gif') ?>" />
                </div>
            </div>
        </section>
    </section>
    
    <script type="text/javascript">
    var tag_events_json = jQuery.parseJSON('<?php echo json_encode($this->tag_events) ?>');
    jQuery(function($){
        renderIndexFeeds(tag_events_json, false);
    });
    </script>
    <?php echo $this->partial('js/page/tag_events.phtml', array('tag_id' => $this->tag_item->id)); ?>

<?php }else{
    echo 'This tag has not been established yet.';
}  ?>
