<script id="bookmark_popup" type="text/x-jquery-tmpl">
    <div data-id="${$item.getID()}" class="bookmark_popup{{if $item.hasReminderContent()}} has_reminder{{/if}}{{if is_like}} bookmarked{{else}} not_bookmarked{{/if}}">
      <div class="bookmark_popup_inner">
        <div class="yellow">
          <a href="<?php echo $this->baseUrl('event');?>/${slug_name}" target="_blank" class="title">${name}</a>
          <?php /*<p class="info_line">
            Music | Dec 23, 2013, 9:00 | City Hall
          </p>*/ ?>
            <ul class="info_line">
              {{if $item.hasMainCat() }}
              <li>
                  <a target="blank" href="${$item.getMainCatURL()}"><strong>${$item.getMainCatName()}</strong></a>
              </li>
              {{/if}}
              {{if begin_datetime}}
                  {{if $item.hasMainCat() }}
                  <li>
                      |
                  </li>
                  {{/if}}
              <li>
                  start: ${$item.formatMysqlDate($data.begin_datetime)}
              </li>
              {{/if}}
              {{if place}}
                  {{if $item.hasMainCat() || begin_datetime}}
              <li>
                  |
              </li>
                  {{/if}}
              <li>
                  place: 
                  {{if degree}}
                      <a href="#" title="${degree}&deg;"><img class="direction-arrow ${degree}" height="10" src="<?php echo $this->baseUrl('images/direction-arrow.jpg');?>" /></a>
                  {{/if}}
                  {{if place_lat && place_lng}}<a class="place" data-coord="${place_lat},${place_lng}" title="${place}" href="#">{{else}}<span class="place">{{/if}}${place}{{if place_lat && place_lng}}</a>{{else}}</span>{{/if}}
              </li>
              {{/if}}
          </ul>
          <div class="clr"></div>
          <p class="teaser">
             ${teaser}
          </p>
        </div>
        <a class="bookmark_popup_set_reminder" href="#" data-value="0">Set Reminder...</a>
        <div class="white">
          <?php /*<form class="bookmark_popup_form" data-id="${id}" name="bookmark_popup_form" action="" method="post" >*/ ?>
            {{if reminder_title}}
              <div class="text_field">
                <?php echo $this->translate('Title')?>: <div id="bookmark_popup_reminder_title" class="inline_edit_text">${reminder_title}</div> 
                <div class="clr"></div>
              </div>
            {{/if}}
            {{if reminder_description}}
              <div class="textarea_field">
                <?php echo $this->translate('Description')?>:
                <div class="bookmark_popup_reminder_description inline_edit_textarea">${reminder_description}</div>
                <div class="clr"></div>
              </div>
            {{/if}}
            {{if reminder_tags}}
              <div class="text_field">
                <?php echo $this->translate('Tags')?>: <div id="bookmark_popup_reminder_tags" class="inline_edit_text">${reminder_tags}</div>
                <div class="clr"></div>
              </div>
            {{/if}}
            {{if reminder_attend_datetime}}
              <div class="text_field">
                <?php echo $this->translate('Attend datetime')?>: <div id="bookmark_popup_reminder_attend_datetime" class="inline_edit_text">${reminder_attend_datetime}</div>
                <div class="clr"></div>
              </div>
            {{/if}}
            {{if reminder_has_email_alarm}}
              <div class="text_field">
                <?php echo $this->translate('Email alert')?>: <div id="bookmark_popup_reminder_has_email_alarm" class="inline_edit_text">${$item.getAlertTime('email')}</div>
                <div class="clr"></div>
              </div>
            {{/if}}
            {{if reminder_has_popup_alarm}}
              <div class="text_field">
                <?php echo $this->translate('Popup alert')?>: <div id="bookmark_popup_reminder_has_popup_alarm" class="inline_edit_text">${$item.getAlertTime('popup')}</div>
                <div class="clr"></div>
              </div>
            {{/if}}
            {{if reminder_has_mobile_alarm}}
              <div class="text_field">
                <?php echo $this->translate('Mobile alert')?>: <div id="bookmark_popup_reminder_has_mobile_alarm" class="inline_edit_text">${$item.getAlertTime('mobile')}</div>
                <div class="clr"></div>
              </div>
            {{/if}}
         <?php // </form> ?>
          <a class="bookmark_popup_more_reminder_fields" href="#">More reminder fields....</a>
          <div class="reminder_save_status">
            <span class="saving"><?php echo $this->translate('Saving...')?></span>
            <span class="saved"><?php echo $this->translate('Saved')?></span>
          </div>
        </div>
        <div class="clr"></div>
      </div>
    </div>
</script>