<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<?php echo $this -> partial('js/settings.phtml'); ?>
<article class="main shadow">
    <section class="mainevent settings_form">
        <h1>Manage Your Details</h1>
        <div class="event_div event_form">
            <div class="eventtype">
                <div class="e_type_div clearfix">
                    <div class="profileLeft">
                        <div class="all_e_div"><img src="images/man.gif" alt=""/>
                        </div>
                        <a href="#uploadThumbnail" class="upload leanModal">Upload an image</a>
                    </div>
                    <div class="profile_right">
                        <h6>Hello !</h6>
                        <p>
                            <strong>Customise your Tagbees.com experience.</strong>
                            <br />
                            Please give us more information about you to help us provide you with relevant information and offers.
                        </p>
                    </div>
                </div>
            </div>
            <article class="event_div2 event_con">
                <div class="eventtype">
                    <h6>Your TagBees.com Memberships</h6>
                    <p>
                        You are currently a member of TagBees.com sites. To opt-out please select logout from the popup window of the register / login.
                    </p>
                </div>
            </article>
        </div>
        <h1>Personal Information</h1>
        <section class="event_div event_form">
            <div class="eventtype">
                <div class="f_div">
                    <label for="user-name">User Name</label>
                    <input type="text" id="user-name" class="middle changetxt" />
                    <label class="l-a1" id="changeInput"><strong>change</strong></label>
                </div>
                <div class="f_div">
                    <label class="place_res" for="place-of-residence">Place of residence</label>
                    <input type="text" id="place-of-residence" class="middle" />
                    <label class="l-a1 settingMap">Hide Map</label>
                </div>
                <div class="f_div" id="settingMapDiv">
                    <label>&nbsp;</label>
                    <div class="f_map"><img src="images/map-form.gif" alt=" " />
                    </div>
                </div>
                <div class="f_div">
                    <label>Gender</label>
                    <select class="smallSel">
                        <option></option>
                        <option>Male</option>
                        <option>Female</option>
                    </select>
                    <?php /*<input type="radio" id="male" name="gender" />
                    <label class="l-a3" for="male"><strong>Male</strong></label>
                    <input type="radio" id="female" name="gender" />
                    <label class="l-a3" for="female"><strong>Female</strong></label>*/ ?>
                    <select class="smallSel">
                        <option>Public</option>
                    </select>
                    <label class="l-a1" style="margin-left:15px;"><strong>Birthday</strong></label>
                    <input type="text" id="birthday" name="birthday" class="m-input" />
                    <select class="smallSel small_gap1">
                        <option>Public</option>
                    </select>
                </div>
                <div class="f_div">
                    <label for="homepage">Homepage</label>
                    <input type="text" class="middle1" id="homepage" />
                    <select class="smallSel small_gap1">
                        <option>Public</option>
                    </select>
                </div>
                <div class="f_div">
                    <label for="email">Email</label>
                    <input type="text" class="middle1" id="email" />
                    <select class="smallSel small_gap1">
                        <option>Public</option>
                    </select>
                </div>
                <div class="f_div">
                    <label for="desctiption">Description</label>
                    <textarea class="middle1" id="desctiption"></textarea>
                    <select class="smallSel small_gap1">
                        <option>Public</option>
                    </select>
                </div>
                <div class="f_div">
                    <label>Time Zone</label>
                    <select class="smallSel1">
                        <option>Hong Kong</option>
                    </select>
                    <input type="text"/>
                    <select class="smallSel small_gap1">
                        <option>Public</option>
                    </select>
                </div>
                <div></div>
            </div>
        </section>
        <h1>Social Connections</h1>
        <section class="event_div event_form">
            <div class="eventtype">
                <div class="f_div">
                    <label>Facebook <img src="images/facebook_icon.png" alt="facebook" /></label>
                    <label class="l-a1"><a href="#">http://www.facebook.com/abcduser</a> </label><img src="images/close.png" alt="close" id="close" class="top_gap" /><a href="#social_connections" class="top_gap leanModal"><img src="images/i_icon.png" alt="icon" /></a>
                </div>
                <div class="f_div">
                    <label>Twitter <img src="images/twitter_icon.png" alt="twitter" /></label>
                    <label class="l-a1"><a href="https://twitter.com/" target="_blank"><img src="images/twitter_icon2.png" alt="twitter" /></a> <a href="#"><img src="images/i_icon.png" alt="icon" /></a></label>
                </div>
                <div class="f_div">
                    <label>Tumblr <img src="images/tumblr.png" alt="twitter" /></label>
                    <label class="l-a1"><a href="javascript:void(0)" id="addTumblr"><img src="images/plus.png" alt="plus" class="add_tum" /> Add Tumblr Details</a> </label>
                </div>
                <div class="addTumblrDiv">
                    <div class="f_div">
                        <label>Tumblr <img src="images/tumblr.png" alt="twitter" /></label>
                        <input type="text" value="" class="middle" />
                        <label class="l-a1"><strong>Tumblr Email</strong></label>
                    </div>
                    <div class="f_div">
                        <label>&nbsp;</label>
                        <input type="text" value="" class="middle" />
                        <label class="l-a1"><strong>Tumblr Password</strong></label>
                    </div>
                </div>
            </div>
        </section>
        <h1>Notifications</h1>
        <section class="event_div event_form notifications">
            <div class="eventtype">
                <div class="f_div">
                    <label class="l-a1"><strong>Receive notifications for these events</strong></label>
                </div>
                <div class="f_div">
                    <label>&nbsp;</label>
                    <input class="" type="checkbox" id="alarm-setting" data-label="Alarm Setting"/>
                    <?php //<label class="l-a" for="alarm-setting"><strong>Alarm Setting</strong></label> ?>
                </div>
                <div class="f_div">
                    <label>&nbsp;</label>
                    <?php /*<input type="checkbox" id="messages" />
                    <label class="l-a" for="messages"><strong>Messages</strong></label>*/?>
                    <input class="" type="checkbox" id="messages" data-label="Messages"/>
                    <div class="clear"></div>
                    <label>&nbsp;</label>
                    <div class="list list_gap">
                        <ul>
                            <li>
                                Your fan publish a social event
                            </li>
                            <li>
                                Someone writes on your message board
                            </li>
                            <li>
                                Someone comments on your event
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="f_div">
                    <label>&nbsp;</label>
                    <?php /*<input type="checkbox" id="updates" />
                    <label class="l-a" for="updates"><strong>Updates</strong></label>*/?>
                    <input class="" type="checkbox" id="updates" data-label="Updates"/>
                    <div class="clear"></div>
                    <label>&nbsp;</label>
                    <div class="list list_gap">
                        <ul>
                            <li>
                                Important announcements from Tagbees
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="f_div div_center">
                    <input type="submit" value="Save" class="submit1" />
                    <input type="submit" value="Restore" class="submit2" />
                </div>
            </div>
        </section>
    </section>
</article>
