<div class="e_type_div">
  <label><?php echo $this->translate('new_event_event_type'); ?></label>
  <div class="new_event_event_types">
    <div class="inner clearfix">
      <ul>
        <li>
          <a href="#" class="profile_pic allgap" data-value="1"> <img src="<?php echo $this->baseUrl('images/public_event.gif')?>" alt="Public Event"/> <h6><?php echo $this -> translate('Public Event'); ?></h6> </a>
        </li>
        <li>
          <a href="#" class="profile_pic allgap" data-value="2"> <img src="<?php echo $this->baseUrl('images/private_event.gif')?>" alt="Private Event"/> <h6><?php echo $this -> translate('Private Event'); ?></h6> </a>
        </li>
        <li>
          <a href="#" class="profile_pic" data-value="3"> <img src="<?php echo $this->baseUrl('images/attraction.gif')?>" alt="Attraction"/> <h6><?php echo $this -> translate('Attraction'); ?></h6> </a>
        </li>
      </ul>
      <input type="hidden" id="new_event_event_type" name="new_event_event_type" value="" required />
    </div>
    <div class="new_event_type_caption">
      <div id="new_event_type_caption_1" style="display:none">
        <p>
          <?php echo $this -> translate('For events either you are the representative of the organizer or the information supplier of an event organized for the public.'); ?>
        </p>
      </div>

      <div id="new_event_type_caption_2" style="display:none">
        <p>
          <?php echo $this -> translate('For events either you are the representative of the organizer or the information supplier of an event organized for the Private.'); ?>
        </p>
      </div>

      <div id="new_event_type_caption_3" style="display:none">
        <p>
          <?php echo $this -> translate('For events either you are the representative of the organizer or the information supplier of an event organized for the Attraction.'); ?>
        </p>
      </div>
    </div>
  </div>
</div>