<div class="f_div">
  <label for="<?php echo $this->name ?>"><?php echo $this->translate($this->name);?></label>
  <textarea class="full" rows="5" cols="25" id="<?php echo $this->name ?>" name="<?php echo $this->name ?>" ></textarea>
  <a href="#" class="toggle_editor text_link" id="<?php echo $this->name ?>_toggle_editor">[<?php echo $this->translate('toggle_editor');?>]</a>
  <input type="hidden" value="0" name="<?php echo $this->name ?>_is_toggled" id="<?php echo $this->name ?>_is_toggled">
</div>