<div class="f_div">
  <label><?php echo $this->translate($this->name); ?></label>
    <p class="tree_text tree_line_hidden"></p>
	    <div class="clearfix tree_line_hidden"></div>
	    <label class="tree_line_hidden"></label>
      <a href="#" class="choose tree_popup" id="addToCategory"><?php echo $this->translate('Please choose correct tree path to help your event easier to reach target group')?></a>
		<input id="tree_text" name="tree_text" value="" type="hidden" />
		<input name="<?php echo $this->name ?>" id="<?php echo $this->name ?>" value="" type="hidden" />
</div>
<script type="text/javascript">
	jQuery(function($){
		$('.tree_text').text($('#tree_text').val());
		
		$('body').on('click',".tree_popup",function(){
			jQDialog(
				'<?php echo $this->translate('Add Tree') ?>',
				'<?php echo $this->baseUrl('ajax/dialog/add_tree')?>',
				{},
				{
  				Confirm: function() {
            if ($("#new_event_add_tree").valid()){
              var value='|'+$('#cat1 :selected').val()+'|';
              var text=$('#cat1 :selected').text();
              if($('#cat2 :selected').length!=0){
                value += $('#cat2 :selected').val()+'|';
                text += ' > ' + $('#cat2 :selected').text();
                if ($('#cat3 :selected').length!=0){
                  value += $('#cat3 :selected').val()+'|';
                  text += ' > ' + $('#cat3 :selected').text();
                }
              }
              $('#<?php echo $this->name ?>').val(value);
              $('.tree_text').text(text);
              $('#tree_text').val(text);
              $('.tree_line_hidden').show();
              $('label.tree_line_hidden').css('display','inline-block');
              $('p.tree_line_hidden').css('display','inline-block');
              $( this ).dialog( "close" );
            }
  				},
  				Cancel: function() {
  						$( this ).dialog( "close" );
  					}
	    	 	}
	    	 );
	   	 	return false;
		})
	});
</script>