<?php echo $this->partial('breadcrumbs.phtml'); ?>
<div class="settings auth forgot-password">
	<h2><?php echo $this->translate('Forgot Password')?></h2>
	<div class="section">
		<div class="content">
			<form method="post" action="<?php echo $this->baseUrl('auth/forgot_password')?>" id="forgot_password">
				<?php echo $this->partial('partials/input/text.phtml',array('is_privacy_enabled'=>false,'required'=>true,'title'=>'Email','name'=>'email')); ?>
				<div class="btnSet" style="padding-bottom:10px;">
					<input type="submit" value="<?php echo $this->translate('Request for password reset')?>" />
				</div>
			</form>
            <script type="text/javascript">
            jQuery(function($){
                $("#forgot_password").validate({
                    onkeyup: false,
                    onclick: false,
                    rules: {
                        email: {
                            required: true,
                            email: true
                        }
                    }
                });
            });
            </script>
		</div>
	</div>
</div>
