<?php echo $this->partial('breadcrumbs.phtml'); ?>
<div class="settings auth reset-password">
	<h2><?php echo $this->translate('Reset Password')?></h2>
	<div class="section">
		<div class="content">
			<form method="post" action="<?php echo $this->baseUrl('auth/reset_password')?>" id="reset_password">

                <?php echo $this->partial('partials/input/text.phtml',array('disabled'=>true,'title'=>'Email','name'=>'email','value'=>$this->email)); ?>

                <?php echo $this->partial('partials/input/password.phtml',array('required'=>true,'title'=>'New Password','name'=>'password')); ?>

                <?php echo $this->partial('partials/input/password.phtml',array('required'=>true,'title'=>'Confirmed Password','name'=>'confirmed_password')); ?>
                <div class="btnSet" style="padding-bottom:10px;">
					<input type="submit" value="<?php echo $this->translate('Submit')?>" />
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
jQuery(function($){
    $("#reset_password").validate({
       onkeyup: false,
       onclick: false,
        rules: {
            password: {
                required: true,
                minlength: 6
            },
            confirmed_password: {
                required: true,
                equalTo: "#password"
            }
        }
    });
});
</script>

