<script id="tmpl_event_detail" type="text/x-jquery-tmpl">
  
    <article data-id="${id}" class="detail_div post_content clearfix {{if is_like}}{{if is_like==1 }}bookmarked{{/if}}{{/if}}">
      <header>
          <div class="bookmark_area">
              <div class="w1">
                  <div data-id="${id}" class="star">
                      <div class="star_inner"></div>
                  </div>
                    <span class="w_con">Watched: ${like_count}</span>
              </div>
          </div>
          <h3 class="head4">${name} (${event_type})</h3>
      </header>
    <div class="main_details clearfix">
      <iframe class="img_gallery" height="{{if img_filenames!=''}}380{{else}}0{{/if}}" width="100%" src="${gallery_url}"></iframe>
      <div class="d_l">
        <table class="d_table">
            <?php //tree ?>
            {{if tree_ids }}
            <tr>
                <td class="title"><strong><?php echo $this -> translate('Tree: '); ?></strong></td>
                <td class="content">
                <a target="blank" href="${$item.getMainCatURL()}"><strong>${$item.getMainCatName()}</strong></a>
                </td>
            </tr>
            {{/if}}
            <?php //time ?>
            {{if is_any_time==0 }}
            <tr>
                <td class="title"><strong><?php echo $this -> translate('Time: '); ?></strong></td>
                <td class="content">
                  <div class="event_datetime">
                  {{if begin_datetime }}
                    ${$item.getDateTime($data.begin_datetime)}
                  {{else}}
                    ?
                  {{/if}} <br />
                  - 
                  {{if end_datetime }}
                    ${$item.getDateTime($data.end_datetime)}
                  {{else}}
                    ?
                  {{/if}}
                  {{if datetime_note }}
                     <div class="event_datetime_note more">
                        {{html $data.datetime_note}}
                     </div>
                  {{/if}}
                   </div>
                </td>
            </tr>
            {{/if}}
            
            <?php //place ?>
            {{if place }}
            <tr>
                <td class="title"><strong><?php echo $this -> translate('Place: '); ?></strong></td>
                <td class="content">
                   <div class="event_place">
                       ${place}
                      
                    {{if traffic_note }}
                       <div class="event_traffic_note more">
                        {{html $data.traffic_note}}
                       </div>
                    {{/if}}
                   </div>
                </td>
            </tr>
            {{/if}}
            
            <?php //price ?>
            <tr>
                <td class="title"><strong><?php echo $this -> translate('Price: '); ?></strong></td>
                <td class="content">
                  
                   <div class="event_price">
                    {{if is_free==0 }}
                        
                      {{if price_min }}
                        $ ${price_min}
                      {{else}}
                        ?
                      {{/if}} 
                      - 
                      {{if price_max }}
                        $ ${price_max}
                      {{else}}
                        ?
                      {{/if}}
                    {{else}}
                      <?php echo $this->translate('Free!') ?>
                    {{/if}}
                  {{if price_note }}
                     <div class="event_price_note more">
                      {{html $data.price_note}}
                     </div>
                  {{/if}}
                </div>
              </td>
            </tr>
            
            <?php //organiser ?>
            {{if organiser_name }}
            <tr>
                <td class="title"><strong><?php echo $this -> translate('Organiser Name: '); ?></strong></td>
                <td class="content">
                   <div class="event_place">
                       ${organiser_name}
                      
                    {{if organiser_note }}
                       <div class="event_organiser_note more">
                        {{html $data.organiser_note}}
                       </div>
                    {{/if}}
                   </div>
                </td>
            </tr>
            {{/if}}
        </table>
      </div>
      {{if place_lat && place_lng && <?php echo Zend_Registry::get('config_ini')->server->online ?>}}
          <div id="event-map" style="float:right;width:220px;height:220px;"></div>
      {{/if}}
    </div>
      <div class="d_middle">
        <?php if (Zend_Auth::getInstance()->hasIdentity()){ ?>
          <a href="#" class="upload_link ui-state-default ui-corner-all">Upload More Images</a>
        <?php } ?>
          <div class="qr_code">
              <div class="qrcode" id="qr1"></div>
          </div>
      </div>
      <h2>Description</h2>
      <div class="description">
        {{html $data.description}}
        <div class="clearfix"></div>
      </div>
      <h2>Application</h2>
      <div class="application">
        {{html $data.application_note}}
        <div class="clearfix"></div>
      </div>
    <footer>
      <div class="tag_l left">
          <strong>Tags:</strong>{{html $item.tagHTML()}}
      </div>
      <div class="tag_r">
          by <a target="_blank" href="<?php echo $this->baseUrl('user');?>/${submitter_slug_name}">${submitter_name}</a>| <abbr class="timeago" title="${create_time}">
      </div>
    </footer>
  </article>
</script>