<script id="event_reminder_form_tmpl" type="text/x-jquery-tmpl">
      <form id="event_reminder_form" data-id="${id}" style="padding: 10px;">
        <input type="hidden" name="event_reminder_item_id" value="${id}"/>
        <table class="event_reminder_form">
          <tbody>
            <tr>
              <th>
                <label><?php echo $this->translate('event_reminder_title');?></label>
              </th>
              <td>
                <input type="text" value="${reminder_title}" id="event_reminder_title" name="event_reminder_title" class="full textinput" />
              </td>
            </tr>
            <tr>
              <th>
                <label><?php echo $this->translate('event_reminder_description');?></label>
              </th>
              <td>
                <textarea name="event_reminder_description" id="event_reminder_description" class="textinput" rows="13">${reminder_description}</textarea>
              </td>
            </tr>
            <tr>
              <th>
                <label><?php echo $this->translate('event_reminder_tags');?></label>
              </th>
              <td>
                <input type="text" value="${reminder_tags}" id="event_reminder_tags" name="event_reminder_tags" class="full textinput" />
              </td>
            </tr>
            <tr>
              <th>
                <label><?php echo $this->translate('event_reminder_attend_datetime');?></label>
              </th>
              <td>
              <input class="event_reminder_is_match_event_begin_datetime" type="checkbox" name="event_reminder_is_match_event_begin_datetime" {{if reminder_is_match_event_begin_datetime == 1 || $item.isSetAttendDateTime()==false }}checked="checked"{{/if}} class="event_reminder_is_match_event_begin_datetime" id="event_reminder_is_match_event_begin_datetime"/>
                <label for="event_reminder_is_match_event_begin_datetime"><?php echo $this->translate('Match event begin datetime');?></label>
              <input type="text" class="date_input event_reminder_attend_date" value="${$item.getAttendDate()}" />
              <input type="text" class="timepicker event_reminder_attend_time" value="${$item.getAttendTime()}"/>
              <input type="hidden" name="event_reminder_attend_datetime" class="event_reminder_attend_datetime" value="">
              <input type="hidden" class="event_reminder_event_begin_datetime" value="${begin_datetime}">
              </td> 
            </tr>
            <tr>
              <th><?php echo $this->translate('event_reminder_options');?>
              </th>
              <td>
                <?php 
                  $sources = array('email', 'popup', 'mobile');
                  foreach($sources as $source){
                ?>
                <input {{if reminder_has_<?php echo $source ?>_alarm}}checked="checked"{{/if}} value="<?php echo $source ?>" class="event_reminder_has_alarm" type="checkbox" name="event_reminder_has_<?php echo $source ?>_alarm" id="event_reminder_has_<?php echo $source ?>_alarm">
                <label for="event_reminder_has_<?php echo $source ?>_alarm"><?php echo $this->translate($source);?></label>
                <input value="${reminder_<?php echo $source ?>_alarm_time}" type="text" id="event_reminder_<?php echo $source ?>_alarm_time" name="event_reminder_<?php echo $source ?>_alarm_time" class="numberinput event_reminder_alarm_time" />
                <select id="event_reminder_<?php echo $source ?>_alarm_time_unit" name="event_reminder_<?php echo $source ?>_alarm_time_unit" class="event_reminder_alarm_time_unit">
                  <option value="minutes" {{if reminder_<?php echo $source ?>_alarm_time_unit}}{{if reminder_<?php echo $source ?>_alarm_time_unit == 'minutes'}}selected="selected"{{/if}}{{/if}}><?php echo $this->translate('minutes');?></option>
                  <option value="hours" {{if reminder_<?php echo $source ?>_alarm_time_unit}}{{if reminder_<?php echo $source ?>_alarm_time_unit == 'hours'}}selected="selected"{{/if}}{{/if}}><?php echo $this->translate('hours');?></option>
                  <option value="days" {{if reminder_<?php echo $source ?>_alarm_time_unit}}{{if reminder_<?php echo $source ?>_alarm_time_unit == 'days'}}selected="selected"{{/if}}{{/if}}><?php echo $this->translate('days');?></option>
                  <option value="weeks" {{if reminder_<?php echo $source ?>_alarm_time_unit}}{{if reminder_<?php echo $source ?>_alarm_time_unit == 'weeks'}}selected="selected"{{/if}}{{/if}}><?php echo $this->translate('weeks');?></option>
                </select>
                <div id="<?php echo $source ?>_reminder_desc" class="reminder_desc"></div>
                <br />
                <?php 
                  }
                ?>
              </td>
            </tr>
            <tr>
              <th>
              </th>
              <td>
                <div class="save_status" style="float:none;">
                  <span class="saving"><?php echo $this->translate('Saving...')?></span>
                  <span class="saved"><?php echo $this->translate('Saved')?></span>
                </div>
              </td>
            </tr>
            <tr>
              <th>
              </th>
              <td>
                <input type="submit" value="<?php echo $this->translate('event_reminder_save');?>" class="save" id="event_reminder_save" />
                <input type="button" value="<?php echo $this->translate('event_reminder_close');?>" class="close" id="event_reminder_close" />
              </td>
            </tr>
          </tbody>
        </table> 
    </form>
</script>