<?php 
if (isset($this->name)){
  $options=array(
      array(
        'title'=>'Public',
        'value'=>0
      ),
      array(
        'title'=>'Friends',
        'value'=>1
      ),
      array(
        'title'=>'Only Me',
        'value'=>2
      )
    )
?>
<select name="<?php echo $this->name ?>" class="smallSel small_gap1">
  <?php
  foreach($options as $option){
  ?>
    <option value="<?php echo $option['value']?>" <?php if ($this->value==$option['value']){?>selected="selected"<?php }?>><?php echo $this->translate($option['title'])?></option>

  <?php
  }
 } ?>
</select>