<script id="confirm_location_remove" type="text/x-jquery-tmpl">
    <div class="pop_form">
        <p>
            Clicking yes will make the current selection your new system
            default location. Seriously, have you thought this through?
        </p>
        <div class="p_field">
            <select class="reveal">
                <option>Reveal</option>
            </select>
        </div>
        <div class="p_field">
            <a href="#morebox" class="form_more leanModal2">more</a>
            <a href="#" class="button green confirm_close"><img src="images/tick.png" alt="yes" />Yes, do it now!</a>
            <a href="#" class="button red confirm_close"><img src="images/cross.png" alt="no" />No, I'm insane!</a>
        </div>
    </div>
</script>