<script id="manage_location" type="text/x-jquery-tmpl">
   <div class="watcher_form">
        <table border="" class="main_table">
            <tr>
                <td>Nossa Senhora do Carmo, Macau</td>
                <td><img src="images/location_img1.gif" alt="Location"></td>
                <td><a class="confirm_location_remove" href="#">remove</a></td>
            </tr>
            <tr>
                <td>Kudanminami, Chiyoda, Tokyo 102-8305, J</td>
                <td><img src="images/location_img1.gif" alt="Location"></td>
                <td><a class="confirm_location_remove" href="#">remove</a></td>
            </tr>
        </table>
        <div class="btn_set">
                <input type="submit" value="Save"  class="submit1" />
                <input type="submit" value="Cancel" class="submit2" />
        </div>
    </div>
</script>