<script id="save_location" type="text/x-jquery-tmpl">
    <div class="watcher_form">
        <form>
        <input class="location_name" type="text" value="" />
        <div class="clr"></div>
        <div class="btn_set">
            <input type="submit" value="Save" class="submit1" />
            <input type="submit" value="Cancel" class="submit2 close_window" />
        </div>
        </form>
    </div>
</script>