<script id="sidebar_event_detail_popup_item" type="text/x-jquery-tmpl">
    <form>
  <div id="mainEventWatcher1">
  <section class="watcher_event">
      <h6 class="head4">British Asparagus Festival</h6>
      <header class="tag_top taggap clearfix">
        <ul>
          <li><a href="#"><strong>Music &amp; Dance</strong></a></li>
          <li>|</li>
          <li>start: Dec 23, 2012</li>
          <li>|</li>
          <li>place: <a href="#">Grand City Hall</a></li>
        </ul>
      </header>
      <article class="event_details clearfix">
          <img src="images/event1.jpg" alt=" " class="event_img" />
          <div class="event_con">
              <p>Asparagus is so well-loved by the residents of the Vale of Evesham that they dedicate a festival to it. Events at the British Asparagus Festival include a party, tastings, auctions and educational events for vegetable-lovers.</p>
          </div>
      </article>
  </section>
  <section class="watcher_details watch_bor watch_color">
      <h6 class="nonselect headgap watcheDetail" data-target="1">Watcher Detail</h6>
      <section id="watcherDetailForm1" class="eventWatcherDetails">
          <div class="watcher_form gap_top">
          
              <ul>
                  <li><input type="text" value="Enter a brief watcher title here" class="txt" /></li>
                  <li><textarea rows="5" class="txt">Enter your event watcher detail here</textarea></li>
                  <li><label>Remind Time</label><input type="text" value="2012-4-4" class="d_input" /><input type="text" value="9:20" class="t_input" /><a href="#"><img src="images/alarm_bg.png" alt="alarm" height="21" /></a></li>
              </ul>
          </div>
          <div class="watcher_form watch_bor watcher_form_gap">
              <ul>
                  <li><label class="tag_label">Tag</label><select><option>Select a group</option></select></li>
                  <li><section class="tag_l"><strong>Tags:</strong> <a href="#">Tag1</a> | <a href="#">Taaag1</a> | <a href="#">Taaaaag1</a> | <a href="#">Taaaag1</a> | <a href="#">Taaaaag1</a> | <a href="#">Taaag1</a> | <a href="#">Tagaa1</a> | <a href="#">Taaaaag1</a> | <a href="#">Tag1</a> | <a href="#">Tagaggg1</a> | <a href="#">Tagsaggg1</a></section></li>
                  <li><textarea rows="5" class="txt">Enter new tags here and separate them with commas</textarea></li>
                  <li class="none">
                  <input type="submit" value="Save" data-target="1" class="submit1 eventSave" />
                  <input type="submit" value="Cancel" data-target="1"  class="submit2 eventCancel" />
                  </li>
              </ul>
          </div>
      </section>
    <section id="watcherDetailEdit1">
          <div class="watcher_form gap_top">
              <ul>
                  <li><strong>veggie produce info</strong></li>
                  <li>email to contact local agent, get Johnson to help sourcing 3 suppliers min.</li>
                  <li><strong>Watcher Alert </strong>: 2012-4-4, 9:20<a class="watcherAlert" data-target="1"><img src="images/alarm_bg.png" alt="alarm" height="21" class="right" /></a></li>
              </ul>
          </div>
          
      </section>
  </section>
  <div class="watcher_form watcher_tag watch_bor">
              <ul>
                  <li>
                  <section class="tag_l"><strong>Tags:</strong> <a href="#">biz</a> | <a href="#">agriculture</a> | <a href="#">first-contact</a> | <a href="#">england</a></section>
                  </li>
                  <li class="none"><input type="submit" value="Edit" data-target="1" class="submit1 eventEdit" /></li>
              </ul>
          </div>
  </div>
  
  <section class="event_remember" id="eventRemender1">
      <h6 class="head4">Event Reminder <img src="images/alarm_bg.png" alt="alarm" height="16" class="right_gap" /></h6>
      <div class="watcher_form">
        <ul>
            <li><strong>British Asparagus Festival</strong></li>
              <li>Event Start Date <a href="#">Dec 23, 2015</a></li>
              <li>Event Start Time</li>
          </ul>
      </div>
      <div class="watcher_form watcher_form_gap watch_bor">
        <ul>
            <li><strong>Notification via:</strong></li>
            <li><input name="sitealerts" type="checkbox" onclick="$(this).is(':checked') && $('#rememberDate1').slideDown('slow') || $('#rememberDate1').slideUp('slow');" /><label class="site_alert">Site alerts</label></li>
              <li style="display:none;" id="rememberDate1">
                <div class="remember_date">
                    <label>Remind Date / Time</label>
                      <input type="text" value="2012-12-31" class="r_d" /><input type="text" value="12:00" class="r_t" />
                  </div>
                  <div class="remember_date">
                    <label>Alert Interval</label>
                      <input type="text" value="2" class="r_t" style="width:20px;" /><input type="text" value="Hours" class="r_t" />
                  </div>
                  <div class="remember_date">
                    <label>Repeat</label>
                      <input type="text" value="3" class="r_t" />
                  </div>
                  <div class="remember_date">
                    <label>&nbsp;</label>
                      <input type="submit" class="submit1 btngap" value="Cancel Alerts" />
                  </div>
              </li>
              <li><input type="checkbox" name="mobilepush"  onclick="$(this).is(':checked') && $('#rememberDate2').slideDown('slow') || $('#rememberDate2').slideUp('slow');" />
              <label class="site_alert">Mobile push</label>
              </li>
              <li style="display:none;" id="rememberDate2" >
                <div class="remember_date" >
                    <label>Remind Date / Time</label>
                      <input type="text" value="2012-12-31" class="r_d" /><input type="text" value="12:00" class="r_t" />
                  </div>
                  <div class="remember_date">
                    <label>Alert Interval</label>
                      <input type="text" value="2" class="r_t" style="width:20px;" /><input type="text" value="Hours" class="r_t" />
                  </div>
                  <div class="remember_date">
                    <label>Repeat</label>
                      <input type="text" value="3" class="r_t" />
                  </div>
                  <div class="remember_date">
                    <label>&nbsp;</label>
                      <input type="submit" class="submit1 btngap" value="Cancel Alerts" />
                  </div>
              </li>
              <li><input type="checkbox" /><label class="site_alert">Email</label></li>
              <li class="none"><input type="submit" value="Save" data-target="1" class="submit1 alertSave" /><input type="submit" data-target="1" value="Cancel" class="submit2 alertCancel" /></li>
          </ul>
      </div>
  </section>
  </form>
</script>