<p><?php echo $this->translate('Hi')?> <?php echo $this->template_vars->display_name ?>,</p>

<p>Please click the link below to activate your account:</p>

<p>
<a href="<?php echo $this->serverUrl() . $this->baseUrl('auth/signup/confirm?code='. $this->template_vars->code)?>">
    <?php echo $this->serverUrl() . $this->baseUrl('auth/signup/confirm?code='. $this->template_vars->code)?>
</a>
</p>

<p>
Regards,<br />
Your Tagbees Team
</p>