<p><?php echo $this->translate('Hi')?> <?php echo $this->template_vars->display_name ?>,</p>

<p>Please click the link below to activate your account in the next 24 hours:</p>

<p>
<a href="<?php echo $this->serverUrl() . $this->baseUrl('auth/signup/confirm?code='. $this->template_vars->code)?>">
    <?php echo $this->serverUrl() . $this->baseUrl('auth/signup/confirm?code='. $this->template_vars->code)?>
</a>
</p>
<p>Please be noted, if you haven't activate your account within the next 24 hours, your account will be permanently deleted.</p>
<p>If that was not you registering, please ignore this email.</p>
<p>
Regards,<br />
Your Tagbees Team
</p>