<p><?php echo $this->translate('Welcome')?> <?php echo $this->template_vars->display_name ?>,</p>

<p>You just confirmed your account in Tagbees, here are some highlighting features that you can utitilize in our site:<br />
<ul>
    <li>Comprehensive Public Events
        <br />You can organise or join any kinds of public events</li>
    <li>Advanced Filtering to match your interest</li>
    <li>Mobile Exploration</li>
    <li>Bonus System</li>
    <li>and many more...</li>
</ul>
</p>
<p>Explore yourself and find out more on <a href="<?php echo $this->serverUrl(); ?>">Tagbees</a></p>

<p>
Regards,<br />
Your Tagbees Team
</p>