<p><?php echo $this->translate('Hi')?> <?php echo $this->template_vars->display_name ?>,</p>

<p>You just requested to reset your password to get access to Tagbees. The link will expire after 24 Hours:</p>

<p>
<a href="<?php echo $this->serverUrl() . $this->baseUrl('auth/reset_password?code='. $this->template_vars->code.'&email='.$this->template_vars->email)?>">
    <?php echo $this->serverUrl() . $this->baseUrl('auth/reset_password?code='. $this->template_vars->code.'&email='.$this->template_vars->email)?>
</a>
</p>

<p>
Regards,<br />
Your Tagbees Team
</p>