<script id="loginned_popup" type="text/x-jquery-tmpl">
    <div class="loginned_popup_inner">
        <div class="img_outer"><img src="images/image.jpg" alt="Proficient Member"></div>
        <div class="info">
            <div class="info_inner">
              <h3>Proficient Member</h3>
              <p>Join: 2010-7-18<br />
                Residence: Moon<br />
                Posts : Very regular<br />
                Role: Publisher</p>
            </div>
        </div>
        <div class="clearfix"> </div>
        <div class="pro-bottom"> 
            <a href="<?php echo $this->baseUrl('settings');?>">Settings</a><br />
            <a href="<?php echo $this->baseUrl('auth/logout');?>" class="logout"><strong>Logout</strong></a>
        </div>
      </div>
</script>