
        <nav class="breadcrumb clearfix">
        <ul>
        <li>You are here:</li>
        <li><a href="#">Home</a> &gt;</li>
        <li><strong>Apps</strong></li>
        </ul>
        </nav>
        <article class="main shadow">
          <div class="tag_con">
            <h1>Description</h1>
            <p>Glycolic Acid has the ability to penetrate the epidermal and dermal tissues, increasing the skin's moisture level which improves the overall facial complexion. It also removes dead keratin cells and decreases the corneous layer, making the skin looks younger and radiant. The use of products containing Glycolic Acid during young age helps to retain the skin's elasticity more effectively throughout the aging process. Thanks to the special formula, the B.M. Glycolic products penetrate the corneous layers of the skin, aiding the removal of impurities gently and gradually so that the moisturized new cells below are able to surface freely as they do in younger skins.</p>
            <div class="download">
              <ul>
                <li><span class="down-txt">Download</span></li>
                <li><a href="#">Android Phone</a></li>
                <li><a href="#">iPhone</a></li>
              </ul>
            </div>
            <p><img src="images/app.gif" alt="apps" /> </p>
            <h2>Features</h2>
            <div class="list tag_list">
              <ul>
                <li>Features 121 Features 121 Features 121 Features 121 Features 121</li>
                <li>Features 122 Features 122 Features 122 Features 122 Features 122 Features 122 Features 122</li>
                <li>Features 123 Features 123 Features 123 Features 123 Features 123 Features 123 Features 123 Features 123 Features 123</li>
                <li>Features 124</li>
                <li>Features 125 Features 125 Features 125 Features 125 Features 125</li>
              </ul>
            </div>
            <h2>Customer Reviews</h2>
            <p>ix it</p>
            <p>by Tjuras</p>
            <p>And this review goes to 5 stars. I used to love this app until they updated a few months back. Takes forever to load and sometime never does. It sure does load the ads at the bottom though! very frustrating because it seems like a quick fix. Sadly I have to get my tech news elsewhere.<br />
              Wait, wait, wait</p>
            <p>by Andy Whitaker<br />
              Content never loaded. Bummer<br />
              great site, terrible app</p>
          </div>
        </article>
