<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<?php //echo '<pre>';var_dump($this->item);echo '</pre>';?>

<div class="main shadow">
  <div class="feeds_and_more">
    <div class="feeds event_detail"></div>
  </div>
</div>
<?php /*
<div class="social_media clearfix">
    <div class="share">
        <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style ">
            <a class="addthis_counter addthis_pill_style"></a>
        </div>
        <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-504d9e426d8fd861"></script>
        <!-- AddThis Button END -->
    </div>
</div>
 */?>
<?php echo $this -> partial('js/event.phtml', array('item'=>$this->item)) ?>
<script type="text/javascript">
jQuery(function($){
  var tag_slug_names ='<?php echo $this->item->tag_slug_names?>'.split(',');
  var tag_names ='<?php echo $this->item->tag_names?>'.split(',');
  var tag_types ='<?php echo $this->item->tag_types?>'.split(',');
  $('.tag_html').html(ns_feeds.getTagHTML(tag_slug_names, tag_names, tag_types));
  //console.log(<?php echo json_encode($this->array_result) ?>)
  //console.log(<?php echo json_encode($this->item) ?>)
  ns_feeds.render(<?php echo json_encode($this->array_result) ?>, false, 'tmpl_event_detail', ns_event_detail.tmpl_functions);
  /*var popup_content = ns_feeds.getHTML(<?php echo json_encode($this->array_result) ?>, 'bookmark_popup', ns_common_bookmark_popup.tmpl_functions);
  $('body').append(popup_content);*/
  ns_event_detail.init();
})
</script>