<script type="text/javascript">
   jQuery(function($){
        $('body').on('click','.language ul ul li',function(){
            $.ajax({
              type: "POST",
              url: "<?php echo $this->baseUrl('ajax/language/switch') ?>",
                data: {
                    display_lang:$(this).find('input').val()
                },
              success: function(msg){
                if(msg['result']==true){
                    window.location.hash = ''; //if you want to reload with an empty hash
                    window.location.reload(true); //reload the page and bypass the cache
                    window.location.replace($(location).attr('href'));
                }else{
                    alert('Unkown error occured. Please try again later.')
                }
                },
                dataType:'json'
            });
            return false;
        })
        $('.login').qtip({
            content: {
                text: '<p style="text-align:center;"><img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." /></p>',
                ajax: {
                    url: '<?php echo $this->baseUrl('ajax/auth/open_login_box')?>',
                    success: function(data, status) {
                        if (data.result == 'false'){
                            this.set('content.text', 'already loginned!');
                        } else {
                            this.set('content.text', $( "#login" ).tmpl(data.data));
                        }
                        $('input.username').watermark("<?php echo $this->translate('Username') ?>");
                        $('input.password').watermark("<?php echo $this->translate('Password') ?>");
                    },
                    once: true,
                    loading: true
                },
                title: {
                    text: 'Login'
                }
            },
            show: {
                event: 'click',
                modal: {
                    on: true
                }
            },
            position: {
                my: 'center',
                at: 'center',
                target: $(window)
            },
            style: {
                def:false,
                classes: 'qtip-light qtip-rounded login_dialog'
            }
        });
        
        $('body').on('click', '.watcher_icon' , function() {
            $(this).qtip(
            {
                //overwrite: false, 
                content: {
                    text: '<img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." />',
                    ajax: {
                        url: '<?php echo $this->baseUrl('ajax/bookmark/open_box_trigger')?>', 
                        success: function(data, status) {
                            this.set('content.text', $( "#movieTemplate" ).tmpl());
                        }
                    },
                    title: {
                        text: 'Bookmark details'
                    }
                },
                position: {
                    at: 'bottom center', 
                    my: 'top right',
                    target: $(this)
                },
                show: {
                     ready: true
                },
                style: {
                    def:false,
                    classes: 'qtip-light bookmark_box_trigger qtip-shadow'
                }
            })
        })
        $('input.username').watermark("<?php echo $this->translate('Username') ?>");
        $('input.password').watermark("<?php echo $this->translate('Password') ?>");
        $('input.keyword_text').watermark("<?php echo $this->translate('Enter keyword...') ?>");
        $('.loc_right input').watermark("<?php echo $this->translate('Enter a location...') ?>");
        
        //$.datepicker.setDefaults($.datepicker.regional['zh-HK']);
        
       /*$("select.selectBoxIt").selectBoxIt({
          showEffect: "fadeIn",
          showEffectSpeed: 100,
          hideEffect: "fadeOut",
          hideEffectSpeed: 100
       });*/
        //from form data to object
        $.fn.serializeObject = function()
        {
            var o = {};
            var a = this.serializeArray();
            $.each(a, function() {
                if (o[this.name] !== undefined) {
                    if (!o[this.name].push) {
                        o[this.name] = [o[this.name]];
                    }
                    o[this.name].push(this.value || '');
                } else {
                    o[this.name] = this.value || '';
                }
            });
            return o;
        };
      });
      
      //common functions
        // to check the size of asso. array
        Object.size = function(obj) {
            var size = 0, key;
            for (key in obj) {
                if (obj.hasOwnProperty(key)) size++;
            }
            return size;
        };
        
        function mysqlTimeStampToDate(timestamp) {
            //function parses mysql datetime string and returns javascript Date object
            //input has to be in this format: 2007-06-05 15:26:02
            var regex=/^([0-9]{2,4})-([0-1][0-9])-([0-3][0-9]) (?:([0-2][0-9]):([0-5][0-9]):([0-5][0-9]))?$/;
            var parts=timestamp.replace(regex,"$1 $2 $3 $4 $5 $6").split(' ');
            return new Date(parts[0],parts[1]-1,parts[2],parts[3],parts[4],parts[5]);
        }
        
        function scrollToAnchor(aid){
           var aTag = $("a[name='"+ aid.replace('#','') +"']");
           $('html,body').animate({scrollTop: aTag.offset().top},'slow');
        }
        
        function getURLParameterValue(name) {
            return decodeURI(
                (RegExp(name + '=' + '(.+?)(&|$)').exec(location.search)||[,''])[1]
            );
        }
        
        function showFlashMessages(content){
            //if (jQuery(".flash_message").is(':visible'))
            //  jQuery(".flash_message").hide();
            jQuery( "#flash_message_tmpl" ).tmpl( content ).appendTo( ".flash_messages" );
            jQuery(".flash_messages").fadeIn(300).delay(5000).fadeOut(300, function(){
                $(this).empty();
            });
        }
        function getFlashMessageType(data){
            if (typeof data == 'object'){
                for (x in data){
                    return x;
                }
            }
            return 'default';
        }
        function getFlashMessageHtml(data){
            if (typeof data == 'object'){
                for (x in data){
                    return data[x];
                }
            }
            return data;
        }
        
        
        function isNumber(n) {
          return !isNaN(parseFloat(n)) && isFinite(n);
        }
        
        
        /*
         * array or list item suffle 
         * Example 1: shuffle an unordered list
            $('ul').shuffle();
            
            Example 2: shuffle an array
            var arr = [1,2,3,4,5,6];
            arr = $.shuffle(arr);
         */
        (function($){
          $.fn.shuffle = function() {
            return this.each(function(){
              var items = $(this).children();
              return (items.length)
                ? $(this).html($.shuffle(items))
                : this;
            });
          }
         
          $.shuffle = function(arr) {
            for(
              var j, x, i = arr.length; i;
              j = parseInt(Math.random() * i),
              x = arr[--i], arr[i] = arr[j], arr[j] = x
            );
            return arr;
          }
        })(jQuery);
        
        
        
        function getNow () {
          var currentDate = new Date()
          var day = currentDate.getDate()
          var month = currentDate.getMonth() + 1
          var year = currentDate.getFullYear()
          var hours = currentDate.getHours()
          var minutes = currentDate.getMinutes()
          var seconds = currentDate.getSeconds()
            if (minutes < 10)  minutes = "0" + minutes
            if (seconds < 10)  seconds = "0" + seconds
           return year+ "-" + month + "-" + day  + " "+ hours + ":" + minutes +":" + seconds + " ";
        }
        
        
        
        function goToByScroll(id){
                $('html,body').animate({scrollTop: $("#"+id).offset().top},'slow');
        }
        
        /*
         * clone object by jQuery.extend (deep copy)
         * @param: source / 來源物件
         * @param: append / 附加的值 (非必要)
         */
        function clone (source, append) {
          if ('undefined' !== typeof append) {
            var obj = jQuery.extend({}, source);
            return jQuery.extend(true, obj, append);
          } else {
            return jQuery.extend(true, {}, source);
          }
        }
        //RETURN KEYS OF AN OBJECT
        $.extend({
            keys:    function(obj){
                var a = [];
                $.each(obj, function(k){ a.push(k) });
                return a;
            }
        })

</script>
<?php echo $this->partial('js/template/auth/login.phtml')?>
<?php echo $this->partial('js/template/bookmark/box_trigger.phtml')?>