<script type="text/javascript">
    jQuery(function($) {
        // Dialog Link
        jQuery('.upload_link').click(function() {
            jQuery('#dialog').dialog('open');
            return false;
        });

        //hover states on the static widgets
        jQuery('.upload_link, ul#icons li').hover(function() {
            jQuery(this).addClass('ui-state-hover');
        }, function() {
            jQuery(this).removeClass('ui-state-hover');
        });
    }); 
</script>
