<script type="text/javascript">
var ns_event_detail = {
  init: function(){
    // Dialog Link
    jQuery('.upload_link').click(function() {
    <?php if (Zend_Auth::getInstance()->hasIdentity() && Common::getSession()->user != null) { ?>
        jQuery( '#dialog iframe' ).attr( 'src', 'http://atticho.no-ip.biz/tagbees_refactored/iframe/event/img_upload_form?event_id=<?php echo $this->event_id ?>')
        jQuery('#dialog')
          .dialog({
            modal: true,
            width:'900',
            height: $(window).height() - 50,
            buttons: {
              'Close': function(){ 
                $(this).dialog('close'); 
              } 
            }
          })
          .dialog('open');
    <? } else { ?>
      alert('Please login to add images.');
    <?php } ?>
        return false;
    });
    //hover states on the static widgets
    jQuery('.upload_link, ul#icons li').hover(function() {
        jQuery(this).addClass('ui-state-hover');
    }, function() {
        jQuery(this).removeClass('ui-state-hover');
    });
    
    
    jQuery(".event_detail .main_details .place a")
        .dotdotdot({
                wrap : 'word',
                height: 16
    });
    
    jQuery('#qr1').uQr({
        create : true,
        type : 'Tagbees.com',
        text : 'tag'
    });
    
    var mapDiv = document.getElementById('event-map');
      map = new google.maps.Map(mapDiv, {
        center: new google.maps.LatLng(<?php echo $this->place_lat?>, <?php echo $this->place_lng?>),
        zoom: 13,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      });
    
    var marker = new google.maps.Marker({
      map: map, position: new google.maps.LatLng(<?php echo $this->place_lat?>, <?php echo $this->place_lng?>)
    });
  }
}
</script>
