<script type="text/javascript">
var ns_event_detail = {
  optional_fields:{
    'event_datetime':'event_datetime_note',
    'event_application_datetime':'event_application_datetime_note',
    'event_place_datetime':'event_place_datetime_note',
    'event_price':'event_price_note',
    'event_place':'event_traffic_note'
    <?php /*'event_organiser':'event_organiser_name',
    'event_organiser':'event_organiser_tel',
    'event_organiser':'event_organiser_email',
    'event_organiser':'event_organiser_website',
    'event_organiser':'event_organiser_detail'*/?>
  },
  init: function(){
    // Dialog Link
    jQuery('.upload_link').click(function() {
    <?php if (Zend_Auth::getInstance()->hasIdentity() && Common::getSession()->user != null) { ?>
        jQuery( '#dialog iframe' ).attr( 'src', '<?php echo Common::getSession()->baseUrl ?>/iframe/event/img_upload_form?event_id=<?php echo $this->item->id?>')
        jQuery('#dialog')
          .dialog({
            modal: true,
            width:'900',
            height: $(window).height() - 50,
            buttons: {
              'Close': function(){
                $(this).dialog('close'); 
                jQuery( '#dialog iframe' ).attr( 'src', '');
                console.log($('#dialog iframe').get(0).contentWindow.ns_iframe_event_image_upload.change_flag);
                if ($('#dialog iframe').get(0).contentWindow.ns_iframe_event_image_upload.num_of_uploaded==0){
                  $( 'iframe.img_gallery' ).attr( 'height', '0');
                }else{
                  if ($('#dialog iframe').get(0).contentWindow.ns_iframe_event_image_upload.change_flag == true)
                    jQuery( 'iframe.img_gallery' ).attr( 'src', function ( i, val ) { return val; });
                  $( 'iframe.img_gallery' ).attr( 'height', '380');
                }
              } 
            }
          })
          .dialog('open');
    <? } else { ?>
      alert('Please login to add images.');
    <?php } ?>
        return false;
    });
    //hover states on the static widgets
    jQuery('.upload_link, ul#icons li').hover(function() {
        jQuery(this).addClass('ui-state-hover');
    }, function() {
        jQuery(this).removeClass('ui-state-hover');
    });
    
    if (jQuery(".event_detail .main_details .place a").length){
      jQuery(".event_detail .main_details .place a")
          .dotdotdot({
            wrap : 'word',
            height: 16
      });
    }
    if (jQuery(".event_detail .main_details td.content").length){
      jQuery(".event_detail .main_details td.content.shortened")
          .dotdotdot({
            wrap : 'word',
            height: 19
      });
    }
    
    jQuery('#qr1').uQr({
        create : true,
        type : 'Tagbees.com',
        text : 'tag'
    });
    <?php if (isset($this->item->place_lat) && isset($this->item->place_lng)){?>
    var mapDiv = document.getElementById('event-map');
      map = new google.maps.Map(mapDiv, {
        center: new google.maps.LatLng(<?php echo $this->item->place_lat?>, <?php echo $this->item->place_lng?>),
        zoom: 13,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      });
    
    var marker = new google.maps.Marker({
      map: map, position: new google.maps.LatLng(<?php echo $this->item->place_lat?>, <?php echo $this->item->place_lng?>)
    });
    <?php } ?>
    for (var key in this.optional_fields){
      if (jQuery('.'+this.optional_fields[key]).length){
        console.log(key +'has note!')
          jQuery('.'+key).readmore({
            speed: 75,
            maxHeight: 18,
            moreLink: '<a href="#" class="event_more_btn"><?php echo $this->translate('More...')?></a>',
            lessLink: '<a href="#" class="event_more_btn"><?php echo $this->translate('Less...')?></a>',
          });
      }
    }
    
  }
}
</script>
