<script type="text/javascript">

var maxDistance = <?php echo Zend_Registry::get('config')->filter->sys_para->max_distance ?>;
var minDistance = <?php echo Zend_Registry::get('config')->filter->sys_para->min_distance ?>;


// prepare to fetch new feed based on updated filter input
function updateFilterByChangedInput(selector){
    if (validateSidebarSearchInputs()){
         if (selector.is('.feed_filter_input[name="is_match_location"]')){
            jQuery( ".radius_amt span#filter_radius" ).text( jQuery( "#radius_slider" ).slider( "option", "value" ));
            if (jQuery('.feed_filter_input[name="is_match_location"]').is(':checked')){
                jQuery( ".match_location_set" ).css('display','block');
                $('#locate_somewhere').prop('disabled',false);
                initDistanceWidget();
            }else{
                jQuery( ".match_location_set" ).hide();
                $('#locate_somewhere').prop('disabled',true);
                distanceWidget.set('map', null);
            }
        } else if (selector.is('.feed_filter_input[name="is_show_map"]')) {
            <?php if (Zend_Registry::get('config_ini')->server->online==1){ ?>
                    $('#map-wrapper').toggle();
                    initMapAndAutoComplete();
                    return true;
            <?php } else { ?>
                var content = [{'debug' : '<?php echo $this->translate('Online mode is off. Please check application.ini to make sure server.online = 1') ?>'}] ;
                showFlashMessages(content);
            <?php } ?>
        }
    <?php if (! Zend_Auth::getInstance()->hasIdentity()) { ?>
        else if (selector.is('.feed_filter_input[name="is_match_interest"]')) {
            var content = [{'error' : '<?php echo $this->translate('To customise your own interest, please login first.') ?>'}] ;
            showFlashMessages(content);
            selector.prop('checked',false);
            return false;
        }
    <?php } ?>
    }
}

function updateSortByInput(value){
    $('.sort_by nav ul li').removeClass('current');
    $('.sort_by nav ul li[data-value="'+value+'"]').addClass('current');
    $('.feed_filter_input[name="sort_by"]').val(value);
}

jQuery(function($){
        $('.match_location_set .save_location').qtip({
        content: {
            text: '<p style="text-align:center;"><img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." /></p>',
            ajax: {
                url: '<?php echo $this->baseUrl('ajax/filter/open_save_location')?>',
                success: function(data, status) {
                    if (data.result == 'false'){
                        this.set('content.text', 'saved failed! Please try again later.');
                    } else {
                        this.set('content.text', $( "#save_location" ).tmpl());
                    }
                    $('input.location_name').watermark("<?php echo $this->translate('Type your saved location here...') ?>");
                }
            },
            title: {
                text: 'Save this Location'
            }
        },
        show: {
            event: 'click',
            modal: {
                on: true
            }
        },
        position: {
            my: 'center',
            at: 'center',
            target: $(window)
        },
        style: 'qtip-light qtip-rounded'
    });
    $('.match_location_set .manage_location').qtip({
        content: {
            text: '<div style="text-align:center"><img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." /></div>',
            ajax: {
                url: '<?php echo $this->baseUrl('ajax/filter/open_manage_location')?>',
                success: function(data, status) {
                    if (data.result == 'false'){
                        this.set('content.text', 'Error occured! Please try again later.');
                    } else {
                        this.set('content.text', $( "#manage_location" ).tmpl());
                    }
                }
            },
            title: {
                text: 'Manage Location'
            }
        },
        show: {
            event: 'click',
            modal: {
                on: true
            }
        },
        position: {
            my: 'center',
            at: 'center',
            target: $(window)
        },
        style: 'qtip-light qtip-rounded'
    });
    <?php /*$('.confirm_location_remove').qtip({
        content: {
            text: '<p style="text-align:center;"><img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." /></p>',
            ajax: {
                url: '<?php echo $this->baseUrl('ajax/filter/open_confirm_location_remove')?>',
                success: function(data, status) {
                    if (data.result == 'false'){
                        this.set('content.text', 'Error occured! Please try again later.');
                    } else {
                        this.set('content.text', $( "#confirm_location_remove" ).tmpl());
                    }
                }
            },
            title: {
                text: 'Confirm Location Deletion?'
            }
        },
        show: {
            event: 'click',
            modal: {
                on: true,
                effect: false
            }
        },
        position: {
            my: 'center',
            at: 'center',
            target: $(window)
        },
        style: {
            def:false,
            classes: 'qtip-light qtip-rounded'
        }
    }); <?php */ ?>
    $( "#radius_slider" ).slider({
        range: "min",
        //value:feed_para['radius'],
        step: 0.01,
        min: minDistance,
        max: maxDistance,
        slide: function( event, ui ) {
            $( ".radius_amt span#filter_radius" ).text( ui.value );
            
        },
        change: function( event, ui ) {
            /*$( ".radius_amt span#filter_radius" ).text( ui.value );
            if ($("#map").is(":visible")){
                distanceWidget.set('distance',ui.value);
                radiusWidget.bindTo('center', distanceWidget, 'position');
                map.fitBounds(radiusWidget.get('bounds'));
            }
          feed_para['radius'] = ui.value;
          updateUrlParam('radius', ui.value);
          refreshFeed();*/
        }
    });
    
    //checking match location...
    var checkMatchLocation = function(){
        if($("#is_match_location").attr("checked")=="checked")
        {
            $('.match_location_set').show();  
        }
        else
        {
            $('.match_location_set').hide();
        }
    }
    checkMatchLocation();
    $('body').on('change', '#is_match_location', function() {checkMatchLocation()});
    
    //show after all events are attached esp. pretty checkable takes effect...
    $('.filter_div').show();
    
    $('body').on('click','.sort_by nav ul li', function(){
        updateSortByInput($(this).data('value'));
        addChangedFeedInputName($('.feed_filter_input[name="sort_by"]'));
        if (validateSidebarSearchInputs()){
            for( key in changed_feed_input_names){
                updateVariableAndUrlParamFromFeedInput($('*[name="'+changed_feed_input_names[key]+'"]'));
            }
            refreshFeed('index');
        }
    }).on('change','.feed_filter_input[name="is_match_interest"]', function(){
        <?php /*if (empty($_SESSION['user'])) { ?>
            var content = [{'error' : '<?php echo $this->translate('To customise your own interest, please login first.') ?>'}] ;
            showFlashMessages(content);
            $(this).removeAttr('checked');
            console.log($(this).parent('.prettycheckbox').find('a'))
            var element = $(this).parent('.prettycheckbox').find('a');
            element.delay(1000).removeClass('checked');
        <?php }else{ ?>
            addChangedFeedInputName($('.feed_filter_input[name="is_match_interest"]'));
            if (validateSidebarSearchInputs()){
                for( key in changed_feed_input_names){
                    updateVariableAndUrlParamFromFeedInput($('*[name="'+changed_feed_input_names[key]+'"]'));
                }
                refreshFeed('index');
            }
        <?php }*/ ?>
    }).on('change','.feed_filter_input[name="is_match_location"]', function(){
        addChangedFeedInputName($('.feed_filter_input[name="is_match_location"]'));
        if (validateSidebarSearchInputs()){
            for( key in changed_feed_input_names){
                updateVariableAndUrlParamFromFeedInput($('*[name="'+changed_feed_input_names[key]+'"]'));
            }
            refreshFeed('index');
        }
    }).on('click','.showMap', function(){
        var input = $('.feed_filter_input[name="is_show_map"]')
        if(input.is(':checked')){
            input.removeProp('checked','checked');
        }else{
            input.prop('checked','checked');
        }
        addChangedFeedInputName($('.feed_filter_input[name="is_show_map"]'));
        if (validateSidebarSearchInputs()){
            for( key in changed_feed_input_names){
                updateVariableAndUrlParamFromFeedInput($('*[name="'+changed_feed_input_names[key]+'"]'));
            }
            refreshFeed('index');
        }
    })
    //when user clicks load more
    .on("click",'.more_div',function() {
        feed_para.last_id = $('.feeds > article:last').data("id");
        refreshFeed('index');
        return false;
    });
});

</script>
<?php if (Zend_Registry::get('config_ini')->server->online==1){
    echo $this->partial('js/filter/map.phtml');
} ?>
<?php echo $this->partial('js/template/filter/save_location.phtml')?>
<?php echo $this->partial('js/template/filter/manage_location.phtml')?>
<?php //echo $this->partial('js/template/filter/confirm_location_remove.phtml')?>