<script type="text/javascript">
var timezone =<?php echo $_SESSION['timezone_json'] ?>;
  var timezone_id = ''; 
<?php if (isset ($_SESSION['timezone_id'])){
if ($_SESSION['timezone_id']!=''){?>var timezone_id = '<?php echo $_SESSION['timezone_id'] ?>';<?php }else{ ?>var timezone_id = '';<?php }} ?>
  jQuery(function($) {
    /*$('#birthday').datepicker({
      dateFormat : 'yy-mm-dd'
    });
    //$('#birthday').datepicker("setDate", 'yy-mm-dd', today));
    */
    
    $('body').on('click', '.remove_social_network', function(){
      var elem = $(this);
      $.ajax({
          url: "<?php echo $this->baseUrl('ajax/settings/delete_social_connection') ?>",
          data: {
              'provider_id':$(this).data('provider-id'),
              'identifier':$(this).data('identifier'),
          },
          success: function(msg){
            if (msg['result']){
              location.reload(true);
            }else{
              alert('<?php echo $this->translate('unknown error occured, please try again.')?>');
            }
          }
      });
      return false;
   })
   
    //timezone js
    if (timezone_id != '') {
      for (var i = 1; i < timezone.length; i = i + 2) {
        var key = jQuery.inArray(timezone_id, timezone[i]);
        if (key != -1) {
          $('#country').val(timezone[i - 1]);
          changeCountry();
          $('#city').val(timezone[i][key]);
          break;
        }
      }
    } else {
      $('#country').val('HK');
      changeCountry();
    }
    $(document).on("change", "#country", function() {
      changeCountry();
    });
  })
  function changeCountry() {
    $('#city').empty();
    var key = jQuery.inArray($("#country").children('option:selected').val(), timezone);
    if (key != -1) {
      var i = 0;
      for ( i = 0; i < timezone[key + 1].length; i = i + 2) {
        $('#city').append('<option value="' + timezone[key+1][i] + '">' + timezone[key+1][i + 1] + '</option>');
      }
      $('#city').show();
    } else {
      $('#city').hide().prop('disabled', 'disabled');
    }
  }
</script>
<?php if (Zend_Registry::get('config_ini')->server->online==1){
    echo $this->partial('js/settings/map.phtml');
} ?>
<?php //echo $this->partial('js/template/filter/confirm_location_remove.phtml') ?>