<script type="text/javascript">
   jQuery(function($){
        $('.upload_user_thumbnail').qtip({
            content: {
                text: '<p style="text-align:center;"><img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." /></p>',
                ajax: {
                    url: '<?php echo $this->baseUrl('ajax/user/open_upload_thumbnail')?>',
                    success: function(data, status) {
                        if (data.result == 'false'){
                            this.set('content.text', 'saved failed! Please try again later.');
                        } else {
                            this.set('content.text', $( "#upload_user_thumbnail" ).tmpl());
                        }
                        $('.avatar_div li').click(function(){
                            $('.avatar_div li').removeClass('active')
                            $(this).toggleClass('active');
                        });
                    }
                },
                title: {
                    text: 'Upload User Thumbnail'
                }
            },
            show: {
                event: 'click',
                modal: {
                    on: true
                }
            },
            position: {
                my: 'center',
                at: 'center',
                target: $(window)
            },
            style: 'qtip-light qtip-rounded'
        });
        
        $('.tab_content').show();
        
        $('body')
            .on('click','.editable label',function(e){
                e.preventDefault();
                var parent = $(this).parents('.editable');
                parent.data('prev_val',$(this).text());
                parent.empty().append('<input type="text" value="'+$(this).text()+'"/> <a class="save_interest_order" href="#"><img width="15" src="<?php echo $this->baseUrl('images/tick.jpg')?>" /></a> <a class="cancel_interest_order" href="#"><img width="15" src="<?php echo $this->baseUrl('images/close.png')?>" /></a><br /><a href="#" class="sorting_toggle">switch to auto</a>');
            })
            .on('click','.editable .save_interest_order',function(e){
                e.preventDefault();
                var parent = $(this).parents('.editable');
                var value = parent.find('input').val();
                if (Number(value) > 0) {
                    parent.empty().append('<label>'+Number(value)+'</label>');
                } else {
                    alert('enter the correct positive value please.');
                }
                
            })
            .on('click','.editable .cancel_interest_order',function(e){
                e.preventDefault();
                var parent = $(this).parents('.editable');
                parent.empty().append('<label>'+parent.data('prev_val')+'</label>');
            })
        
    });
</script>
<?php echo $this->partial('js/template/user/upload_thumbnail.phtml') ?>