<script type="text/javascript">
    jQuery(function($){
      ns_feeds.refresh('search');
    });
</script>
<?php echo $this -> partial('js/feeds/index_events.phtml'); ?>

<?php //echo $this->partial('breadcrumbs.phtml'); ?>
<article class="main shadow">
    <?php echo $this -> partial('partials/filter.phtml'); ?>

    <div class="feeds_and_more">
        <div class="feeds index"></div>
        <div class="load_more_feeds">
            <a style="display:none;" class="more" href="#"> More &gt; </a>
            <img style="display:none;" class="loading" alt="loading..." src="<?php echo $this->baseUrl('images/ajax-loader.gif') ?>" />
        </div>
    </div>

</article>

