<?php echo $this->partial('breadcrumbs.phtml'); ?>
<?php echo $this -> partial('js/user.phtml'); ?>
        <article class="main div_shadow">
        <?php echo $this -> partial('partials/user/profile.phtml', array('active_tab'=>'bookmarks','user'=>$this->user)); ?>
          <section class="tab_container">
            <section id="mybookmark" class="tab_content">
              <h1 class="heading1">My Watchlist</h1>
              <table class="tag_table">
                <tr>
                  <th style="width:15%"><select class="all">
                      <option>All</option>
                    </select></th>
                  <th style="width:15%"><select class="t_time">
                      <option>All Time</option>
                    </select></th>
                  <th style="width:25%" class="td_th_align_left">Event</th>
                  <th style="width:45%" class="td_th_align_left">Tags</th>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">5 days ago</td>
                  <td><a href="event.php" class="dblink">Monumenta</a></td>
                  <td>activities,aims,alive,annual,area,arts,based,bristol,car<a href="#" data-link="event_tag_more.php">...</a>                 
                  </td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">5 days ago</td>
                  <td><a href="event.php" class="dblink">Letterature</a></td>
                  <td>children,city,closed,community,contact,council,create,</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">6 days ago</td>
                  <td><a href="event.php" class="dblink">British Asparagus F...</a></td>
                  <td>credits,culture,dance,days,develop,events,excluded,</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">7 days ago</td>
                  <td><a href="event.php" class="dblink">Friday Market</a></td>
                  <td>footsteps,free,games,held,home,join-in,london,meet,</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">7 days ago</td>
                  <td><a href="event.php" class="dblink">San Pellegrino Cook...</a></td>
                  <td>night,options,partnership,people,photos,positive,</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">9 days ago</td>
                  <td><a href="event.php" class="dblink">Midsummer Cel...</a></td>
                  <td>promotions,resulted,services,streets,successfully...</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">9 days ago</td>
                  <td><a href="event.php" class="dblink">Sydney Good Food</a></td>
                  <td>traffic,traffic-free,transport,travel,used,wide,</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">11 days ago</td>
                  <td><a href="event.php" class="dblink">Rally del Salento</a></td>
                  <td>adults,alive,around,attitudes,behind,centre,chance</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">12 days ago</td>
                  <td><a href="event.php" class="dblink">Dragonboat Cup</a></td>
                  <td>change,children,community,contact,create,credits<a href="#">...</a></td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Private</td>
                  <td class="td_th_align_right">13 days ago</td>
                  <td><a href="event.php" class="dblink">Football Match</a></td>
                  <td>text,town,traffic,traffic-free,uk,visible,walk,young,</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">fb G1</td>
                  <td class="td_th_align_right">19 days ago</td>
                  <td><a href="event.php" class="dblink">Nancy BD</a></td>
                  <td>football,games,generations,give,home,links,london,<a href="#">...</a></td>
                </tr>
                <!--<tr>
                  <td colspan="4"><a href="#" class="more">More...</a></td>
                </tr> -->
              </table>
            </section>
          </section>
        </article>

<script type="text/javascript">
</script>