<?php echo $this->partial('breadcrumbs.phtml'); ?>
<?php echo $this -> partial('js/user.phtml'); ?>
<?php //echo '<pre>';var_dump($this->bookmarks);echo '</pre>';die(); ?>
        <div class="main shadow">
        <?php echo $this -> partial('partials/user/profile.phtml', array('active_tab'=>'bookmarks','user'=>$this->user)); ?>
          <div class="tab_container">
            <section id="user_bookmarks" data-id="<?php echo $this->user->id ?>" class="tab_content">
              <h1 class="heading1">Bookmarks</h1>
              <table class="tag_table">
                <tr>
                  <th style="width:15%"><select class="all">
                      <option>All</option>
                      <option>Public</option>
                      <option>Private</option>
                    </select></th>
                  <th style="width:55%" class="td_th_align_left">Event</th>
                  <th style="width:15%" class="td_th_align_left">Trend Score</th>
                  <th style="width:15%" class="td_th_align_left">Status</th>
                  <th style="width:15%">Last Updated</th>
                </tr> 
              </table>
            <div class="load_more_feeds">
                <a class="more" href="#"> More &gt; </a>
                <img style="display:none;" class="loading"  alt="loading..." src="<?php echo $this->baseUrl('images/ajax-loader.gif') ?>" />
            </div>
            </section>
          </div>
        </div>

<script type="text/javascript">
     var user_bookmarks = <?php echo json_encode($this->bookmarks) ?>;
     
     console.log(user_bookmarks);
    
    jQuery(function($){
        renderUserBookmarks(user_bookmarks);
    });
</script>
<?php echo $this->partial('js/feeds/user_bookmarks.phtml'); ?>