<?php echo $this -> partial('breadcrumbs.phtml'); ?>
<?php echo $this -> partial('js/user.phtml'); ?>
<div class="main shadow">
<?php echo $this -> partial('partials/user/profile.phtml', array('active_tab' => 'index', 'user' => $this -> user)); ?>
  <div class="main_inner">
    <section id="user_activities" class="tab_content" >
      <h1 class="heading1">Activities</h1>
      <div class="feeds_and_more">
        <div class="feeds user_logs"></div>
        <div class="load_more_feeds">
          <a style="display:none;" class="more" href="#"> More &gt; </a>
          <img style="display:none;" class="loading"  alt="loading..." src="<?php echo $this->baseUrl('images/ajax-loader.gif') ?>" />
        </div>
      </div>
    </section>
  </div>
</div>

<script type="text/javascript">
var user_logs = <?php echo json_encode($this->logs) ?>;
jQuery(function($){
    renderUserLogs(user_logs, false);
});
</script>
<?php echo $this -> partial('js/feeds/user_activities.phtml'); ?>