<?php echo $this->partial('breadcrumbs.phtml'); ?>
<?php echo $this -> partial('js/user.phtml'); ?>
        <article class="main div_shadow">
          <section class="mainevent">
            <h1><?php echo $this->username?></h1>
            <div class="myprofile profile_form clearfix">
              <div class="profileLeft">
                <div class="all_e_div"><img src="<?php echo $this->baseUrl('images/man.gif')?>" alt=""/></div>
                <a href="#" class="upload_user_thumbnail">Upload an image</a></div>
              <div class="profile_right">
                <div class="activity">
                  <div class="active_div"></div>
                  <div class="not_active"><a href="#">not active</a></div>
                </div>
                <div class="p-div">
                  <label>Name:</label>
                  <span class="profile_field">tagjoseph</span></div>
                <div class="p-div">
                  <label>Place of residence:</label>
                  <span class="profile_field">Moon</span></div>
                <div class="p-div">
                  <label>Posts habit:</label>
                  <span class="profile_field">Very regular</span></div>
                <div class="p-div">
                  <label >Membership:</label>
                  <span class="profile_field">Proficient</span></div>
                <div class="p-div">
                  <label >Role:</label>
                  <span class="profile_field">Publisher</span></div>
                <div class="p-div">
                  <label>Description:</label>
                </div>
                <p>The first Moon Country resident, jQuery provide an easy way to automatically seperate your information into generated hyper-linked pages, abit like a book with page numbers. The implementation can either be a) all data is loaded on 1 page and then the plugin evenly splits the data.</p>
              </div>
            </div>
          </section>
          <nav class="righttab">
            <ul class="tabs">
              <li><a href="#mypublish"><img src="<?php echo $this->baseUrl('images/icon12.png')?>" alt="Category" /></a></li>
              <li><a href="#myinterest"><img src="<?php echo $this->baseUrl('images/icon13.png')?>" alt="Category" /></a></li>
              <li><a href="#mywatchlist"><img src="<?php echo $this->baseUrl('images/icon14.png')?>" alt="Category" /></a></li>
            </ul>
          </nav>
          <section class="tab_container">
            <section id="mypublish" class="tab_content">
              <h1 class="heading1">Activities</h1>              
              
              <section class="post" id="more_updates">
                    <?php
                    echo $this -> partial('partials/feed.phtml', array(
                    //'feed'=>$this->feed,
                    //'category_tags'=>$this->category_tags
                    ));
                    ?>
                    <div class="more" id="morebutton" >
                        <a class="more" title="more" href="javascript:void(0);" > More &gt; </a>
                    </div>
                </section>
            </section>
            <section id="myinterest" class="tab_content">
              <h1 class="heading1">My Interests<span class="set">Set yyyy</span><a href="#useropen" class="open leanModal">Open</a></h1>
              <table class="tag_table1">
                <tr>
                  <th>S</th>
                  <th>P</th>
                  <th class="td_th_align_left">Tag Group</th>
                  <th class="td_th_align_left">Tags</th>
                  <th>Applied</th>
                  <th class="td_th_align_right">Last used</th>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center"><input type="checkbox" class="styled" /></td>
                  <td><input type="text" maxlength="2" /></td>
                  <td >MU Group</td>
                  <td >activities,aims,alive,annual,area,arts,based,bristol,car<a href="#" data-link="user_more.php">...</a></td>
                  <td class="td_th_align_center" >70</td>
                  <td class="td_th_align_right" >6-15-2012</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center"><input type="checkbox" class="styled" /></td>
                  <td><input type="text" maxlength="2" /></td>
                  <td >MU Group1</td>
                  <td >children,city,closed,community,contact,council,create,</td>
                  <td class="td_th_align_center" >66</td>
                  <td class="td_th_align_right" >6-14-2012</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center"><input type="checkbox" class="styled" /></td>
                  <td><input type="text" maxlength="2" /></td>
                  <td >MU Group1</td>
                  <td >credits,culture,dance,days,develop,events,excluded,</td>
                  <td class="td_th_align_center" >63</td>
                  <td class="td_th_align_right" >6-11-2012</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center"><input type="checkbox" class="styled" /></td>
                  <td><input type="text" maxlength="2" /></td>
                  <td >Group 1</td>
                  <td >footsteps,free,games,held,home,join-in,london,meet,</td>
                  <td class="td_th_align_center" >57</td>
                  <td class="td_th_align_right" >6-11-2012</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center"><input type="checkbox" class="styled" /></td>
                  <td><input type="text" maxlength="2" /></td>
                  <td >Group 2</td>
                  <td >night,options,partnership,people,photos,positive,</td>
                  <td class="td_th_align_center" >53</td>
                  <td class="td_th_align_right" >6-10-2012</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center"><input type="checkbox" class="styled" /></td>
                  <td><input type="text" maxlength="2" /></td>
                  <td >Group 3</td>
                  <td >promotions,resulted,services,streets,successfully<a href="#">...</a></td>
                  <td class="td_th_align_center" >49</td>
                  <td class="td_th_align_right" >6-17-2012</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center"><input type="checkbox" class="styled" /></td>
                  <td><input type="text" maxlength="2" /></td>
                  <td >Group 4</td>
                  <td >traffic,traffic-free,transport,travel,used,wide,</td>
                  <td class="td_th_align_center" >36</td>
                  <td class="td_th_align_right" >6-18-2012</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center"><input type="checkbox" class="styled" /></td>
                  <td><input type="text" maxlength="2" /></td>
                  <td >Group 5</td>
                  <td >adults,alive,around,attitudes,behind,centre,chance</td>
                  <td class="td_th_align_center" >28</td>
                  <td class="td_th_align_right" >6-2-2012</td>
                </tr>
                <tr class="add_n">
                  <td><a href="#" class="add"></a></td>
                  <td colspan="2"><input type="text" value="Group 16" class="groupInp" /></td>
                  <td>&nbsp;</td>
                  <td class="td_th_align_center">&nbsp;</td>
                  <td class="td_th_align_right">&nbsp;</td>
                </tr>
                <tr>
                  <th colspan="2" class="td_th_align_left"><input type="submit" value="save" class="saveBtn" /></th>
                  <th colspan="4" class="td_th_align_left" ><a class="leanModal" href="#usersave">Save the setting as ...</a></th>
                </tr>
              </table>
            </section>
            <section id="mywatchlist" class="tab_content">
              <h1 class="heading1">My Watchlist</h1>
              <table class="tag_table">
                <tr>
                  <th style="width:15%"><select class="all">
                      <option>All</option>
                    </select></th>
                  <th style="width:15%"><select class="t_time">
                      <option>All Time</option>
                    </select></th>
                  <th style="width:25%" class="td_th_align_left">Event</th>
                  <th style="width:45%" class="td_th_align_left">Tags</th>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">5 days ago</td>
                  <td><a href="event.php" class="dblink">Monumenta</a></td>
                  <td>activities,aims,alive,annual,area,arts,based,bristol,car<a href="#" data-link="event_tag_more.php">...</a>                 
                  </td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">5 days ago</td>
                  <td><a href="event.php" class="dblink">Letterature</a></td>
                  <td>children,city,closed,community,contact,council,create,</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">6 days ago</td>
                  <td><a href="event.php" class="dblink">British Asparagus F...</a></td>
                  <td>credits,culture,dance,days,develop,events,excluded,</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">7 days ago</td>
                  <td><a href="event.php" class="dblink">Friday Market</a></td>
                  <td>footsteps,free,games,held,home,join-in,london,meet,</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">7 days ago</td>
                  <td><a href="event.php" class="dblink">San Pellegrino Cook...</a></td>
                  <td>night,options,partnership,people,photos,positive,</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">9 days ago</td>
                  <td><a href="event.php" class="dblink">Midsummer Cel...</a></td>
                  <td>promotions,resulted,services,streets,successfully...</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">9 days ago</td>
                  <td><a href="event.php" class="dblink">Sydney Good Food</a></td>
                  <td>traffic,traffic-free,transport,travel,used,wide,</td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">11 days ago</td>
                  <td><a href="event.php" class="dblink">Rally del Salento</a></td>
                  <td>adults,alive,around,attitudes,behind,centre,chance</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">Public</td>
                  <td class="td_th_align_right">12 days ago</td>
                  <td><a href="event.php" class="dblink">Dragonboat Cup</a></td>
                  <td>change,children,community,contact,create,credits<a href="#">...</a></td>
                </tr>
                <tr class="even">
                  <td class="td_th_align_center">Private</td>
                  <td class="td_th_align_right">13 days ago</td>
                  <td><a href="event.php" class="dblink">Football Match</a></td>
                  <td>text,town,traffic,traffic-free,uk,visible,walk,young,</td>
                </tr>
                <tr class="add_n">
                  <td class="td_th_align_center">fb G1</td>
                  <td class="td_th_align_right">19 days ago</td>
                  <td><a href="event.php" class="dblink">Nancy BD</a></td>
                  <td>football,games,generations,give,home,links,london,<a href="#">...</a></td>
                </tr>
                <!--<tr>
                  <td colspan="4"><a href="#" class="more">More...</a></td>
                </tr> -->
              </table>
            </section>
          </section>
        </article>


<div id="uploadThumbnail" class="popup_window" style="width:485px;">
  <?php include("upload_thumbnail.php");?>
</div>
<div id="usersave" class="popup_window" style="width:450px;">
  <?php include("user_save.php");?>
</div>
<div id="useropen" class="popup_window" style="width:450px;">
  <?php include("user_open.php");?>
</div>