<article class="post_content clearfix">
    <header>
        <div class="watched">
            <div class="w1">
                <img class="watcher_icon" src="<?php echo $this->baseUrl('images/watched_icon.png');?>" alt=" " /><span class="w_con">Watched: 2</span>
            </div>
            <div class="w2">
                225
            </div>
        </div>
        <h3 class="head3">Floating turbine buoys offshore wind....</h3>
    </header>
    <div class="post_left"><img src="<?php echo $this->baseUrl('images/p4.jpg');?>" alt=" " />
    </div>
    <div class="post_right">
        <header class="tag_top taggap clearfix">
            <ul>
                <li>
                    <a href="#"><strong>Knowledge</strong></a>
                </li>
                <li>
                    |
                </li>
                <li>
                    start: Dec 23, 2012
                </li>
                <li>
                    |
                </li>
                <li>
                    place:<a href="#">Grand City Hall</a>
                </li>
            </ul>
        </header>
        <p>
            Music is the soul of the cosmos. It is found everywhere from the rustling of the trees, to the playful streams to the pitter-patter of the raindrops. Indian music in particular, is one of the oldest and finest forms of human passions like agony, ecstasy, sorrow, hope, desire etc. Indian music has strong connections.
        </p>
        <footer class="tag_bottom">
            <div class="tag_l left">
                <strong>Tags:</strong><a href="#">Music</a>|<a href="#">Dance</a>
            </div>
            <div class="tag_r right">
                <a href="#">by Mac Slocum</a>|<a href="#">12 days ago</a>
            </div>
        </footer>
    </div>
</article>
<article class="post_content clearfix">
    <header>
        <div class="watched">
            <div class="w1">
                <img class="watcher_icon" src="<?php echo $this->baseUrl('images/watched_icon.png');?>" alt=" " /><span class="w_con">Watched: 1</span>
            </div>
            <div class="w2">
                125
            </div>
        </div>
        <h3 class="head3">From CrackBerry to 'depressing'</h3>
    </header>
    <div class="post_left"><img src="<?php echo $this->baseUrl('images/p5.jpg');?>" alt=" " />
    </div>
    <div class="post_right">
        <header class="tag_top taggap clearfix">
            <ul>
                <li>
                    <a href="#"><strong>Students</strong></a>
                </li>
                <li>
                    |
                </li>
                <li>
                    start: Dec 23, 2012
                </li>
                <li>
                    |
                </li>
                <li>
                    place:<a href="#">Grand City Hall</a>
                </li>
            </ul>
        </header>
        <p>
            Music is the soul of the cosmos. It is found everywhere from the rustling of the trees, to the playful streams to the pitter-patter of the raindrops. Indian music in particular, is one of the oldest and finest forms of human passions like agony, ecstasy, sorrow, hope, desire etc. Indian music has strong connections.
        </p>
        <footer class="tag_bottom">
            <div class="tag_l left">
                <strong>Tags:</strong><a href="#">Music</a>|<a href="#">Dance</a>
            </div>
            <div class="tag_r right">
                <a href="#">by Mac Slocum</a>|<a href="#">20 days ago</a>
            </div>
        </footer>
    </div>
</article>
<article class="post_content clearfix">
    <header>
        <div class="watched">
            <div class="w1">
                <img class="watcher_icon" src="<?php echo $this->baseUrl('images/watched_icon.png');?>" alt=" " /><span class="w_con">Watched: 7</span>
            </div>
            <div class="w2">
                315
            </div>
        </div>
        <h3 class="head3">Cyprus requests emergency loans....</h3>
    </header>
    <div class="post_left"><img src="<?php echo $this->baseUrl('images/p6.jpg');?>" alt=" " />
    </div>
    <div class="post_right">
        <header class="tag_top taggap clearfix">
            <ul>
                <li>
                    <a href="#"><strong>Venues &amp; Festival</strong></a>
                </li>
                <li>
                    |
                </li>
                <li>
                    start: Dec 23, 2012
                </li>
                <li>
                    |
                </li>
                <li>
                    place:<a href="#">Grand City Hall</a>
                </li>
            </ul>
        </header>
        <p>
            Music is the soul of the cosmos. It is found everywhere from the rustling of the trees, to the playful streams to the pitter-patter of the raindrops. Indian music in particular, is one of the oldest and finest forms of human passions like agony, ecstasy, sorrow, hope, desire etc. Indian music has strong connections.
        </p>
        <footer class="tag_bottom">
            <div class="tag_l left">
                <strong>Tags:</strong><a href="#">Music</a>|<a href="#">Dance</a>
            </div>
            <div class="tag_r right">
                <a href="#">by Mac Slocum</a>|<a href="#">25 days ago</a>
            </div>
        </footer>
    </div>
</article>