<?php echo $this->partial('js/filter.phtml')?>

<?php $sort_by = (isset($_GET['sort_by']) && ($_GET['sort_by']==0||$_GET['sort_by']==1||$_GET['sort_by']==2)) ? $_GET['sort_by'] : Zend_Registry::get('config')->filter->user_para->sort_by;
    $is_match_interest = (isset($_GET['is_match_interest']) && ($_GET['is_match_interest']==0||$_GET['is_match_interest']==1)) ? $_GET['is_match_interest'] : Zend_Registry::get('config')->filter->user_para->is_match_interest;
    $is_match_location = (isset($_GET['is_match_location']) && ($_GET['is_match_location']==0||$_GET['is_match_location']==1)) ? $_GET['is_match_location'] : Zend_Registry::get('config')->filter->user_para->is_match_location;
    $is_show_map = (isset($_GET['is_show_map']) && ($_GET['is_show_map']==0||$_GET['is_show_map']==1)) ? $_GET['is_show_map'] : Zend_Registry::get('config')->filter->user_para->is_show_map;
    $radius = isset($_GET['radius']) && (is_numeric($_GET['radius'])) ? $_GET['radius'] : Zend_Registry::get('config')->filter->user_para->radius;
    $place_lat = isset($_GET['place_lat']) && (is_numeric($_GET['place_lat'])) ? $_GET['place_lat'] : Zend_Registry::get('config')->filter->user_para->place_lat;
    $place_lng = isset($_GET['place_lng']) && (is_numeric($_GET['place_lng'])) ? $_GET['place_lng'] : Zend_Registry::get('config')->filter->user_para->place_lat;
?>

<?php /*<form action="" id="feed_filter" name="feed_filter" class="search"> */ ?>
    <section class="filter clearfix">
        <nav class="sort_by">
            <div class="title">Sort by :</div>
            <ul>
                <li class="<?php if ($sort_by==0){ ?>current<?php } ?>" data-value="0"><?php echo $this->translate('new')?></li>
                <li class="<?php if ($sort_by==1){ ?>current<?php } ?>" data-value="1"><?php echo $this->translate('hot')?></li>
                <li class="last <?php if ($sort_by==2){ ?>current<?php } ?>" data-value="2"><?php echo $this->translate('ending soon')?></li>
            </ul>
        </nav>
        <input type="hidden" class="feed_filter_input" name="sort_by" value="<?php echo $sort_by ?>"/>
        
        <input class="feed_filter_input" type="checkbox" <?php if (Zend_Auth::getInstance()->hasIdentity() && isset($_GET['is_match_interest']) && $_GET['is_match_interest']==1) {?>checked="checked" <?php } ?> name="is_match_interest" id="feed_is_match_interest" <?php if (!Zend_Auth::getInstance()->hasIdentity()) { ?> disabled="disabled"<?php } ?>/> <label for="feed_is_match_interest"><?php echo $this->translate('match interest')?></label>
        <input class="feed_filter_input" type="checkbox" <?php if (isset($_GET['is_match_location']) && $_GET['is_match_location']==1) {?>checked="checked" <?php } ?> name="is_match_location" id="feed_is_match_location" /> <label for="feed_is_match_location"><?php echo $this->translate('match location')?></label>
        <a href="#" class="showMap"><strong><?php echo ($is_show_map != 1) ? $this->translate('show map') : $this->translate('hide map') ?></strong></a>
        <input type="hidden" class="feed_filter_input" name="is_show_map" value="<?php echo $is_show_map ?>"/>
        <a id="refresh_feed" href="#"><strong><?php echo $this->translate('refresh')?></strong></a>
        <img alt="loading..." class="loading feed" src="<?php echo $this->baseUrl('images/loading.gif') ?>" />
    </section>
    <section style="display:none;" class="match_location_set clearfix" style="display:none;">
        <h3 class="radius_amt" ><?php echo $this -> translate("within %1\$s km of %2\$s", '<span id="filter_radius">'.$radius.'</span>', '<span id="of"> Tai Lam, Hong Kong</span>'); ?></h3>
        <div class="radius_amt" style="display:inline"></div>
        <div id="radius_slider"></div>
        <input type="hidden" class="feed_filter_input" name="radius" value="<?php echo $radius ?>"/>
        <div class="loc_right">
        <input id="locate_somewhere" type="text" name="locate_somewhere" value="" />
        <img id="geo_locate" class="geo_locate" onclick="navigator.geolocation.getCurrentPosition(ns_filter_map.handleGeolocationQuery,ns_filter_map.handleErrors);return false;" src="<?php echo $this->baseUrl('images/location_icon.png')?>" class="l_icon" alt="geo locate..." />
        <?php if (Zend_Auth::getInstance()->hasIdentity()){ ?>
         <select class="user_saved_location_list">
          <option value="last" disabled="disabled" selected="selected"><?php echo $this->translate('saved locations') ?>...</option>
          <?php foreach(Common::getSession()->user_saved_locations as $value){?>
            <option value="<?php echo $value['name']?>"><?php echo $value['name']?></option>
          <?php } ?>
         </select>
        <a href="#" class="save_location"><img src="<?php echo $this->baseUrl('images/save.gif')?>" alt=" " /></a>
        <a href="#" class="manage_location"><img src="<?php echo $this->baseUrl('images/setting.gif')?>" alt=" " /></a>
        </div>
        <?php } ?>
    </section>
    <section style="display:none;width:100%;height:300px;border:1px solid black" id="map_wrapper">
        <input type="hidden" class="feed_filter_input" name="place_lat" value="<?php echo $place_lat ?>"/>
        <input type="hidden" class="feed_filter_input" name="place_lng" value="<?php echo $place_lng ?>"/>
        <?php //<article> <img src="images/map2.gif" alt=" "> </article> ?>
        <div id="feed_filter_map" style="height: 300px;width: 100%;background-color: #E5E3DF;overflow: hidden;position: relative;"></div>
      </section>
  <?php //</form> ?>