<script type="text/javascript">
var ns_event_reminder_form = {
  reminder_textfields : ['reminder_title', 'reminder_description', 'reminder_tags','reminder_attend_datetime'],
  reminder_checkboxes : ['reminder_has_email_alarm','reminder_has_popup_alarm','reminder_has_mobile_alarm'],
  alert_types : ['email', 'popup', 'mobile'],
  tmpl_functions : {
    isSetAttendDateTime: function() {
      if (this.data.reminder_attend_datetime){
        if (this.data.reminder_attend_datetime == '') return false;
      } else {
        return false;
      }
      return true;
    },
    getAttendDate: function(){
      var data = this.data.reminder_attend_datetime;
      if(data){
        if(data.trim()=='') return '';
        var array = data.split(' ');
        return array[0];
      }
      return '';
    },
    getAttendTime: function(){
      var data = this.data.reminder_attend_datetime;
      if(data){
        if(data.trim()=='') return '';
        var array = data.split(' ');
        return array[1];
      }
      return '';
    }
  },
  init : function(){
    $('input[name="event_reminder_title"]').watermark("<?php echo $this->translate('reminder title') ?>");
    $('textarea[name="event_reminder_description"]').watermark("<?php echo $this->translate('reminder description') ?>");
    $('input[name="event_reminder_tags"]').watermark("<?php echo $this->translate('Please enter tags (seperated with comma)') ?>");
    $('.event_reminder_attend_date').watermark("<?php echo $this->translate('date') ?>");
    $('.event_reminder_attend_time').watermark("<?php echo $this->translate('time') ?>");
    $('.event_reminder_attend_date').datepicker({
          changeMonth: true,
          changeYear: true,
          onSelect: function(dateText, inst) { ns_event_reminder_form.updateReminderDescription();}
    }).keyup(function(e) {
      if(e.keyCode == 8 || e.keyCode == 46) {
        e.preventDefault();
        $.datepicker._clearDate(this);
      }
    });
    $('.event_reminder_attend_time').timepicker({
      'timeFormat': 'H:i', step : 15 
    });
    $('.event_reminder_attend_time').on('change',function(){
      ns_event_reminder_form.updateAttendDatetime();
    })
    if ($('.event_reminder_is_match_event_begin_datetime').is(':checked')){
        $('.event_reminder_attend_date').val('').prop('disabled',true);
        $('.event_reminder_attend_time').val('').prop('disabled',true);
        $('.event_reminder_attend_datetime').val('');
        $('.reminder_desc').empty();
    } else {
        $('.event_reminder_attend_date').prop('disabled',false);
        $('.event_reminder_attend_time').prop('disabled',false);
    }
    $('.event_reminder_has_alarm').each(function(){
      if (! $(this).is(':checked')){
        $('#event_reminder_'+$(this).val()+'_alarm_time').prop('disabled',true);
        $('#event_reminder_'+$(this).val()+'_alarm_time_unit').prop('disabled',true);
      } else {
        $('#event_reminder_'+$(this).val()+'_alarm_time').prop('disabled',false);
        $('#event_reminder_'+$(this).val()+'_alarm_time_unit').prop('disabled',false);
      }
    });
    
    ns_event_reminder_form.updateReminderDescription();
  },
  updateAttendDatetime: function(){
    if($('.event_reminder_is_match_event_begin_datetime').is(':checked')){
      $('.event_reminder_attend_datetime').val($('.event_reminder_event_begin_datetime').val());
    }else{
      if ($('.event_reminder_attend_date').val()=='') return false;
      var time = $('.event_reminder_attend_time').val()!='' ? $('.event_reminder_attend_time').val() : '00:00';
      $('.event_reminder_attend_datetime').val($('.event_reminder_attend_date').val()+' '+time);
    }
    return true;
  },
  hasReminderContent: function(data){
    for ( var n in ns_event_reminder_form.reminder_textfields ){
      if (typeof data[ns_event_reminder_form.reminder_textfields[n]] != 'undefined'){
        if (data[ns_event_reminder_form.reminder_textfields[n]] != null && data[ns_event_reminder_form.reminder_textfields[n]] != '') 
          return true;
      }
    }
    for ( var n in ns_event_reminder_form.reminder_checkboxes ){
      if (typeof data[ns_event_reminder_form.reminder_checkboxes[n]] != 'undefined'){
        if (data[ns_event_reminder_form.reminder_checkboxes[n]] == 1) return true;
      }
    }
    return false;
  },
  updateReminderDescription : function(){
    if (!ns_event_reminder_form.updateAttendDatetime()){
      $('.reminder_desc').empty();
      return false;
    };
    
    var datetime = Date.parse($('.event_reminder_attend_datetime').val());
    
    var types = ['email', 'popup', 'mobile'];
    for (i in types){
      if ($('#event_reminder_has_'+types[i]+'_alarm').is(':checked')){
        var unit = $('#event_reminder_'+types[i]+'_alarm_time_unit').val();
        var time_amount = new String('-'+$('#event_reminder_'+types[i]+'_alarm_time').val());
        var time;
        if (isNumber(time_amount)){
          time = Number(time_amount);
        }else{ 
          time = 0; 
          $('#event_reminder_'+types[i]+'_alarm_time').val(0)
        }
        
        if (unit=='weeks'){
          datetime = datetime.add(time).weeks();
        } else if (unit=='days'){
          datetime = datetime.add(time).days();
        } else if (unit=='hours'){
          datetime = datetime.add(time).hours();
        } else if (unit=='minutes'){
          datetime = datetime.add(time).minutes();
        }
        $('#'+types[i]+'_reminder_desc').text(datetime.toString('yyyy-MM-dd HH:mm'));
      } else {
        $('#'+types[i]+'_reminder_desc').empty();
      }
    }
  },
  submitForm : function(data){
    $('.event_reminder_alarm_time').each(function(){
      if(! isNumber($(this).val())) $(this).val(0);
    });
    $('.event_reminder_attend_datetime').val( $('.event_reminder_attend_date').val()+' '+$('.event_reminder_attend_time').val() );
    var is_submitted = false;
    $('.reminder_save_status .saving').show();
    jQuery.ajax({
      type: "POST",
      url: "<?php echo $this->baseUrl('ajax/event/reminder_form_submit') ?>",
      data: data,
      success: function(msg){
        if(msg['result']==true){
          
          $('.reminder_save_status .saving').hide();
          $('.reminder_save_status .saved').show().fadeOut("slow");
          
          var reminder_fields = ns_event_reminder_form.reminder_textfields;
          for ( i in reminder_fields){
            $('[data-id="'+msg.data[0].id+'"]').find('[name="event_'+reminder_fields[i]+'"]').text(msg.data[0][reminder_fields[i]]);
            if( msg.data[0][reminder_fields[i]] && msg.data[0][reminder_fields[i]]!='' ){
              
            } else{
              $('[data-id="'+msg.data[0].id+'"]').find('[name="event_'+reminder_fields[i]+'"]').parents('.text_line').removeClass('hidden');
            }
          }
          
          if(msg.data[0].reminder_title && msg.data[0].reminder_title!=''){
            $('[data-id="'+msg.data[0].id+'"]').find('.reminder_title .text').text(msg.data[0].reminder_title);
            $('[data-id="'+msg.data[0].id+'"]').find('.reminder_title .not_set').hide();
          } else{
            $('[data-id="'+msg.data[0].id+'"]').find('.reminder_title .text').text('');
            $('[data-id="'+msg.data[0].id+'"]').find('.reminder_title .not_set').show();
          }
          
          if (ns_event_reminder_form.hasReminderContent(msg.data[0])){
            $('.bookmark_popup[data-id="'+msg.data[0].id+'"]').addClass('has_reminder');
          } else {
            $('.bookmark_popup[data-id="'+msg.data[0].id+'"]').removeClass('has_reminder');
          }
          ns_bookmark_popup.updateContent(msg);
          if(! $('.bookmark_popup[data-id="'+msg.data[0].id+'"]').is(':visible')){
            var popup_content = ns_feed.getHTML(msg, 'bookmark_popup', ns_bookmark_popup.tmpl_functions);
            $('body').append(popup_content);
          } else {
          }
    return true;
        } else{
    return false;
        }
      },
      error: function(){
        alert ("<?php echo $this->translate('Connection failed. Please try again later.') ?>");
        $('.reminder_save_status .saving').hide();
    console.log(true);
    return true;
      },
      dataType:"json"
    });
  }
}

jQuery(function($){
  $('body').on('click', 'input#event_reminder_save', function(e){
    e.preventDefault();
    ns_event_reminder_form.submitForm($(this).parents('form').serialize());
    return false;
  })
  .on('click', 'input#event_reminder_close', function(e){
    e.preventDefault();
    $.colorbox.close();
    return false;
  }).on('change','.event_reminder_has_alarm',function(){
    if (! $(this).is(':checked')){
      $('#event_reminder_'+$(this).val()+'_alarm_time').prop('disabled',true);
      $('#event_reminder_'+$(this).val()+'_alarm_time_unit').prop('disabled',true);
    } else {
      $('#event_reminder_'+$(this).val()+'_alarm_time').prop('disabled',false);
      $('#event_reminder_'+$(this).val()+'_alarm_time_unit').prop('disabled',false);
    }
  })
  .on('change','.event_reminder_is_match_event_begin_datetime .event_reminder_attend_date, .event_reminder_attend_time, .event_reminder_has_alarm, .event_reminder_alarm_time, .event_reminder_alarm_time_unit', function(){
    ns_event_reminder_form.updateReminderDescription();
  });
})
</script>
