<script type="text/javascript">
var ns_event_reminder_form = {
  reminder_textfields : ['reminder_title', 'reminder_description', 'reminder_tags','reminder_attend_datetime'],
  reminder_checkboxes : ['reminder_has_email_alarm','reminder_has_popup_alarm','reminder_has_mobile_alarm'],
  init : function(){
    $('input[name="event_reminder_title"]').watermark("<?php echo $this->translate('reminder title') ?>");
    $('textarea[name="event_reminder_description"]').watermark("<?php echo $this->translate('reminder description') ?>");
    $('input[name="event_reminder_tags"]').watermark("<?php echo $this->translate('Please enter tags (seperated with comma)') ?>");
    $('input#event_reminder_attend_date').watermark("<?php echo $this->translate('date') ?>");
    $('input#event_reminder_attend_time').watermark("<?php echo $this->translate('time') ?>");
    $('#event_reminder_attend_date').datepicker({
          changeMonth: true,
          changeYear: true
    }).keyup(function(e) {
      if(e.keyCode == 8 || e.keyCode == 46) {
        e.preventDefault();
        $.datepicker._clearDate(this);
      }
    });
    $('#event_reminder_attend_time').timepicker({
      'timeFormat': 'H:i', step : 15 
    });
    $('.event_reminder_has_alarm').each(function(){
      if (! $(this).is(':checked')){
        $('#event_reminder_'+$(this).val()+'_alarm_time').prop('disabled',true);
        $('#event_reminder_'+$(this).val()+'_alarm_time_unit').prop('disabled',true);
      } else {
        $('#event_reminder_'+$(this).val()+'_alarm_time').prop('disabled',false);
        $('#event_reminder_'+$(this).val()+'_alarm_time_unit').prop('disabled',false);
      }
    })
    ns_event_reminder_form.updateReminderDescription();
  },
  hasReminderContent: function(data){
    for ( var n in ns_event_reminder_form.reminder_textfields ){
      if (typeof data[ns_event_reminder_form.reminder_textfields[n]] != 'undefined'){
        if (data[ns_event_reminder_form.reminder_textfields[n]] != null && data[ns_event_reminder_form.reminder_textfields[n]] != '') 
          return true;
      }
    }
    for ( var n in ns_event_reminder_form.reminder_checkboxes ){
      if (typeof data[ns_event_reminder_form.reminder_checkboxes[n]] != 'undefined'){
        if (data[ns_event_reminder_form.reminder_checkboxes[n]] == 1) return true;
      }
    }
    return false;
  },
  updateReminderDescription : function(){
    var datetime;
    var types = ['email', 'popup', 'mobile'];
    for (i in types){
      datetime = Date.parse($('#event_reminder_attend_date').val()+' '+$('#event_reminder_attend_time').val());
      if ($('#event_reminder_has_'+types[i]+'_alarm').is(':checked')){
        var unit = $('#event_reminder_'+types[i]+'_alarm_time_unit').val();
        var time_amount = new String('-'+$('#event_reminder_'+types[i]+'_alarm_time').val());
        var time;
        if (isNumber(time_amount)) time = Number(time_amount);
        else{ time = 0; $('#event_reminder_'+types[i]+'_alarm_time').val(0)}
        
        if (unit=='weeks'){
          datetime = datetime.add(time).weeks();
        } else if (unit=='days'){
          datetime = datetime.add(time).days();
        } else if (unit=='hours'){
          datetime = datetime.add(time).hours();
        } else if (unit=='minutes'){
          datetime = datetime.add(time).minutes();
        }
        $('#'+types[i]+'_reminder_desc').text(datetime.toString('yyyy-MM-dd HH:mm'));
      } else {
        $('#'+types[i]+'_reminder_desc').empty();
      }
    }
  },
  submitForm : function(form){
    $('.event_reminder_alarm_time').each(function(){
      if(! isNumber($(this).val())) $(this).val(0);
    });
    $('#event_reminder_attend_datetime').val( $('#event_reminder_attend_date').val()+' '+$('#event_reminder_attend_time').val() );
    var is_submitted = false;
    $('.reminder_save_status .saving').show();
    jQuery.ajax({
      type: "POST",
      url: "<?php echo $this->baseUrl('ajax/event/reminder_form_submit') ?>",
      data: form.serialize(),
      success: function(msg){
        if(msg['result']==true){
          $('[data-id="'+msg.data.item_id+'"]').find('[name="event_reminder_title"]').val(msg.data.title);
          $('[data-id="'+msg.data.item_id+'"]').find('[name="event_reminder_description"]').text(msg.data.description);
          $('.reminder_save_status .saving').hide();
          $('.reminder_save_status .saved').show().fadeOut("slow");
          if(msg.data.title && msg.data.title!=''){
            $('[data-id="'+msg.data.item_id+'"]').find('.reminder_title .text').text(msg.data.title);
            $('[data-id="'+msg.data.item_id+'"]').find('.reminder_title .not_set').hide();
          } else{
            $('[data-id="'+msg.data.item_id+'"]').find('.reminder_title .text').text('');
            $('[data-id="'+msg.data.item_id+'"]').find('.reminder_title .not_set').show();
          }
          
          console.log(msg.data);
          if (ns_event_reminder_form.hasReminderContent(msg.data)){
            $('[data-id="'+msg.data.item_id+'"]').addClass('has_reminder');
          } else {
            $('[data-id="'+msg.data.item_id+'"]').removeClass('has_reminder');
          }
          return true;
        } else{
          return false;
        }
      },
      error: function(){
        alert ("<?php echo $this->translate('Connection failed. Please try again later.') ?>");
        $('.reminder_save_status .saving').hide();
      },
      dataType:"json"
    });
    
    return is_submitted;
  }
}

jQuery(function($){
  $('body').on('click', 'input#event_reminder_save', function(e){
    e.preventDefault();
    ns_event_reminder_form.submitForm($(this).parents('form'));
    return false;
  })
  .on('click', 'input#event_reminder_close', function(e){
    e.preventDefault();
    $.colorbox.close();
    return false;
  }).on('change','.event_reminder_has_alarm',function(){
    if (! $(this).is(':checked')){
      $('#event_reminder_'+$(this).val()+'_alarm_time').prop('disabled',true);
      $('#event_reminder_'+$(this).val()+'_alarm_time_unit').prop('disabled',true);
    } else {
      $('#event_reminder_'+$(this).val()+'_alarm_time').prop('disabled',false);
      $('#event_reminder_'+$(this).val()+'_alarm_time_unit').prop('disabled',false);
    }
  })
  .on('change','#event_reminder_attend_date, #event_reminder_attend_time, .event_reminder_has_alarm, .event_reminder_alarm_time, .event_reminder_alarm_time_unit', function(){
    ns_event_reminder_form.updateReminderDescription();
  });
})
</script>
