<div class="popup_bor">
<div class="main_popup">
<div class="popup-header">
<h2>Are you sure you want to do that?</h2>
<a class="window_close" href="javascript: void(5)"></a>
</div>
<div class="pop_form">
<p>Clicking yes will make the current selection your new system
default location. Seriously, have you thought this through?</p>
<div class="p_field"><select class="reveal"><option>Reveal</option></select></div>
<div class="p_field"><a href="#morebox" class="form_more leanModal2">more</a>
<a href="#" class="button green confirm_close"><img src="images/tick.png" alt="yes" />Yes, do it now!</a>
<a href="#" class="button red confirm_close"><img src="images/cross.png" alt="no" />No, I'm insane!</a>
</div>
</div>
</div>
</div>