<div class="popup_bor">
<div class="main_popup">
<div class="popup-header">
<h2>Saved Locations Management</h2>
<a class="modal_close" href="javascript: void(0)"></a>
</div>
<div class="watcher_form">
        	<table border="" class="main_table div_gap">
              <tr>
                <td>Nossa Senhora do Carmo, Macau</td>
                <td><img src="images/location_img1.gif" alt="Location"></td>
                <td><a class="leanModal1" href="#remove">remove</a></td>
              </tr>
              <tr>
                <td>Kudanminami, Chiyoda, Tokyo 102-8305, J</td>
                <td><img src="images/location_img1.gif" alt="Location"></td>
                <td><a class="leanModal1" href="#remove" >remove</a></td>
              </tr>
            </table>
            
            <ul>
            	<li class="none"><input type="submit" value="Save"  class="submit1" /><input type="submit" value="Cancel" class="submit2" /></li>
            </ul>
            

        </div>
</div>
</div>