<div class="popup_bor">
<div class="main_popup">
<div class="popup-header">
<h2>Login</h2>
<a class="modal_close" href="javascript: void(0)"></a>
</div>
<div class="pop_form">
<div class="p_field"><label>User Name:</label><input type="text" /></div>
<div class="p_field"><label>Password:</label><input type="password" /></div>
<div class=""><a class="forgot" href="<?php echo $this->baseUrl('auth/forgot_password')?>">Forgot your password?</a><input type="submit" value="Login" class="right" /></div>
</div>
</div>
</div>