<div class="popup_bor">
<div class="main_popup">
<div class="popup-header">
<h2>Save this Location</h2>
<a class="modal_close" href="javascript: void(0)"></a>
</div>
<div class="watcher_form">
        	<ul>
            	<li><input type="text" value="Nossa Senhora do Carmo, Macau" onclick="if(this.value == 'Nossa Senhora do Carmo, Macau'){this.value='';}" onblur="if(this.value==''){this.value='Nossa Senhora do Carmo, Macau'};"></li>
                <li class="none"><input type="submit" value="Save" class="submit1" /><input type="submit" value="Cancel" class="submit2 close_window" /></li>
            </ul>
        </div>
</div>
</div>