<div class="popup_bor">
<div class="main_popup">
<div class="popup-header">
<h2>Add a Simple Personal Event</h2>
<a class="modal_close" href="javascript: void(0)"></a>
</div>
<section class="watcher_details_inner">
        <div class="watcher_form gap_top">
            <ul>
                <li><input type="text" value="Event Title" /></li>
                <li><input type="text" value="2012-12-31" class="d_input" /><input type="text" value="23:50" class="t_input" /> - &nbsp;<input type="text" value="2012-12-31" class="d_input" /><input type="text" value="23:50" class="t_input" /></li>
                <li><textarea rows="5">Event Description</textarea></li>
            </ul>
        </div>
        <div class="watcher_form watcher_tag_inner watch_bor">
            <ul>
                <li><label class="tag_label">Tag</label><select><option>Select a group</option></select></li>
                <li><footer class="tag_l"><strong>Tags:</strong> <a href="#">Tag1</a> | <a href="#">Taaag1</a> | <a href="#">Taaaaag1</a> | <a href="#">Taaaag1</a> | <a href="#">Taaaaag1</a> | <a href="#">Taaag1</a> | <a href="#">Tagaa1</a> | <a href="#">Taaaaag1</a> | <a href="#">Tag1</a> | <a href="#">Tagaggg1</a> | <a href="#">Tagsaggg1</a></footer></li>
                <li><textarea rows="5">Enter your description here</textarea></li>
                <li class="none">
                <input type="submit" value="Save" class="submit1" />
                <input type="submit" value="Cancel" class="submit2 close_window" />
                </li>
            </ul>
        </div>
    </section>
</div>
</div>


    
