<script id="login" type="text/x-jquery-tmpl">
<?php /*    <div class="popup_bor">
        <div class="main_popup">
           <?php // <div class="popup-header">
                //<h2>Login</h2>
                //<a class="modal_close" href="javascript: void(0)"></a>
            //</div>
            <div class="pop_form">
                <div class="p_field"><label>User Name:</label><input type="text" /></div>
                <div class="p_field"><label>Password:</label><input type="password" /></div>
                <div><a class="forgot" href="<?php echo $this->baseUrl('auth/forgot_password')?>">Forgot your password?</a><input type="submit" value="Login" class="right" /></div>
                <div>or <a class="use_other_auth_provider" href="<?php echo $this->baseUrl('auth/login')?>">use other site account (Facebook, Google, or Twitter)...</a></div>
            </div>
        </div>
    </div><?php */ ?>
<?php /*    
<nav class="breadcrumb clearfix">
    <ul>
        <li>
            You are here:
        </li>
        <li>
            <a href="#"><strong>Home</strong></a> &gt;
        </li>
        <li>
            <strong>Login</strong>
        </li>
    </ul>
</nav><?php */ ?>
    <article class="main div_shadow">
        <section class="mainevent">
            <?php /*<h1>Login</h1>*/?>
            <div class="pop_form login_form">
                <div class="col_left">
                    <form method="post" action="<?php echo $this->baseUrl('auth/login')?>">
                    <div class="p_field">
                        <input class="required username"  type="text" name="username" value="" />
                    </div>
                    <div class="p_field">
                        <input type="password" class="required password" type="text" name="password" value="" />
                    </div>
                    
                    <div>
                        <input class="submit_btn" type="submit" value="Login"  />
                    </div>
                    </form>
                    <div class="other_options">
                        <a href="<?php echo $this->baseUrl('auth/signup'); ?>">Don't have an account?</a> <br />
                        <a href="<?php echo $this->baseUrl('auth/forgot_password'); ?>">Forgot your password?</a>
                    </div>
                </div>
                <div class="or">
                    <p>Or</p>
                </div>
                <div class="col_right">
                        <a href="${googleAuthUrl}" class="button google"></a><br />
                        <a href="${facebookAuthUrl}" class="button facebook"></a><br />
                        <a href="${twitterAuthUrl}" class="button twitter"></a>
                </div>
                <div class="clr"></div>
            </div>
        </section>
    </article>
</script>