<!DOCTYPE html>
<html lang="en">
    <?php echo $this->render('head.phtml') ?>
<body>
    <?php echo $this->render('header.phtml') ?>
    <div id="main_wrapper">
      <div class="container">
        <section id="main" class="clearfix">
            <?php echo $this->render('sidebar.phtml') ?>
            <section id="content" class="right">
                <?php echo $this->layout()->content ?>
            </section>
        </section>
      </div>
    </div>
    <?php echo $this->render('footer.phtml') ?>
    <?php echo $this->render('scripts.phtml') ?>
</body>
</html>
