<?php 
//echo '<pre>';var_dump(Common::getSession()->user);echo '</pre>'; ?>
<head>
    <?php echo $this->headTitle(); ?>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link href="<?php echo $this->baseUrl('favicon.ico'); ?>" rel="shortcut icon" />
    <?php echo $this->minifyHeadLink()
        //->appendStylesheet('tooltip.css')
        //->appendStylesheet('bootstrap.css')
        //->appendStylesheet('normalize.css')
        ->appendStylesheet('jquery.qtip.css')
        ->appendStylesheet('ui-lightness/jquery-ui-1.10.3.custom.min.css')
        ->appendStylesheet('main.css')
        ->appendStylesheet('colorbox.css');
    ?>
    
    <?php if (Zend_Registry::get('config_ini')->server->online==1){ ?>
        <script src="http://maps.googleapis.com/maps/api/js?key=<?php echo Zend_Registry::get('config_ini')->google->api_key ?>&sensor=false&amp;libraries=places&amp;region=hk&amp;language=<?php echo Common::getSiteDisplayLang();?>" type="text/javascript"></script>
    <?php } ?>
    
    <?php $this->minifyHeadScript()
        ->prependFile('jquery-ui-1.10.3.custom.js')
        ->prependFile('jquery-1.8.3.min.js')
        ->appendFile('jquery.tmpl.min.js')
        ->appendFile('jquery.qtip.min.js')
        ->appendFile('jquery.watermark.js')
        ->appendFile('jquery.dotdotdot.min.js')
        ->appendFile('jQueryRotate.2.2.js')
        //->appendFile('jquery.validate.js')
        ->appendFile('jquery.address-1.5.min.js')
        ->appendFile('jquery.lazyload.js')
        ->appendFile('jquery.uqr.js')
        ->appendFile('jquery.timepicker.min.js')
        ->appendFile('jquery.mousewheel-3.1.6.js')
        ->appendFile('jquery.scrollpanel-0.1.min.js')
        ->appendFile('validate/jquery.validate.min.js')
        ->appendFile('tinymce/jquery.tinymce.js')
        ->appendFile('jquery.cookie.js')
        ->appendFile('jquery.colorbox-min.js')
        ->appendFile('date.js')
        ->appendFile('jquery.editinplace.js');
    
        if (Common::getSiteDisplayLang() == 'zh-hk'){
          $this->minifyHeadScript()->appendFile('jquery.validate.messages_zh_TW.js');
        }
        if (Zend_Registry::get('config_ini')->server->online==1){
            echo $this->minifyHeadScript()->appendFile('map/distancewidget.js');
        }else{
            echo $this->minifyHeadScript();
        }
    ?>
    <link href="<?php echo $this->baseUrl('css/wittysparks_checkbox_radio.css')?>"  rel="stylesheet" type="text/css" >
    <?php /*
    <link href="<?php echo $this->baseUrl('css/main.less')?>" rel="stylesheet/less" type="text/css" media="all">
      <script type="text/javascript" src="<?php echo $this->baseUrl('js/less-1.3.0.min.js')?>"> </script> */ ?>
      
    <!-- Internet Explorer HTML5 enabling code: -->
    <!--[if IE]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
            <script src="http://ie7-js.googlecode.com/svn/version/2.1%28beta4%29/ie7-squish.js"></script>
    
            <link href="<?php echo $this->baseUrl('css/ie.css')?>" rel="stylesheet" type="text/css" media="all">
            <style type="text/css">
            .clear {
              zoom: 1;
              display: block;
            }
            </style>
        <![endif]-->
    <!--[if (gte IE 6)&(lte IE 8)]>
      <script type="text/javascript" src="<?php echo $this->baseUrl('js/selectivizr-min.js')?>"></script>
    <![endif]--> 

<!-- qtip box -->
<script type="text/javascript">
    var flash_messages = jQuery.parseJSON('<?php echo json_encode(Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger')->getMessages()) ?>');

   jQuery(function($){
        if (flash_messages != []){
            showFlashMessages(flash_messages);
        }
        jQuery.address
            .crawlable(1)
            <?php if ($this->baseUrl()!='/'){?>
            .state('<?php echo $this->baseUrl()?>')
            <?php }?>
            .init(function(event) {
            });
        $.ajaxSetup({
            type: "POST",
            dataType:"json",
            error:function(jqXHR, textStatus, errorThrown){
                //console.log(errorThrown);
                //console.log(textStatus);
            },
            cache: true
        })
        <?php if (APPLICATION_ENV == 'production'){
            ?>
            // hack for disabling console.log... 
                console = console || {};
                console.log = function(){};
            <?php 
            }
        ?>
        $.fn.qtip.defaults = $.extend(true, {}, $.fn.qtip.defaults, {
            overwrite: true,
            content: {
                text: true,
                attr: '<img class="throbber" src="<?php echo $this->baseUrl('images/throbber.gif')?>" alt="Loading..." />',
                ajax: {
                    type: 'POST',
                    dataType: 'json',
                    //url: $(this).attr('rel'),
                    once: false,
                    loading: false,
                    error:function(){
                        //alert( jqXHR.responseText);
                    }
                },
                title: {
                    button: true
                }
            },
            events: {
                visible: function(event, api) {
                    // Grab the tooltip element from the API
                    var tooltip = api.elements.tooltip
                    // ...and here's the extra event binds
                    tooltip.bind('tooltipshow', function(event, api) {
                        $.watermark.showAll();
                    })
                    
                }
            },
            show: {
                event: 'click',
                solo: true, // Only show one tooltip at a time
                delay: 0,
                effect: false
            },
            hide: {
                event: 'unfocus'
            }
            <?php /*
            ,position: {
                at: 'bottom center', 
                my: 'top left',
                viewport: $(window), // Keep the tooltip on-screen at all times
                //effect: false // Disable positioning animation
            }, 
            ,style: {
                def:false,
                //classes: 'qtip-wiki qtip-light qtip-shadow'
                classes: 'ui-tooltip-green ui-tooltip-shadow'
            }*/ ?>
        })
        
        $.watermark.options = {
          className: 'watermark'
        };
        
        $('input[type="checkbox"]+ label').disableSelection();
          
       //not sure why it's not working
         $.datepicker.setDefaults({
           dateFormat: 'yy-mm-dd'
        });
       
        $('body').on('click', '[data-hasqtip]' , function(ev) {
            ev.preventDefault();
        });
        
        $("img.lazy").lazyload({
        });
        
        $.ajaxSetup({
          type: "POST",
          dataType:"json",
          error:function(jqXHR, textStatus, errorThrown){
            //console.log(errorThrown);
            //console.log(textStatus);
          },
          cache: true
        })
    });
    
    function jQDialog(title, contentUrl, params, buttons) {
      //if (!width) var width='500';
      //if (!height) var height='500';
      
      //close previous dialog if existed...
      //jQuery(".dialog").dialog('close');
      
      var dialog = jQuery(".dialog").dialog(
        {
            title: title,
            buttons: buttons,
            closeOnEscape: true,
            position: "center",
            width: "auto",
            height: "auto",
            resizable: false,
            autoOpen: false,
            minHeight: false,
            maxHeight: false,
            draggable: false,
            modal: true,
            open: function(event, ui) { 
              $('.ui-widget-overlay').bind('click', function(){ dialog.dialog('close'); }); 
            },
            close:  function (e, ui){
              $(this).html('<p class="loading"><?php echo $this->translate('loading')?>...</p>')
            }
        }).load(contentUrl, params, function() {
            //TODO to fix the dialog with variable height to be middle aligned 
            dialog.dialog('open').dialog("option", "position", "center");;
        });
     }
     
    //begin date and end date for sidebar and feed para
    var today = new Date();
    var end_date = new Date();
    end_date.setDate(today.getDate()+60);
    
    var map_markers_data = changed_feed_input_names = [];
    
    var default_feed_para = feed_para = {};
        default_feed_para['q'] = '';
        default_feed_para['begin_date'] = $.datepicker.formatDate('yy-mm-dd', today);
        default_feed_para['end_date'] = $.datepicker.formatDate('yy-mm-dd', end_date);
        
    // just for the demos, avoids form submit
    jQuery.validator.setDefaults({
      debug: true,
      success: "valid"
    });
</script>
<?php echo $this->partial('js/feeds.phtml'); ?>
</head>