<div id="wrapper">
  <div class="container">
    <header id="header" class="clearfix">
      <h1 class="logo"><a href="index.php"><img src="<?php echo $this->baseUrl('images/logo.jpg')?>" alt="Tagbees" title="Tagbees" /></a></h1>
      <div class="header_right right">
        <div class="header_top clearfix"> 
            <nav class="language">
                <ul>
                    <li><a href="#" ><span class="country_flag EF"></span>English</a>
                        <ul class="div_shadow">
                            <li><a href="#" ><span class="country_flag CF"></span>Chinese</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
          <div class="date">Thursday, July 05, 2012</div>
        </div>
        <div class="header-bottom">
          <nav class="login_reg">
            <ul>
              <li><a href="#login" class="leanModal icon1">Login</a></li>
              <li><a href="<?php echo $this->baseUrl('auth/signup')?>" class="icon2 register">Register</a></li>
            </ul>
          </nav>
          <nav id="menu">
            <ul>
              <li <?php if(Zend_Registry::get('request')->getControllerName() == 'new-event'){ echo "class='current'";}?>><a href="<?php echo $this->baseUrl('new-event');?>">Post</a></li>
              <li><a href="#">Latest</a></li>
              <li><a href="#">Hot</a></li>
              <li><a href="#">Red Dots</a></li>
              <li><a href="#">Green Dots</a></li>
              <li><a href="#">Sports</a></li>
              <li><a href="#">MyList</a></li>
              <li <?php if(Zend_Registry::get('request')->getControllerName() == 'apps'){ echo "class='current'";}?>><a href="<?php echo $this->baseUrl('apps');?>"><strong>apps</strong></a></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
  </div>
</div>
<div id="login" class="popup_window" style="width:400px;">
      <?php echo $this->partial('partials/popup/login.phtml'); ?>
</div>
