<?php //just incase there are external js like google map js
        //echo $this->HeadScript() ?>

<?php echo $this->partial('js/common.phtml')?>

<script type="text/javascript">
   jQuery(function($){
        $('.watcher_close').click(function(){           
            $("#positionable1").hide();
        }); 
    });
</script>

<script type='text/javascript'>

var current = null;

function showresponddiv(messagedivid){
    var id = messagedivid.replace("message-", "respond-"),
        div = document.getElementById(id);

    // hide previous one
    if(current && current != div) {
        current.style.display =  'none';
    }   

    if (div.style.display=="none"){
        div.style.display="inline";
        current = div;
    } 
    else {
        div.style.display="none";
    }
}


jQuery(function($){
    $('.close').click(function () {
                $('.popup').hide();
            }); 
});

</script>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/javascript.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/custom-form-elements.js')?>"> </script>
<script type="text/javascript">
jQuery(function($){
    
    $(window).scroll(function(){
        if ($(this).scrollTop() > 100) {
            $('.scrollup').fadeIn();
        } else {
            $('.scrollup').fadeOut();
        }
    }); 
    
    $('.scrollup').click(function(){
        $("html, body").animate({ scrollTop: 110 }, 600);
        return false;
    });

});
</script>

<script type="text/javascript">
jQuery(function($){
    $('#addTumblr').click(function(){
        $('.addTumblrDiv').slideToggle();
    })
    $('#close').click(function(){
        $(this).parent().hide('slow');
    });
    $('.dblink').click(function() {
        return false;
    }).dblclick(function() {
        window.location = this.href;
        return false;
    });
    $('#changeInput').click(function() {
         $('.changetxt').val('').focus();
     });

});

</script> 
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.leanModal.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.leanModal1.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.leanModal2.min.js')?>"></script>
<script type="text/javascript">
    jQuery(function($) {
        $('a[class*=leanModal]').leanModal({ top :80, closeButton: ".modal_close, .close_window" });       
    });
</script>
<script type="text/javascript">
    jQuery(function($) {
        $('a[class*=leanModal1]').leanModal1({ top :100, closeButton: ".window_close, .confirm_close" });      
    });
</script>
<script type="text/javascript">
    jQuery(function($) {
        $('a[class*=leanModal2]').leanModal1({ top :100, closeButton: ".window_close1" });     
    });
</script>


<!-- dialog box -->
<script type="text/javascript">
  jQuery(function($){
      // Dialog
      jQuery('#dialog').dialog({
          autoOpen: false,
          width: 700,
          buttons: {
              "Ok": function() {
                  jQuery(this).dialog("close");
              },
              "Cancel": function() {
                  jQuery(this).dialog("close");
              }
          }
      });
  });
</script>
