<?php echo $this -> partial('js/sidebar.phtml');  ?>
<aside id="sidebar" class="left">
    <form id="feed_search" name="search" class="search">
        <section class="search_field clearfix">
            <input class="keyword_text feed_filter_input" name="q" type="text" value="<?php echo isset($_GET['q']) ? $_GET['q'] : ''?>"/>
            <input class="keyword_submit" type="submit"  value=""/>
        </section>
        <section class="date_search clearfix">
            <?php $is_all_time = ((isset($_GET['is_all_time']) && ($_GET['is_all_time']==1))||(!isset($_GET['is_all_time']))) ? 1 : 0; ?>
            <input class="feed_filter_input" type="checkbox" <?php if ($is_all_time){?>checked="checked"<?php } ?> name="is_all_time" id="feed_is_all_time" /> <label for="feed_is_all_time" class="checkbox ">All Time</label>
            <div class="text from">
                From
            </div>
            <input type="text" name="begin_date" class="feed_filter_input" value="<?php echo isset($_GET['begin_date']) ? $_GET['begin_date'] : ''; ?>" <?php if ($is_all_time){?>disabled="disabled"<?php } ?>/>
            <div class="text to">
                To
            </div>
            <input type="text" name="end_date" class="feed_filter_input" value="<?php echo isset($_GET['end_date']) ? $_GET['end_date'] : ''; ?>" <?php if ($is_all_time){?>disabled="disabled"<?php } ?>/>
        </section>
    </form>
    <section class="tab_div shadow gap">
        <nav class="tab_link clearfix">
            <ul class="home_tab">
                <li>
                    <a href="#category_tab" class="category_icon"></a>
                </li>
                <li>
                    <a href="#highlight_tab" class="watchlist_icon"></a>
                </li>
                <li>
                    <a href="#bookmark_tab" class="watchlist_icon"></a>
                </li>
            </ul>
        </nav>
        <div class="options">
            <a class="edit_list_order" data-flag="0" href="#">edit list order...</a>
            <a style="display:none" class="refresh" data-flag="0" href="#" style="display:none;">refresh...</a>
        </div>
        <div class="sidebar_tabs">
            <div id="category_tab" class="tab">
                <div class="shown_categories">
                    <ul class="accordions">
                        <li class="accordion" data-expanded="0">
                            <div class="accordion_button">
                                <img src="<?php echo $this->baseUrl('images/icon1.png')?>" alt=" " />My Ride Summary <div class="ui-icon ui-icon-arrowthick-2-n-s movable"></div>
                                <a href="#" class="hide_toggle" data-flag="1">Hide</a>
                            </div>
                            <div class="accordion_content">
                                <div class="accordion_button_sub">
                                    Leisure
                                </div>
                                <div class="accordion_content_sub">
                                    <nav>
                                        <ul>
                                            <li>
                                                <a href="#">Sightseeing</a>
                                            </li>
                                            <li>
                                                <a href="#">Eco Experience</a>
                                            </li>
                                            <li>
                                                <a href="#">Mountaineering</a>
                                            </li>
                                            <li>
                                                <a href="#">Barbecue Camping</a>
                                            </li>
                                            <li>
                                                <a href="#">Ecological</a>
                                            </li>
                                            <li>
                                                <a href="#">Biking</a>
                                            </li>
                                            <li>
                                                <a href="#">Seasonal</a>
                                            </li>
                                            <li>
                                                <a href="#">Farms Parks</a>
                                            </li>
                                            <li>
                                                <a href="#">Country Parks</a>
                                            </li>
                                            <li>
                                                <a href="#">Landmark</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <div class="accordion_button_sub">
                                    Festival
                                </div>
                                <div class="accordion_content_sub">
                                    <nav>
                                        <ul>
                                            <li>
                                                <a href="#">Festival 1</a>
                                            </li>
                                            <li>
                                                <a href="#">Festival 2</a>
                                            </li>
                                            <li>
                                                <a href="#">Festival 3</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <div class="accordion_button_sub">
                                    Regions
                                </div>
                                <div class="accordion_content_sub">
                                    <nav>
                                        <ul>
                                            <li>
                                                <a href="#">Festival 1</a>
                                            </li>
                                            <li>
                                                <a href="#">Festival 2</a>
                                            </li>
                                            <li>
                                                <a href="#">Festival 3</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <div class="accordion_button_sub">
                                    ECO Charity
                                </div>
                                <div class="accordion_button_sub">
                                    Social Service
                                </div>
                                <div class="accordion_button_sub">
                                    Perform Art
                                </div>
                            </div>
                        </li>
                        <li class="accordion" data-expanded="0">
                            <div class="accordion_button">
                                <img src="<?php echo $this->baseUrl('images/icon2.png')?>" alt=" " />Knowledge <div class="ui-icon ui-icon-arrowthick-2-n-s movable"></div>
                                <a href="#" class="hide_toggle" data-flag="1">Hide</a>
                            </div>
                            <div class="accordion_content">
                                <div class="accordion_button_sub">
                                    ECO Charity
                                </div>
                                <div class="accordion_button_sub">
                                    Social Service
                                </div>
                                <div class="accordion_button_sub">
                                    Perform Art
                                </div>
                            </div>
                        </li>
                        <li class="accordion" data-expanded="0">
                            <div class="accordion_button">
                                <img src="<?php echo $this->baseUrl('images/icon3.png')?>" alt=" " />Shopping &amp; Business <div class="ui-icon ui-icon-arrowthick-2-n-s movable"></div>
                                <a href="#" class="hide_toggle" data-flag="1">Hide</a>
                            </div>
                            <div class="accordion_content">
                                <div class="accordion_button_sub">
                                    ECO Charity
                                </div>
                                <div class="accordion_button_sub">
                                    Social Service
                                </div>
                                <div class="accordion_button_sub">
                                    Perform Art
                                </div>
                            </div>
                        </li>
                        <li class="accordion" data-expanded="0">
                            <div class="accordion_button">
                                <img src="<?php echo $this->baseUrl('images/icon4.png')?>" alt=" " />Sports &amp; Outdoors <div class="ui-icon ui-icon-arrowthick-2-n-s movable"></div>
                                <a href="#" class="hide_toggle" data-flag="1">Hide</a>
                            </div>
                            <div class="accordion_content">
                                <div class="accordion_button_sub">
                                    ECO Charity
                                </div>
                                <div class="accordion_button_sub">
                                    Social Service
                                </div>
                                <div class="accordion_button_sub">
                                    Perform Art
                                </div>
                            </div>
                        </li>
                        <li class="accordion" data-expanded="1">
                            <div class="accordion_button">
                                <img src="<?php echo $this->baseUrl('images/icon5.png')?>" alt=" " />Students <div class="ui-icon ui-icon-arrowthick-2-n-s movable"></div>
                                <a href="#" class="hide_toggle" data-flag="1">Hide</a>
                            </div>
                            <div class="accordion_content">
                                <div class="accordion_button_sub">
                                    ECO Charity
                                </div>
                                <div class="accordion_button_sub">
                                    Social Service
                                </div>
                                <div class="accordion_button_sub">
                                    Perform Art
                                </div>
                            </div>
                        </li>
                        <li class="accordion" data-expanded="0">
                            <div class="accordion_button">
                                <img src="<?php echo $this->baseUrl('images/icon6.png')?>" alt=" " />Wonderful <div class="ui-icon ui-icon-arrowthick-2-n-s movable"></div>
                                <a href="#" class="hide_toggle" data-flag="1">Hide</a>
                            </div>
                            <div class="accordion_content">
                                <div class="accordion_button_sub">
                                    ECO Charity
                                </div>
                                <div class="accordion_button_sub">
                                    Social Service
                                </div>
                                <div class="accordion_button_sub">
                                    Perform Art
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="hidden_categories">
                    <ul class="accordions">
                    </ul>
                </div>
            </div>
            <div id="highlight_tab" style="display:none;" class="tab">
                <div class="event_head">
                    <h4>Event Highlights</h4>
                </div>
                <ul data-isfirstloaded="0" class="highlight_list scrollpanel">
                  <li class="load_more">
                      <a style="display:none;" class="more" href="#"> More &gt; </a>
                      <img class="loading" alt="loading..." src="<?php echo $this->baseUrl('images/ajax-loader.gif') ?>" />
                  </li>
                </ul>
            </div>
            <div id="bookmark_tab" style="display:none;" class="tab">
                <div class="event_head clearfix">
                    <h4>Event Reminder</h4>
                    <a href="#" class="more_dot">....</a><a class="simple_personal_event add" href="#"></a>
                    <img data-id="event_time" class="sort disabled" src="<?php echo $this->baseUrl('images/calendar-icon-150x150.png')?>" />
                    <img data-id="bookmark_time" class="sort active" src="<?php echo $this->baseUrl('images/Actions-bookmark-new-list-icon.png')?>" />
                </div>
                <ul data-isfirstloaded="0" class="bookmark_list scrollpanel">
                  <li class="load_more">
                      <a style="display:none;" class="more" href="#"> More &gt; </a>
                      <img class="loading" alt="loading..." src="<?php echo $this->baseUrl('images/ajax-loader.gif') ?>" />
                  </li>
                </ul>
            </div>
        </div>
    </section>
    <section class="tag_cloud shadow gap">
        <h1 class="cloudhead">Tag Cloud</h1>
        <p>
            <span class="font11">Bishop &nbsp; Guertin &nbsp; High &nbsp; School &nbsp; prescription &nbsp; ETL</span><span class="font11 align1">Dynamic PDF Generator </span><span class="font35">VB.NET</span><span class="font11 align1">DevExpress</span><span class="font35">SQL Server</span> risk &nbsp; management &nbsp; <span class="font14">XML</span><span class="font16">HTML</span> &nbsp; asp.net
            <br />
            <span class="font14">ISA</span> user interface Inured Workers Pharmacy <span class="font14">hydraulics pharmaceutical</span> family engineering <span class="font16">SSIS</span><span class="font13">WaWWGO</span> pneumatics <span class="font16">Microsoft Expression Web</span>
            <br />
            Dreamweaver data warehouse
            <br />
            <span class="font16">Domesticating IT</span> vision systems
            <br />
            <span class="font13">Aspose QMS</span><span class="font16">VB6</span><span class="font24">Bridge-Soft</span> Hp <span class="font13">COM</span> education <span class="font13">DotNetNuke</span> Plastics Forming Enterprises <span class="font16">web design</span> University of Lowell <span class="font14">training </span><span class="font16">NEWWA</span> cyber security <span class="font14">SSRS</span> winforms <span class="font14">Crystal Reports</span> AutoCAD Consulting
        </p>
    </section>
    <section class="info_block shadow gap">
        <h2 class="head1"><strong><a href="#">Attraction &gt;</a></strong><a href="#">Venues &amp; Festivals &gt;</a> Open Spaces &gt;</h2>
        <h2 class="head2 blue"><strong>HM Tower of London</strong></h2>
        <p><img src="<?php echo $this->baseUrl('images/v1.gif')?>" alt=" " width="100" class="block_img" />Despite the Tower of London's grim reputation as a place of torture and death, within these walls you will also discover the history of a royal palace, an armoury and a powerful fortress. Don't miss Royal Beasts! Learn about the wild and  wonderous animals that have inhabited the Tower throughout its history.
        </p>
        <p>
            Plus: Discover the priceless Crown Jewels, join a 'Beefeater' tour and hear their bloody tales, stand where famous heads have rolled, learn the legend of the Tower's ravens, storm the battlements and try your hand at siege weapons* in the moat, get to grips with swords and armour and much more
        </p>
    </section>
    <section class="info_block shadow">
        <h2 class="head1"><strong><a href="#">Attraction &gt;</a></strong><a href="#">Venues &amp; Festivals &gt;</a> Open Spaces &gt;</h2>
        <h2 class="head2 orange"><strong> HM Tower of London</strong></h2>
        <p><img src="<?php echo $this->baseUrl('images/v1.gif')?>" alt=" " width="100" class="block_img" />Despite the Tower of London's grim reputation as a place of torture and death, within these walls you will also discover the history of a royal palace, an armoury and a powerful fortress. Don't miss Royal Beasts! Learn about the wild and  wonderous animals that have inhabited the Tower throughout its history.
        </p>
        <p>
            Plus: Discover the priceless Crown Jewels, join a 'Beefeater' tour and hear their bloody tales, stand
        </p>
    </section>
</aside>
